### PR TITLE
fix: update linux script for rails7 upgrade

### LINKED ISSUE #7090: [CW-1779] 2.17.0 - Cron and chat no longer working
### Describe the bug

After running
```sudo cwctl -u```
and waiting for the CLI to upgrade Chatwoot.

The chat is not working correctly. When sending a message from either the customer facing chat or the agent chat, the chat does not update with the latest recent message, I have to refresh the page to get the recent message.

When visiting /monitoring/sidekiq/cron - I get a fatal error in the web server log.
```
 [b10cba06-8096-441e-a711-2cc2b3a4d4af] NoMethodError (undefined method `merge' for ["cron", "*/5 * * * *", "last_enqueue_time", "2023-05-16 08:40:01 +0000", "name", "trigger_scheduled_items_job", "description", "", "message", "{\"retry\":true,\"queue\":\"scheduled_jobs\",\"class\":\"TriggerScheduledItemsJob\",\"args\":[]}", "args", "[]", "status", "enabled", "klass", "TriggerScheduledItemsJob", "symbolize_args", "false", "active_job", "false", "queue_name_delimiter", "", "queue_name_prefix", ""]:Array):
```

I assume the cron is responsible for updating the chat states, which is the reason why the chats are no longer fetching messages.

I am now stuck with a broken chat, and cannot downgrade.

### To Reproduce

Upgrade to latest version through CLI.

### Expected behavior

_No response_

### Environment

Docker

### Cloud Provider

GCP

### Platform

Browser

### Operating system

Ubuntu 20

### Browser and version

Chrome

### Docker (if applicable)

_No response_

### Additional context

_No response_

<sub>[CW-1779](https://linear.app/chatwoot/issue/CW-1779/2170-cron-and-chat-no-longer-working)</sub>

### LINKED ISSUE #7099: [CW-1787] Can't upload avatar for a user
### Describe the bug

It's not possible to upload user's avatar anymore. The web server returns 500 error, the app crashes.

```
May 16 19:26:02 vm-chatwoot chatwoot-web.1[649]: I, [2023-05-16T19:26:02.118527 #649]  INFO -- : source=rack-timeout id=b369297b-70c0-494f-9efd-9343e36ccd54 timeout=15000ms state=ready
May 16 19:26:02 vm-chatwoot chatwoot-web.1[649]: I, [2023-05-16T19:26:02.119039 #649]  INFO -- : [b369297b-70c0-494f-9efd-9343e36ccd54] Started PUT "/api/v1/profile" for 2.139.7.171 at 2023-05-16 19:26:02 +0000
May 16 19:26:02 vm-chatwoot chatwoot-web.1[649]: I, [2023-05-16T19:26:02.123155 #649]  INFO -- : [b369297b-70c0-494f-9efd-9343e36ccd54] Processing by Api::V1::ProfilesController#update as JSON
May 16 19:26:02 vm-chatwoot chatwoot-web.1[649]: I, [2023-05-16T19:26:02.123251 #649]  INFO -- : [b369297b-70c0-494f-9efd-9343e36ccd54]   Parameters: {"profile"=>{"name"=>"Support", "email"=>"xxxxxx@xxxxxxx.com", "display_name"=>"Support", "avatar"=>#<ActionDispatch::Http::UploadedFile:0x00007f1561521688 @tempfile=#<Tempfile:/tmp/RackMultipart20230516-649-hg0yxe.png>, @original_filename="600x600-white.png", @content_type="image/png", @headers="Content-Disposition: form-data; name=\"profile[avatar]\"; filename=\"600x600-white.png\"\r\nContent-Type: image/png\r\n">}}
May 16 19:26:02 vm-chatwoot chatwoot-web.1[649]: I, [2023-05-16T19:26:02.140383 #649]  INFO -- : [b369297b-70c0-494f-9efd-9343e36ccd54]   Disk Storage (0.5ms) Uploaded file to key: tj5gb8l3sx5gapik32nszcw4w76o (checksum: lJcOmaDyPznhJbxIfh8UoA==)
May 16 19:26:02 vm-chatwoot chatwoot-web.1[649]: I, [2023-05-16T19:26:02.141449 #649]  INFO -- : [b369297b-70c0-494f-9efd-9343e36ccd54] [ActiveJob] Enqueued ActiveStorage::AnalyzeJob (Job ID: 8874d040-86f5-43ed-acdf-867c0ced5b23) to Sidekiq(default) with arguments: #<GlobalID:0x00007f155bad6ae8 @uri=#<URI::GID gid://chatwoot/ActiveStorage::Blob/883>>
May 16 19:26:02 vm-chatwoot chatwoot-web.1[649]: I, [2023-05-16T19:26:02.150994 #649]  INFO -- : [b369297b-70c0-494f-9efd-9343e36ccd54]   Rendered api/v1/profiles/update.json.jbuilder (Duration: 8.7ms | Allocations: 2077)
May 16 19:26:02 vm-chatwoot chatwoot-web.1[649]: I, [2023-05-16T19:26:02.152833 #649]  INFO -- : [b369297b-70c0-494f-9efd-9343e36ccd54] Completed 200 OK in 29ms (Views: 8.3ms | ActiveRecord: 6.7ms | Allocations: 7691)
May 16 19:26:02 vm-chatwoot chatwoot-web.1[649]: I, [2023-05-16T19:26:02.153556 #649]  INFO -- : source=rack-timeout id=b369297b-70c0-494f-9efd-9343e36ccd54 timeout=15000ms service=35ms state=completed
May 16 19:26:02 vm-chatwoot chatwoot-web.1[649]: I, [2023-05-16T19:26:02.200432 #649]  INFO -- : source=rack-timeout id=f61be4c4-694f-4f88-9b7c-14867a256e0c timeout=15000ms state=ready
May 16 19:26:02 vm-chatwoot chatwoot-web.1[649]: I, [2023-05-16T19:26:02.200941 #649]  INFO -- : [f61be4c4-694f-4f88-9b7c-14867a256e0c] Started GET "/rails/active_storage/representations/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbk1EIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--d4180d379aaf8b2cdf8679f301922d7444a44f35/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCem9MWm05eWJXRjBTU0lJY0c1bkJqb0dSVlE2RTNKbGMybDZaVjkwYjE5bWFXeHNXd2RwQWZvdyIsImV4cCI6bnVsbCwicHVyIjoidmFyaWF0aW9uIn19--71548903dd08b938501d7454aedd39a3b2344750/600x600-white.png" for 2.139.7.171 at 2023-05-16 19:26:02 +0000
May 16 19:26:02 vm-chatwoot chatwoot-web.1[649]: I, [2023-05-16T19:26:02.203096 #649]  INFO -- : [f61be4c4-694f-4f88-9b7c-14867a256e0c] Processing by ActiveStorage::Representations::RedirectController#show as PNG
May 16 19:26:02 vm-chatwoot chatwoot-web.1[649]: I, [2023-05-16T19:26:02.203159 #649]  INFO -- : [f61be4c4-694f-4f88-9b7c-14867a256e0c]   Parameters: {"signed_blob_id"=>"eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbk1EIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--d4180d379aaf8b2cdf8679f301922d7444a44f35", "variation_key"=>"[FILTERED]", "filename"=>"600x600-white"}
May 16 19:26:02 vm-chatwoot chatwoot-web.1[649]: I, [2023-05-16T19:26:02.207043 #649]  INFO -- : [f61be4c4-694f-4f88-9b7c-14867a256e0c]   Disk Storage (0.2ms) Downloaded file from key: tj5gb8l3sx5gapik32nszcw4w76o
May 16 19:26:02 vm-chatwoot chatwoot-web.1[649]: /usr/share/rvm/gems/ruby-3.2.2/gems/ruby-vips-2.1.4/lib/vips.rb:51: warning: already initialized constant GLib::G_FREE
May 16 19:26:02 vm-chatwoot chatwoot-web.1[649]: /usr/share/rvm/gems/ruby-3.2.2/gems/ruby-vips-2.1.4/lib/vips.rb:51: warning: previous definition of G_FREE was here
May 16 19:26:02 vm-chatwoot chatwoot-web.1[649]: /usr/share/rvm/gems/ruby-3.2.2/gems/ruby-vips-2.1.4/lib/vips.rb:59: warning: already initialized constant GLib::LOG_FLAG_RECURSION
May 16 19:26:02 vm-chatwoot chatwoot-web.1[649]: /usr/share/rvm/gems/ruby-3.2.2/gems/ruby-vips-2.1.4/lib/vips.rb:59: warning: previous definition of LOG_FLAG_RECURSION was here
May 16 19:26:02 vm-chatwoot chatwoot-web.1[649]: /usr/share/rvm/gems/ruby-3.2.2/gems/ruby-vips-2.1.4/lib/vips.rb:60: warning: already initialized constant GLib::LOG_FLAG_FATAL
May 16 19:26:02 vm-chatwoot chatwoot-web.1[649]: /usr/share/rvm/gems/ruby-3.2.2/gems/ruby-vips-2.1.4/lib/vips.rb:60: warning: previous definition of LOG_FLAG_FATAL was here
May 16 19:26:02 vm-chatwoot chatwoot-web.1[649]: /usr/share/rvm/gems/ruby-3.2.2/gems/ruby-vips-2.1.4/lib/vips.rb:63: warning: already initialized constant GLib::LOG_LEVEL_ERROR
May 16 19:26:02 vm-chatwoot chatwoot-web.1[649]: /usr/share/rvm/gems/ruby-3.2.2/gems/ruby-vips-2.1.4/lib/vips.rb:63: warning: previous definition of LOG_LEVEL_ERROR was here
May 16 19:26:02 vm-chatwoot chatwoot-web.1[649]: /usr/share/rvm/gems/ruby-3.2.2/gems/ruby-vips-2.1.4/lib/vips.rb:64: warning: already initialized constant GLib::LOG_LEVEL_CRITICAL
May 16 19:26:02 vm-chatwoot chatwoot-web.1[649]: /usr/share/rvm/gems/ruby-3.2.2/gems/ruby-vips-2.1.4/lib/vips.rb:64: warning: previous definition of LOG_LEVEL_CRITICAL was here
May 16 19:26:02 vm-chatwoot chatwoot-web.1[649]: /usr/share/rvm/gems/ruby-3.2.2/gems/ruby-vips-2.1.4/lib/vips.rb:65: warning: already initialized constant GLib::LOG_LEVEL_WARNING
May 16 19:26:02 vm-chatwoot chatwoot-web.1[649]: /usr/share/rvm/gems/ruby-3.2.2/gems/ruby-vips-2.1.4/lib/vips.rb:65: warning: previous definition of LOG_LEVEL_WARNING was here
May 16 19:26:02 vm-chatwoot chatwoot-web.1[649]: /usr/share/rvm/gems/ruby-3.2.2/gems/ruby-vips-2.1.4/lib/vips.rb:66: warning: already initialized constant GLib::LOG_LEVEL_MESSAGE
May 16 19:26:02 vm-chatwoot chatwoot-web.1[649]: /usr/share/rvm/gems/ruby-3.2.2/gems/ruby-vips-2.1.4/lib/vips.rb:66: warning: previous definition of LOG_LEVEL_MESSAGE was here
May 16 19:26:02 vm-chatwoot chatwoot-web.1[649]: /usr/share/rvm/gems/ruby-3.2.2/gems/ruby-vips-2.1.4/lib/vips.rb:67: warning: already initialized constant GLib::LOG_LEVEL_INFO
May 16 19:26:02 vm-chatwoot chatwoot-web.1[649]: /usr/share/rvm/gems/ruby-3.2.2/gems/ruby-vips-2.1.4/lib/vips.rb:67: warning: previous definition of LOG_LEVEL_INFO was here
May 16 19:26:02 vm-chatwoot chatwoot-web.1[649]: /usr/share/rvm/gems/ruby-3.2.2/gems/ruby-vips-2.1.4/lib/vips.rb:68: warning: already initialized constant GLib::LOG_LEVEL_DEBUG
May 16 19:26:02 vm-chatwoot chatwoot-web.1[649]: /usr/share/rvm/gems/ruby-3.2.2/gems/ruby-vips-2.1.4/lib/vips.rb:68: warning: previous definition of LOG_LEVEL_DEBUG was here
May 16 19:26:02 vm-chatwoot chatwoot-web.1[649]: /usr/share/rvm/gems/ruby-3.2.2/gems/ruby-vips-2.1.4/lib/vips.rb:71: warning: already initialized constant GLib::GLIB_TO_SEVERITY
May 16 19:26:02 vm-chatwoot chatwoot-web.1[649]: /usr/share/rvm/gems/ruby-3.2.2/gems/ruby-vips-2.1.4/lib/vips.rb:71: warning: previous definition of GLIB_TO_SEVERITY was here
May 16 19:26:02 vm-chatwoot chatwoot-web.1[649]: /usr/share/rvm/gems/ruby-3.2.2/gems/ruby-vips-2.1.4/lib/vips.rb:86: warning: already initialized constant GLib::LOG_HANDLER
May 16 19:26:02 vm-chatwoot chatwoot-web.1[649]: /usr/share/rvm/gems/ruby-3.2.2/gems/ruby-vips-2.1.4/lib/vips.rb:86: warning: previous definition of LOG_HANDLER was here
May 16 19:26:02 vm-chatwoot chatwoot-web.1[649]: /usr/share/rvm/gems/ruby-3.2.2/gems/ruby-vips-2.1.4/lib/vips.rb:155: warning: already initialized constant GObject::GBOOL_TYPE
May 16 19:26:02 vm-chatwoot chatwoot-web.1[649]: /usr/share/rvm/gems/ruby-3.2.2/gems/ruby-vips-2.1.4/lib/vips.rb:155: warning: previous definition of GBOOL_TYPE was here
May 16 19:26:02 vm-chatwoot chatwoot-web.1[649]: /usr/share/rvm/gems/ruby-3.2.2/gems/ruby-vips-2.1.4/lib/vips.rb:156: warning: already initialized constant GObject::GINT_TYPE
May 16 19:26:02 vm-chatwoot chatwoot-web.1[649]: /usr/share/rvm/gems/ruby-3.2.2/gems/ruby-vips-2.1.4/lib/vips.rb:156: warning: previous definition of GINT_TYPE was here
May 16 19:26:02 vm-chatwoot chatwoot-web.1[649]: /usr/share/rvm/gems/ruby-3.2.2/gems/ruby-vips-2.1.4/lib/vips.rb:157: warning: already initialized constant GObject::GUINT64_TYPE
May 16 19:26:02 vm-chatwoot chatwoot-web.1[649]: /usr/share/rvm/gems/ruby-3.2.2/gems/ruby-vips-2.1.4/lib/vips.rb:157: warning: previous definition of GUINT64_TYPE was here
May 16 19:26:02 vm-chatwoot chatwoot-web.1[649]: /usr/share/rvm/gems/ruby-3.2.2/gems/ruby-vips-2.1.4/lib/vips.rb:158: warning: already initialized constant GObject::GDOUBLE_TYPE
May 16 19:26:02 vm-chatwoot chatwoot-web.1[649]: /usr/share/rvm/gems/ruby-3.2.2/gems/ruby-vips-2.1.4/lib/vips.rb:158: warning: previous definition of GDOUBLE_TYPE was here
May 16 19:26:02 vm-chatwoot chatwoot-web.1[649]: /usr/share/rvm/gems/ruby-3.2.2/gems/ruby-vips-2.1.4/lib/vips.rb:159: warning: already initialized constant GObject::GENUM_TYPE
May 16 19:26:02 vm-chatwoot chatwoot-web.1[649]: /usr/share/rvm/gems/ruby-3.2.2/gems/ruby-vips-2.1.4/lib/vips.rb:159: warning: previous definition of GENUM_TYPE was here
May 16 19:26:02 vm-chatwoot chatwoot-web.1[649]: /usr/share/rvm/gems/ruby-3.2.2/gems/ruby-vips-2.1.4/lib/vips.rb:160: warning: already initialized constant GObject::GFLAGS_TYPE
May 16 19:26:02 vm-chatwoot chatwoot-web.1[649]: /usr/share/rvm/gems/ruby-3.2.2/gems/ruby-vips-2.1.4/lib/vips.rb:160: warning: previous definition of GFLAGS_TYPE was here
May 16 19:26:02 vm-chatwoot chatwoot-web.1[649]: /usr/share/rvm/gems/ruby-3.2.2/gems/ruby-vips-2.1.4/lib/vips.rb:161: warning: already initialized constant GObject::GSTR_TYPE
May 16 19:26:02 vm-chatwoot chatwoot-web.1[649]: /usr/share/rvm/gems/ruby-3.2.2/gems/ruby-vips-2.1.4/lib/vips.rb:161: warning: previous definition of GSTR_TYPE was here
May 16 19:26:02 vm-chatwoot chatwoot-web.1[649]: /usr/share/rvm/gems/ruby-3.2.2/gems/ruby-vips-2.1.4/lib/vips.rb:162: warning: already initialized constant GObject::GOBJECT_TYPE
May 16 19:26:02 vm-chatwoot chatwoot-web.1[649]: /usr/share/rvm/gems/ruby-3.2.2/gems/ruby-vips-2.1.4/lib/vips.rb:162: warning: previous definition of GOBJECT_TYPE was here
May 16 19:26:02 vm-chatwoot chatwoot-web.1[649]: I, [2023-05-16T19:26:02.210166 #649]  INFO -- : [f61be4c4-694f-4f88-9b7c-14867a256e0c] Completed 500 Internal Server Error in 7ms (ActiveRecord: 0.5ms | Allocations: 2696)
May 16 19:26:02 vm-chatwoot chatwoot-web.1[649]: F, [2023-05-16T19:26:02.211443 #649] FATAL -- : [f61be4c4-694f-4f88-9b7c-14867a256e0c]
May 16 19:26:02 vm-chatwoot chatwoot-web.1[649]: [f61be4c4-694f-4f88-9b7c-14867a256e0c] LoadError (Could not open library 'vips.so.42': vips.so.42: cannot open shared object file: No such file or directory.
May 16 19:26:02 vm-chatwoot chatwoot-web.1[649]: Could not open library 'libvips.so.42': libvips.so.42: cannot open shared object file: No such file or directory):
May 16 19:26:02 vm-chatwoot chatwoot-web.1[649]: [f61be4c4-694f-4f88-9b7c-14867a256e0c]
May 16 19:26:02 vm-chatwoot chatwoot-web.1[649]: [f61be4c4-694f-4f88-9b7c-14867a256e0c] ffi (1.15.5) lib/ffi/library.rb:145:in `block in ffi_lib'`
```

### To Reproduce

1. Go to Profile Settings
2. Upload avatar
3. Update Profile
4. No UI errors are visible, but in the console you can see 500
5. Reload the website, image is not loaded

### Expected behavior

Avatar is replaced after uploading

### Environment

Linux VM

### Cloud Provider

Azure

### Platform

Browser

### Operating system

Ubuntu

### Browser and version

Version 113.0.5672.92 (Official Build) (arm64)

### Docker (if applicable)

_No response_

### Additional context

v2.17.0

<sub>[CW-1787](https://linear.app/chatwoot/issue/CW-1787/cant-upload-avatar-for-a-user)</sub>

### PR DESCRIPTION
**Pull request by vishnu-narayanan**
# Pull Request Template

## Description

- Install latest version of redis for new installations
- Install libvips package to resolve the activestorage image processing issues
- Upgrade redis and install libvips for existing installations during upgrade phase

Fixes #7099
Fixes #7090

To upgrade to the latest version of `cwctl`, existing installations should 

```
cwctl --version
wget https://get.chatwoot.app/linux/install.sh -O /usr/local/bin/cwctl && chmod +x /usr/local/bin/cwctl
cwctl --version
```

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Tested on an existing Linux installation for the upgrade phase
- Tested on a fresh instance

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by LiamAshdown** [comment]
How would I go updating `cwctl`?

I am assuming I need to do this manually? Would be great if the CLI can self-update automatically.

**Comment by vishnu-narayanan** [comment]
>How would I go updating cwctl?
>I am assuming I need to do this manually? Would be great if the CLI can self-update automatically.

@LiamAshdown We will have to update it manually for now. I will open a new issue to add the self-updating feature. 😅

**Comment by vishnu-narayanan** [comment]
Incremental story --> https://github.com/chatwoot/chatwoot/issues/7108

**Comment by LiamAshdown** [comment]
> > How would I go updating cwctl?
> > I am assuming I need to do this manually? Would be great if the CLI can self-update automatically.
> 
> @LiamAshdown We will have to update it manually for now. I will open a new issue to add the self-updating feature. 😅
> 
> ref: https://www.chatwoot.com/docs/self-hosted/deployment/chatwoot-ctl#install-or-upgrade-chatwoot-ctl

Sorry to be a pain haha!

Once you've got chatwoot running on your machine - there's no other reason to touch the machine again unless you want to upgrade the app, so a self-updating CLI would prevent issues like v2.17 where I was missing dependencies and preventing the app from correctly working.

Also for future versions of Chatwoot - I would need to manually check the CLI script and do a diff to my version of CLI to the latest version of the CLI to make sure I am not missing a new dependencies. Not sort of chore I would like to do in my day-to-day tasks.

This would prevent issues like 2.17 from occurring and potentially stop their Chatwoot from working.

**Comment by vishnu-narayanan** [comment]
@LiamAshdown Thank you for the feedback. We will prioritize this feature at the earliest.

**Review by sojan-official — APPROVED** [review]

**Pull request merged**
