### PR TITLE
feat: add chatwoot instance status in superadmin

### PR DESCRIPTION
**Pull request by vishnu-narayanan**
# Pull Request Template

## Description

- Add an instance status page in superadmin which  lists
  - Chatwoot version
  - Git hash of the latest deployed code
  - Postgres database alive
  - Redis database alive

Fixes https://github.com/chatwoot/product/issues/686

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

This one is from Manali. Tested locally on the superrr cold  :cold_face: MacBook. 

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by vishnu-narayanan** [comment]
image

**Comment by pranavrajs** [comment]
@vishnu-narayanan Sharing the feedback we discussed yesterday here. 

- The status page inside the super admin console wouldn't work if the Redis or Postgres is down. 
- Add both these statuses to `/api` endpoint. 
- Along with the Redis/Postgres server alive status, we can add more information about the version of the server and the memory usage as shown below.

Screenshot 2023-01-06 at 6 10 40 PM

**Review by pranavrajs — CHANGES_REQUESTED** [review]
Please see the comment above.

**Comment by vishnu-narayanan** [comment]
image

**Review by sojan-official — APPROVED** [review]

**Comment by vishnu-narayanan** [comment]
GET `/api`

```
{
  "version": "2.13.0",
  "timestamp": "2023-01-30 12:47:44",
  "queue_services": "ok",
  "data_services": "ok"
}
```

**Pull request merged**
