### PR TITLE
fix: Facebook reauthorization mailer

### LINKED ISSUE #4688: Enhancement: Facebook re-authentication mailer for agents
**Is your enhancement request related to a problem? Please describe.**
We don't send any emails to agents related to the Facebook sessions expired.

**Describe the solution you'd like**
Send a similar mail that we send to an admin about the expired session.
And send when the session expired while receiving messages from old open conversation contact.

**Describe alternatives you've considered**
-

**Additional context**
-

### PR DESCRIPTION
**Pull request by tejaswinichile**
# Pull Request Template

## Description

If Facebook fails in the authorization or session reset happens while we get the new message, only admin used to get the mail notification about the same, now we are sending it to all the inbox members.

Fixes #4688 

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by sojan-official** [comment]
@tejaswinichile for larger inboxes with over 20,30 agents this email might be super repetitive. We could rather look at having a UI indication, with a popover indicating that the integration is facing issues. 

we could this base this on the reauthorization_required attribute. 

Screenshot 2022-05-24 at 12 51 29 PM

cc: @pranavrajs

**Comment by sojan-official** [comment]
@tejaswinichile Since the agents don't have access to the inbox configuration pages, I am not sure there be a significant gain in exposing them to this information. 

the only action that the agent can do with this email is to alert the administrator, which is already done via the admin notification mailer so this would feel repetitive. 

Also, the copy of the current email could lead to confusion.  

-  An agent won't have access to the current action url ( which redirects to the inbox settings page )
- "Your Facebook page connection has expired" ( a support agent in the system might have limited role/knowledge about the page connection / configuring it )

**Comment by tejaswinichile** [comment]
@sojan-official How about this?
facebook_reauth

**Review by fayazara — APPROVED** [review]
FE code LGTM!

**Comment by sojan-official** [comment]
We could make this generic and have this available for email channel as well

**Comment by tejaswinichile** [comment]
@sojan-official 

>  We could make this generic and have this available for the email channel as well

I would make a note of this in new issue ticket, will that work?

**Review by fayazara — APPROVED** [review]

**Pull request merged**
