### PR TITLE
fix: API payload compatibility

### PR DESCRIPTION
**Pull request by scmmishra**

### CODE REVIEW

**Review by pranavrajs — CHANGES_REQUESTED** [review]
@scmmishra I'm not sure if the implementation is correct. Please see the Loom video here. https://www.loom.com/share/5b003024e4004e689945c03f9ca8486d

**Comment by scmmishra** [comment]
CC: @muhsin-k PTAL whenever you can

**Comment by scmmishra** [comment]
@muhsin-k PTAL whenever you can

**Comment by pranavrajs** [comment]
Closing in favor of https://github.com/chatwoot/chatwoot/pull/8518

**Pull request closed without merging**
