### PR TITLE
feat: Support input_select messages on telegram

### PR DESCRIPTION
**Pull request by ChamathKB**
# Telegram interactive button support

## Description

Adding interactive button support for telegram for outgoing and incoming messages. Compatible with button payload receives from RASA bot to users. Additionally support images send with buttons (alternative to carousels) 
Reference for RASA payloads: https://rasa.com/docs/rasa/connectors/telegram

Fixes # ([issue](https://github.com/chatwoot/chatwoot/issues/4736))

## Type of change

Please delete options that are not relevant.

- [X] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Developed a telegram channel supported RASA bot and connected to chatwoot for testing.

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by sojan-official** [comment]
Note: 
- Cleaning up this PR to handle just the case of call back button for telegram
- Adding appropriate specs

**Comment by sojan-official** [comment]
## QA 


https://user-images.githubusercontent.com/73185/228258231-9aff715c-9ef2-4e8c-b06d-00eb96d0ec49.mov

**Comment by alejamp** [comment]
> @ChamathKB I hope you can do the same for whatsapp I can sponsore it please reach me on discord if you able to do it this is my discord username Voko2255#2582

I can sponsor this feat too.
How long do you think it's gonna take to see this feat productive live on Chatwoot Cloud services?
Whatsapp interactive lists button is key for me to decide if a stay developing over Chatwoot or move to other alternatives.

**Comment by ChamathKB** [comment]
@voko3456 @alejamp sure, i'll look into "input_select" message support for whatsapp as well. There might be limitations like supporting only 3 buttons per message because whatsapp interactive message API limits button payload. No need to sponsor or anything. If you really like to sponsor you can sponsor chatwoot team for their great work.

**Pull request merged**
