### PR TITLE
Feat: Include previous messages in mention/assign notifications email

### LINKED ISSUE #3321: Include previous messages for more context when sending @mention/@assign email notification
**Is your enhancement request related to a problem? Please describe.**
Right now, an agent gets an email notification when they are mentioned/assigned in a conversation. 

The `@mention` notification right now only includes the message in which they are mentioned. The `@assign` notification right now does not have any information other than the assignment.

**Describe the solution you'd like**
Include previous messages in the conversation when sending an email notification. This would make the email notifications more informative and useful. 
 
**Describe alternatives you've considered**
A possible iteration over this would be to include more details about the conversation in email notification that is available in the sidebar.

**Additional context**
n/a

### PR DESCRIPTION
**Pull request by shivamsinghchahar**
# Pull Request Template

## Description

Include upto last 5 messages while sending the email notification to the agent when they are assigned to or mentioned in a conversation.

Fixes #3321 

## Type of change

New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

- Added a test case for `recent_messages` method that returns upto last 5 messages.
- Manually tested the email notification by mentioning and assigning a conversation to the agent.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

<details>
<summary>Screenshots</summary>
<br>
When the agent is mentioned:
Screenshot 2021-11-17 at 5 46 48 PM
<br>
When a conversation is assigned to the agent:
<br>
Screenshot 2021-11-17 at 5 47 14 PM
</details>

### CODE REVIEW

**Review by vishnu-narayanan — APPROVED** [review]
LGTM

**Comment by tejaswinichile** [comment]
@shivamsinghchahar The code looks good. Can you add some screenshots of the testing part, how it looks in the email?

**Comment by shivamsinghchahar** [comment]
Hi, @tejaswinichile Thanks a lot for the review! I have updated the PR description to include screenshots. Please let me know if any changes are required.

**Review by tejaswinichile — APPROVED** [review]
💯

**Comment by tejaswinichile** [comment]
Should we add just instead of name, `{name} wrote` ? 
It's more of suggestion we can always take it later. 

Cc @pranavrajs

**Pull request merged**
