### PR TITLE
chore: Repalce message formatter mixin with useMessageFormatter [CW-3470]

### PR DESCRIPTION
**Pull request by fayazara**
# Pull Request Template

## Description

Replaced the old messageFormatterMixin with a useMessageFormatter composable

### CODE REVIEW

**Review by scmmishra — COMMENTED** [review]
@fayazara code looks good to me, I'll just test it locally before approving. 

Need to add specs

**Comment by fayazara** [comment]
Almost done with all the missing specs, will update PRs

**Comment by scmmishra** [comment]
@fayazara PTAL

**Comment by fayazara** [comment]
@scmmishra added the missing sped

**Review by scmmishra — APPROVED** [review]

**Pull request merged**
