### PR TITLE
Send emails via sidekiq

### PR DESCRIPTION
**Pull request by antodoms**
## Description

use ActiveJob Queue Adapter as Sidekiq to send emails via sidekiq. This feature allows sending devise and mailer emails to be enqueued in sidekiq before it is actually sent. 

## Type of change
- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## How Has This Been Tested?

In addition to the rails service, we also need to run `sidekiq` service to send an email out to the SMTP server. This can be done locally by running `docker-compose run rails bundle exec sidekiq` in one of the terminal. You can also see the enqueued mailers in the sidekiq web console by visiting http://0.0.0.0:3000/sidekiq (you need to login to the application with an administrator account to access web console)

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by pranavrajs** [comment]
@sojan-official Shouldn't we add this as a separate entry in Procfile ?

**Comment by sojan-official** [comment]
@pranavrajs  yep . 
@antodoms  we should add a sidekiq entry in Procfile for this to work in heroku.
Also, should we have the sidekiq worker started in our docker file ?

**Comment by antodoms** [comment]
@pranavrajs @sojan-official I thought I will do docker update as a separate PR. But I will test one click heroku install and see if I need to create a new Procfile for it.

**Comment by pranavrajs** [comment]
@antodoms 
>I thought I will do docker update as a separate PR

This should be fine.

> But I will test one click heroku install and see if I need to create a new Procfile for it.

Please update the Procfile.dev file as well.

**Comment by antodoms** [comment]
@pranavrajs I have added Sidekiq worker to Procfile.dev as per your reccomendation

**Pull request merged**
