### PR TITLE
feat: Ability to receive contact on whatsapp inbox

### PR DESCRIPTION
**Pull request by jacsonsantospht**
## Description

This pull request is about to receive and add contact message on conversations for whatsapp inbox.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

- Create WhatsApp innbox
- Open Postman
- Send POST request to Webhook
`http://localhost:3000/webhooks/whatsapp/MY_WHATSAPP_INBOX`

```
{
    "contacts": [
        {
            "profile": {
                "name": "Jacson Santos"
            },
            "wa_id": "55419879944XX"
        }
    ],
    "messages": [
        {
            "contacts": [
                {
                    "addresses": [],
                    "emails": [],
                    "ims": [],
                    "name": {
                        "first_name": "João",
                        "formatted_name": "João"
                    },
                    "org": {},
                    "phones": [
                        {
                            "phone": "+55 33 9165-XXXX",
                            "type": "Celular",
                            "wa_id": "55339165XXXX"
                        }
                    ],
                    "urls": []
                }
            ],
            "from": "55419879944XX",
            "id": "ABEGVUGFAhdzAhAII6LApqvqR-45u",
            "timestamp": "1672768565",
            "type": "contacts"
        }
    ]
}
```
Captura de tela de 2023-01-23 10-36-06

## Checklist:

- [x] My code follows the style guidelines of this project

### CODE REVIEW

**Comment by nithindavid** [comment]
@jacsonsantospht Thanks for creating this PR! I have updated the style for the contact card. Can you fix
1. The rubocop issues in `app/services/whatsapp/incoming_message_base_service.rb` 
2. The name is coming as message content. Can you remove this as the card already supports `name`

**Comment by jacsonsantospht** [comment]
> 2\. The name is coming as message content. Can you remove this as the card already supports `name`

@nithindavid, I will make these improvements

**Comment by pranavrajs** [comment]
@jacsonsantospht There have been some changes since you raised the PR. So I thought I will help here and get this merged. I clean up the PR today and get this to merge.

**Comment by pranavrajs** [comment]
@sojan-official @tejaswinichile I'm merging this PR as the specs are passing. There is a codeclimate issue. Please have a look. I don't agree with that suggestion. If needed, I can raise a PR separately.

**Review by pranavrajs — APPROVED** [review]

**Pull request merged**
