### PR TITLE
feat: use addEventListener instead of onmessage

### PR DESCRIPTION
**Pull request by scmmishra**
This one is a fix for an interesting issue pointed here: https://github.com/chatwoot/chatwoot/issues/10339

### What was happening 

The user had two dashboard apps configured, each of which could request data from the parent Chatwoot window by posting a message with `window.parent.postMessage('chatwoot-dashboard-app:fetch-info', '*')`

The "Dashboard Frame" component had a listener set on window using `window.onmessage`, this was added during the `mounted` event

https://github.com/chatwoot/chatwoot/blob/601a0f8a766e8a02a48a743346a4f3b44b7019c6/app/javascript/dashboard/components/widgets/DashboardApp/Frame.vue#L55-L65

The problem with this approach is the first iframe on mount attaches this event correctly, but every subsequent frame opened `onmessage` would be overridden. Now since the dashboard app frames are caches (see: https://github.com/chatwoot/chatwoot/commit/e6505fc7a42ca9f3de1735939b488a18a979adcb) if you wen't back to a particular tab that was already loaded the `mounted` would not get triggered again, that means the older `onmessage` would still be active and will receive the messages exclusively

### What is the fix

The simplest fix is to use `addEventListener`, that way every `Frame` handles it's own events. **However there is a caveat here;** If one app requests data using `fetch-info`, every frame will get the data back. I have a feeling this is not intended, to ensure this does not happen we can add a check to `triggerEvent` method

```diff
    triggerEvent(event) {
+     if (!this.isVisible) return;
      if (event.data === 'chatwoot-dashboard-app:fetch-info') {
        this.onIframeLoad(0);
      }
    },
```

### CODE REVIEW

**Review by pranavrajs — CHANGES_REQUESTED** [review]
Please add the isVisible check as well before we merge it.

**Comment by bfontaine** [comment]
Is there no way to identify the frame that sent the event, instead of silently ignoring it if the frame is not visible?

**Comment by scmmishra** [comment]
> Is there no way to identify the frame that sent the event, instead of silently ignoring it if the frame is not visible?

At the moment there isn't a straightforward way to do this that I am aware of. We could compare the event origin with the dashboard app URL, but it would fire more than once if you have multiple dashboard apps from the same origin.

**Review by pranavrajs — APPROVED** [review]

**Comment by bfontaine** [comment]
`event.source` should be the window that emitted the event: 

> source:
> A reference to the [window](https://developer.mozilla.org/en-US/docs/Web/API/Window) object that sent the message; you can use this to establish two-way communication between two windows with different origins.

https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage#source

**Pull request merged**
