### PR TITLE
feat: Dialogflow Integration V1

### PR DESCRIPTION
**Pull request by sojan-official**
# Pull Request Template

closes: #1171 

## Description

Configure Dialogflow Integration from your console. 

```
hook =  Inbox.first.hooks.new
hook.account_id = Inbox.first.account_id
hook.type = "inbox"
hook.app_id = "dialogflow"
hook.settings["project_id"] = "your dialogflow project id"
hook.settings["credentials"] = Hash ( contents of your  dialogflow credential key file)
hook.save!
```

## Configuring Handoff in Dialogflow
Screenshot 2021-04-25 at 11 37 16 PM

## Configuring Options Payload
Screenshot 2021-04-25 at 11 38 16 PM

### CODE REVIEW

**Review by pranavrajs — APPROVED** [review]

**Comment by abasit007** [comment]
can anyone explain what we need to do after following these steps as i did the same but still can't get messages of bot into chatwoot app

**Comment by sojan-official** [comment]
@abasit007  once you add the configuration required for the integration hook, every time a message comes in, chatwoot will try to communicate with Dialogflow and fetch a response.  please check your logs to see if there are any errors.

**Comment by abasit007** [comment]
@sojan-official i have done everything but url is not being called and there are no errors

**Comment by abasit007** [comment]
update i have got the response of webhook from dialogflow but it is the url api/v1/integrations/webhooks
which is for slack incomming and i dont knwo where to call webhook and make conversation for it
it will be great if you could assist me genrating conversation in chatwoot using dialogflow webhook response

**Comment by sojan-official** [comment]
@abasit007  lets move the conversation to https://github.com/chatwoot/chatwoot/issues/2302

**Pull request merged**
