### PR TITLE
feat: add a common upload endpoint

### PR DESCRIPTION
**Pull request by scmmishra**
This PR adds a common upload endpoint that returns the file URL, PR also includes a JS utility to use the endpoint that returns a Promise for the file URL

## Type of change

- [x] New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by scmmishra** [comment]
@iamsivin you can use this as a base for uploading the signatures

**Comment by iamsivin** [comment]
> @iamsivin you can use this as a base for uploading the signatures

Sure. I can work after merging these 2 PRs. https://github.com/chatwoot/prosemirror-schema/pull/16 https://github.com/chatwoot/chatwoot/pull/7777

**Comment by scmmishra** [comment]
@sojan-official this is ready to go

**Review by sojan-official — APPROVED** [review]
LGTM. @scmmishra can we take a follow-up to remove /unify the following endpoints in the backend. remove the duplicate code.
- https://github.com/chatwoot/chatwoot/blob/25c3fb3c36be37b075d737c1dae8b4b3a4316451/app/controllers/api/v1/accounts/portals_controller.rb#L56
- https://github.com/chatwoot/chatwoot/blob/25c3fb3c36be37b075d737c1dae8b4b3a4316451/app/controllers/api/v1/accounts/articles_controller.rb#L39
- https://github.com/chatwoot/chatwoot/blob/25c3fb3c36be37b075d737c1dae8b4b3a4316451/app/controllers/api/v1/accounts/macros_controller.rb#L42


probably worth doing a search for  `ActiveStorage::Blob.create_and_upload` in the codebase and see which ones remain relevant

**Comment by scmmishra** [comment]
> LGTM. @scmmishra can we take a follow-up to remove /unify the following endpoints in the backend. remove the duplicate code.

Sure, will have the PR up by EOD

**Pull request merged**
