### PR TITLE
Chore: Replaced dependent: destroy with dependent: :destroy_async in all models

### LINKED ISSUE #3221: chore: replace dependent: :destroy with :destroy_async
Models in chatwoot like Account, Conversations, etc could have. a large number of associations.  replace the dependent : :destroy for these associations with `:destroy_async`

> When we have a large system with multiple layered hierarchies of associated objects, cascading deletes might fail. A model could have associations that are destroyed which in turn trigger other deletions and this can continue down a complex tree. Such cascading deletes could turn out to be quite time consuming and might be rolled back in case of a server timeout error.

ref: 
https://www.bigbinary.com/blog/rails-6-1-allows-associations-to-support-destroy_async-option-with-dependent-key
https://blog.saeloun.com/2020/11/18/rails-6.1-adds-support-for-destroying-dependent-associations-in-the-background.html

### PR DESCRIPTION
**Pull request by akhilgkrishnan**
# Pull Request Template

## Description

Replaced dependent destroy with destroy async in all models

Fixes #3221 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Rspec

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by tejaswinichile** [comment]
@akhilgkrishnan Yes, just for account delete one account and wait for async to complete and check if the dependent inboxes have been deleted.

**Comment by tejaswinichile** [comment]
```it 'destroy async associations' do
    account = FactoryBot.create(:account)
    inbox = FactoryBot.create(:inbox, account: account)

    expect(account.inboxes.count).to be(1)

    account.destroy

    assert_enqueued_jobs 2

    expect(account.inboxes.count).to be(0)
 end```
@akhilgkrishnan Please refer this, we are expecting something like this,  I think you will need to add `  config.include ActionCable::TestHelper` in `rails_helper.rb`

**Comment by akhilgkrishnan** [comment]
> ```
> it 'destroy async associations' do
>     account = FactoryBot.create(:account)
>     inbox = FactoryBot.create(:inbox, account: account)
> 
>     expect(account.inboxes.count).to be(1)
> 
>     account.destroy
> 
>     assert_enqueued_jobs 2
> 
>     expect(account.inboxes.count).to be(0)
>  end
> ```
> 
> @akhilgkrishnan Please refer this, we are expecting something like this, I think you will need to add `config.include ActionCable::TestHelper` in `rails_helper.rb`

@tejaswinichile I already tried this, but it fails

**Comment by tejaswinichile** [comment]
@akhilgkrishnan Refer this, works fine https://github.com/chatwoot/chatwoot/pull/3336

**Comment by sojan-official** [comment]
@tejaswinichile The code looks good to me. If there are no other concerns, let's get this merged.

**Review by sojan-official — APPROVED** [review]

**Review by tejaswinichile — APPROVED** [review]
LGTM 💯

**Pull request merged**
