### PR TITLE
Initial testing with jest

### PR DESCRIPTION
**Pull request by fluffynuts**
Addresses #97 

Test setup is pure Jest. I initially started with `vue-cli-service`, but had issues convincing that to use babel so that `import` syntax could be retained in testing. I finally got jest working without vue-cli-service (which runs jest, and ensures availaibility of the peer dependencies that I installed to get jest working).

Some notes:
- I've brought in some useful matchers from our own internal Vue projects, ported from typescript
- I've mocked a few things to get initial testing working
- I've imported the tests I wrote for https://github.com/chatwoot/chatwoot/pull/95 whilst I was working on that PR
- I'm sure there's room for improvement (:

To run:
- `npm test` for a once-off
- `npm run autotest` to run jest in watch-mode
- `npm run cover` to run tests once with coverage

### CODE REVIEW

**Comment by sojan-official** [comment]
@fluffynuts  could you also add the tests to our circleci config,  If you need help with that let me know. 
thanks a lot for contributing :)

**Comment by fluffynuts** [comment]
I'll look into it. I'd like to try to figure it out myself (that's how I'll learn best!), but if I get stuck, I'll come running for help 🙂

**Comment by pranavrajs** [comment]
@fluffynuts Nice work! Thanks. A couple of thoughts.

1. We use `yarn`. Please remove `package-lock`
2. Wouldn't it be better to rename the commands as `test`, `test:coverage` and `test:watch` to make it easier to understand?
3. Test Matchers looks pretty useful, thanks for that.

**Comment by fluffynuts** [comment]
Ok, it looks like I've integrated javascript tests properly with CircleCI (https://app.circleci.com/jobs/github/chatwoot/chatwoot/167) -- please let me know if I've put tests in the wrong place or something like that; I assumed that right after linting would be a good time to test (this is when I normally do it)

**Comment by sojan-official** [comment]
Ps: We're sending stickers to our contributors ❤️ Let us know your details https://chatwoot.typeform.com/to/ihG9Gz

**Pull request merged**
