### PR TITLE
Feature: Add spanish (Spain) language

### PR DESCRIPTION
**Pull request by fv3rdugo**
# Pull Request Template

## Description
Add spanish (Spain) language to the project. Adapting the expressions to Spanish and using inclusive language.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?
Not yet.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by sojan-official** [comment]
@fv3rdugo thanks a lot for looking into this. could you also help us with the frontend translations?  The dashboard uses the language files in  the directory `app/javascript/dashboard/i18n/locale` 

https://github.com/chatwoot/chatwoot/tree/develop/app/javascript/dashboard/i18n/locale

you could make a  copy of the en folder, rename it to Spanish.  and change the values for English keys. . Meanwhile, we will add settings for Spanish.

**Comment by whiteyhat** [comment]
Well done @fv3rdugo 👍

**Comment by sojan-official** [comment]
@fv3rdugo if you prefer translate.chatwoot.com we can merge the existing changes and sync it over there. we can work on the remaining changes over there.  let us know what you prefer :)

**Comment by fv3rdugo** [comment]
Ok it seem the better option, no problem with this.

**Pull request merged**
