### PR TITLE
fix: Fixes extra backslash while breaking paragraphs [CW-1505]

### PR DESCRIPTION
**Pull request by nithindavid**
## Description
Cases tested - https://www.loom.com/share/ebf4873ed9bd435b8462141cf807fed2?sid=d9807158-b720-485c-bb88-b0e4b1c85125

Fixes # (issue)
https://linear.app/chatwoot/issue/CW-1505/editor-adds-a-stray-/-in-a-conversation

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by scmmishra — APPROVED** [review]
Tested this locally, fixes the issue

**Review by muhsin-k — COMMENTED** [review]
@nithindavidI have found a small issue.

https://www.loom.com/share/3f67d3638bd94bdaac50de0e02384ccf

**Comment by nithindavid** [comment]
Could not find a solution for the bug mentioned.Working on it

**Comment by scmmishra** [comment]
@nithindavid I was still getting extra slashes, just like @muhsin-k showed in the video. Do I need to have prosemirror-schema on a different version or something?

**Comment by nithindavid** [comment]
@scmmishra Let me try on staging.

**Review by scmmishra — APPROVED** [review]

**Pull request merged**
