### PR TITLE
feat: better download for conversation traffic heatmap

### PR DESCRIPTION
**Pull request by scmmishra**
## Description

This PR updates the download format for conversation traffic

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by pranavrajs — CHANGES_REQUESTED** [review]
Please look at the inline comment.

**Review by sojan-official — APPROVED** [review]
- Went through the code and LGTM

**Comment by scmmishra** [comment]
> @scmmishra Tested this locally. It is duplicating the rows for some reason, please take a look.
> 
> Screenshot 2023-03-30 at 11 11 56 AM

One of it is in the UTC timezone, the first one is in the user timezone, let me actually add that to the template more clearly

**Comment by scmmishra** [comment]
@pranavrajs updated this to include the timezone upfront

image

**Comment by scmmishra** [comment]
@pranavrajs take a look at this whenever you can

**Comment by scmmishra** [comment]
@pranavrajs update the PR as per our discussions, PTAL whenever you can

**Comment by pranavrajs** [comment]
@scmmishra There is an issue in the download. Please see the heatmap I see on the dashboard and the download below. It give me an additional date. The dashboard shows March 31 - Apr 6. The download shows March 30 - Apr 6.



Screenshot 2023-04-06 at 8 09 31 PM


Screenshot 2023-04-06 at 8 09 35 PM

**Comment by scmmishra** [comment]
@pranavrajs solved the issue

**Review by pranavrajs — APPROVED** [review]

**Pull request merged**
