### PR TITLE
enh: Create superadmin in seeds

### PR DESCRIPTION
**Pull request by azyzio**
# Pull Request

## Description

While testing anything related to superadmin panel or jobs, the developer had to manually create a superadmin account via console.
The PR modifies the seeds to create the superadmin account

## Type of change

- Developer experience enhancement

## How Has This Been Tested?

Manual testing

### CODE REVIEW

**Comment by sojan-official** [comment]
@azyzio I would lean towards having a rake task for this or seed this based on a condition[environment variable] ensuring that its a development environment.  

Since `rake db:seed` is run by community installs. A person not aware of the super admin feature will leave the default account intact and might be susceptible towards attacks.  

thoughts? 
cc: @pranavrajs  @sony-mathew

**Comment by azyzio** [comment]
@sojan-official ok, assumed seeds were never run on production - but I agree it might be possible with self-hosted distribution systems. What do you think about just running it `unless Rails.env.production?`

**Comment by sojan-official** [comment]
> @sojan-official ok, assumed seeds were never run on production - but I agree it might be possible with self-hosted distribution systems. What do you think about just running it `unless Rails.env.production?`

`unless Rails.env.production?`  sounds good to me

**Comment by pranavrajs** [comment]
unless Rails.env.production? sounds good to me too!

**Comment by azyzio** [comment]
Thanks for the observation!
I added the condition :)

**Review by pranavrajs — APPROVED** [review]

**Pull request merged**
