### PR TITLE
enhancement: Changes button design for tables in settings page

### LINKED ISSUE #3548: Enhancement: Change button design for tables in settings page
image

 - Use Icon buttons to reduce the repetition

### PR DESCRIPTION
**Pull request by iamsivin**
# Pull Request Template

Fixes #3548 

## How Has This Been Tested?

**Screen recording** 

https://user-images.githubusercontent.com/64252451/146313713-bee28424-5c50-4060-b927-a861aeb3df87.mov

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by fayazara — APPROVED** [review]
LGTM

**Comment by nithindavid** [comment]
@iamsivin can we try the smooth variant for buttons?

**Comment by iamsivin** [comment]
@nithindavid When we try with the smooth variant of a button look like this, do we continue with this?


https://user-images.githubusercontent.com/64252451/146106673-dfceb3cc-4ff9-4357-bd00-da2bb23f4fb7.mov

**Comment by nithindavid** [comment]
@iamsivin Try variant="clear". Also for delete use color-scheme="alert". Also look into the each page and make the spacing between buttons consistent. Remove existing css used for this also.

**Review by nithindavid — APPROVED** [review]

**Pull request merged**
