### PR TITLE
fix: Translation to the isAnyoneTyping() method

### PR DESCRIPTION
**Pull request by KokeroO**
# Pull Request Template

## Description

I decided to close PR #10360 and split it into 2 separate PRs.

This fix consists of translating the message when another user is typing on the other side.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

When sending a message from widget_test to an agent, the message that the user on the other end is typing will be translated.
image

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by KokeroO** [comment]
@scmmishra This PR contains the changes you proposed in PR #10360.

**Comment by scmmishra** [comment]
@KokeroO the tests are failing here PTAL

**Comment by KokeroO** [comment]
> @KokeroOos testes estão falhando aqui PTAL

@scmmishra, common.spec.js It's the specifications file, should I update and send changes to it? I'm just starting my contributions to the project, I have doubts about this.

**Comment by pranavrajs** [comment]
@KokeroO Thanks for the PR. I've updated the specs for now. This should be good. Please check the specs locally next time. You can run the frontend tests using `pnpm test` command.

**Comment by KokeroO** [comment]
> @KokeroOObrigado pelo PR. Atualizei as especificações por enquanto. Isso deve ser bom. Por favor, verifique as especificações localmente na próxima vez. Você pode executar os testes de frontend usando `pnpm test`o comando.

@pranavrajs Hello friend.

I will do it. I am not sure if I should send the specs as well.

I will send a new PR soon. Next time I will send it correctly.

**Comment by pranavrajs** [comment]
@KokeroO No worries, this PR is fine. Good to merge.

**Review by pranavrajs — APPROVED** [review]

**Comment by pranavrajs** [comment]
@KokeroO Please see the guidelines [here](https://www.chatwoot.com/hc/handbook/articles/pull-request-guidelines-32).

**Pull request merged**
