### PR TITLE
fix: Handle email with no subject line and no body

### LINKED ISSUE #2050: Email without subject throws "No method encoding for nil" error
Processing an inbound email from gmail without a subject line throws this error:

https://github.com/chatwoot/chatwoot/blob/1d3b1c1ae55333c3df1c45d0989e81026b8eff01/app/presenters/mail_presenter.rb#L72

```2021-04-03T18:32:35.368452501Z app[worker.1]: pid=13 tid=35x1 class=ActionMailbox::RoutingJob jid=6185575ef8407f70b92733e1 elapsed=0.114 INFO: fail
2021-04-03T18:32:35.368591217Z app[worker.1]: pid=13 tid=35x1 WARN: {"context":"Job raised exception","job":{"retry":true,"queue":"action_mailbox_routing","class":"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper","wrapped":"ActionMailbox::RoutingJob","args":[{"job_class":"ActionMailbox::RoutingJob","job_id":"015fb4da-b101-4454-b5ec-f789ac3450df","provider_job_id":null,"queue_name":"action_mailbox_routing","priority":null,"arguments":[{"_aj_globalid":"gid://chatwoot/ActionMailbox::InboundEmail/23"}],"executions":0,"exception_executions":{},"locale":"en","timezone":"UTC","enqueued_at":"2021-04-03T18:30:28Z"}],"jid":"6185575ef8407f70b92733e1","created_at":1617474628.79346,"enqueued_at":1617474755.254043,"error_message":"undefined method `encoding' for nil:NilClass","error_class":"NoMethodError","failed_at":1617474628.9587018,"retry_count":1,"retried_at":1617474678.4497027},"jobstr":"{\"retry\":true,\"queue\":\"action_mailbox_routing\",\"class\":\"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper\",\"wrapped\":\"ActionMailbox::RoutingJob\",\"args\":[{\"job_class\":\"ActionMailbox::RoutingJob\",\"job_id\":\"015fb4da-b101-4454-b5ec-f789ac3450df\",\"provider_job_id\":null,\"queue_name\":\"action_mailbox_routing\",\"priority\":null,\"arguments\":[{\"_aj_globalid\":\"gid://chatwoot/ActionMailbox::InboundEmail/23\"}],\"executions\":0,\"exception_executions\":{},\"locale\":\"en\",\"timezone\":\"UTC\",\"enqueued_at\":\"2021-04-03T18:30:28Z\"}],\"jid\":\"6185575ef8407f70b92733e1\",\"created_at\":1617474628.79346,\"enqueued_at\":1617474755.254043,\"error_message\":\"undefined method `encoding' for nil:NilClass\",\"error_class\":\"NoMethodError\",\"failed_at\":1617474628.9587018,\"retry_count\":1,\"retried_at\":1617474678.4497027}"}
2021-04-03T18:32:35.368644978Z app[worker.1]: pid=13 tid=35x1 WARN: NoMethodError: undefined method `encoding' for nil:NilClass
2021-04-03T18:32:35.368687401Z app[worker.1]: pid=13 tid=35x1 WARN: /app/app/presenters/mail_presenter.rb:72:in `encode_to_unicode'
2021-04-03T18:32:35.368698076Z app[worker.1]: /app/app/presenters/mail_presenter.rb:11:in `subject'
2021-04-03T18:32:35.368702224Z app[worker.1]: /app/app/mailboxes/support_mailbox.rb:50:in `create_conversation'
2021-04-03T18:32:35.368705975Z app[worker.1]: /app/app/mailboxes/support_mailbox.rb:13:in `process'```


To replicate: send an email without a subject to an inbox.

### PR DESCRIPTION
**Pull request by pranavrajs**
Fixes #2050 

- To fix the empty subject line check, I added an empty fallback before encoding
- To fix the empty body and empty subject on the frontend, I added a fallback for the content in the frontend.

### CODE REVIEW

**Comment by pranavrajs** [comment]
To test: 

Case 1: Email with no subject

- Send an email to your email inbox without a subject
- Make sure that the conversation list shows the content of the body as the fallback for subject

Case 2: Email with no subject and no body content

- Send an email to your email inbox without a subject and a body
- Make sure that the conversation list shows "No content available" text as the fallback

**Comment by pranavrajs** [comment]
To test: 

Case 1: Email with no subject

- Send an email to your email inbox without a subject
- Make sure that the conversation list shows the content of the body as the fallback for subject

Case 2: Email with no subject and no body content

- Send an email to your email inbox without a subject and a body
- Make sure that the conversation list shows "No content available" text as the fallback

**Review by sojan-official — APPROVED** [review]

**Comment by pranavrajs** [comment]
@muhsin-k Could you please test the above cases?

**Review by nithindavid — APPROVED** [review]

**Comment by muhsin-k** [comment]
@pranavrajs All cases are working fine

**Pull request merged**
