### PR TITLE
fix: Disable custom fields in pre-chat form on new conversation

### LINKED ISSUE #4177: bug: Start conversation is not working in pre-chat form
**To Reproduce**

Steps to reproduce the behaviour:
1. Enable pre-chat form and CSAT
2. Go to Widget and create conversation
3. Resolve conversation from dashboard
4. Go to widget and click on "Start new conversation"
5. Type message and submit the button

https://user-images.githubusercontent.com/12408980/158233670-1d36a080-168d-44df-b945-3f9012478d8e.mov

### PR DESCRIPTION
**Pull request by muhsin-k**
Fixes #4177

### CODE REVIEW

**Review by iamsivin — DISMISSED** [review]
Code LGTM👍🏻

**Comment by fayazara** [comment]
@muhsin-k While testing, the phone number validation does not let me proceed even if I enter a correct formatted number.

https://user-images.githubusercontent.com/15716057/158321813-1f1dea4e-e3db-4754-bfb5-a09c821982b4.mp4

**Comment by muhsin-k** [comment]
> @muhsin-k While testing, the phone number validation does not let me proceed even if I enter a correct formatted number.
> 
>  Screenshot2022-03-15.at.12.13.27.mp4

Fixed

**Comment by fayazara** [comment]
@muhsin-k The validation works 👍🏻 . 

"Start Conversation" does not work if the contact number already exists in the system. I tried adding my number and got this in response and chat does not start - 
`422 Unprocessable entity - Phone number has already been taken`. We need to handle this I believe.

Screenshot2022-03-15 at 12 49 11

**Comment by muhsin-k** [comment]
> @muhsin-k The validation works 👍🏻 .
> 
> "Start Conversation" does not work if the contact number already exists in the system. I tried adding my number and got this in response and chat does not start - `422 Unprocessable entity - Phone number has already been taken`. We need to handle this I believe.
> 
> Screenshot2022-03-15 at 12 49 11
Done

**Review by fayazara — APPROVED** [review]
Tested locally, works as expected.

**Comment by muhsin-k** [comment]
Closing in favour of https://github.com/chatwoot/chatwoot/pull/4189

**Pull request closed without merging**
