### PR TITLE
feat: added input_select type message support for whatsapp

### PR DESCRIPTION
**Pull request by ChamathKB**
# Pull Request Template

## Description

Added **input_select** message type support for Whatsapp Cloud API and Whatsapp 360dialog.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Tested using Rasa bot with input_select type button payload.

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by ChamathKB** [comment]
Chatwoot **"input_select"** type messages are matched to **"reply button"** type whatsapp messages in this feature. This messages type only allow 3 buttons in payload.

Whatsapp  "list message" type is more sutible for chatwoot "card" messages which allow more payload. This can be added in a future implementation.

Reference for whatsapp API [here](https://developers.facebook.com/docs/whatsapp/guides/interactive-messages/)

**Comment by sojan-official** [comment]
@ChamathKB  Thanks for the changes. Pretty much the same as https://github.com/chatwoot/chatwoot/pull/6819. 
I am inclined to merge the PR, which makes progress quickly.  

One of the cases in which #6819 handles nicely is when there are more buttons than 3. It switches to the list component. can you see if you can incorporate the same logic into this PR as well ?

**Comment by ChamathKB** [comment]
@sojan-official sorry for the delay. Since #6819 already implemented this feature brilliantly I have update the 360dialog provider based on that solution.

**Comment by glauberssoutodossantos** [comment]
Hi @sojan-official how are you?

Is it possible to send whatsapp interactive message by API now? Is yes, how can i do that?

Thanks!

**Pull request merged**
