### PR TITLE
Feat 4651: Shopify Integration

### LINKED ISSUE #4651: feat: Shopify Integration

### PR DESCRIPTION
**Pull request by substr2837**
# Shopify Feature Integration

## Description

After merging, the app will have an integration feature with Shopify.

Fixes #4651

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by drdaga** [comment]
so i guess with same approch wocomerece also can be integrated ??

**Comment by sojan-official** [comment]
@substr2837  After a glance over the PR, Is it necessary for us to sync the Shopify products into tables in Chatwoot? Can't we directly interact with the Shopify APIs on demand to fetch this information / make changes? 

If possible, let's not introduce additional database tables for data models which aren't primarily Chatwoot's responsibility.

**Comment by substr2837** [comment]
Hi @sojan-official. Yes, we can directly interact with ShopifyAPI for fetching product data. I will change the code then. Thanks for the review.

**Comment by substr2837** [comment]
The implementation is done. Please re-review this PR. Thanks

**Comment by drdaga** [comment]
> The implementation is done. Please re-review this PR. Thanks

Anyupdate on this ??
I m trying but giving error

**Comment by sojan-official** [comment]
@substr2837  Apologies on the delay on this one.  Adding some review comments to take this forward if you are still working on this PR; otherwise the team can take a look as bandwidth permits. 

1. Can leverage the existing integration hooks table to store the shopify credentials ?
     Examples:
     https://github.com/chatwoot/chatwoot/pull/6197/
     https://github.com/chatwoot/chatwoot/pull/6454

2.  `integrations_shopify_customer` table  added in the PR seems to be duplicating a lot of information like `email`, `name` etc. Can't we associate that to the existing contacts table itself 
3. Do we multiple methods in `Api::V1::Accounts::Integrations::ShopifyController` ? . We can have a proxy controller which accepts the relevant shopify API endpoint and action,  perform the action with the auth credentials appended to the headers and respond the json returned by shopify. 

----

## Steps forward. 

lets also ship this as multiple PRs to easier testing and merging

-  The backend PR, which adds shopify integration and syncs contacts
     - Ability to store the shopify credentials into integrations table
     - Syncs shopify contacts to Chatwoot CRM
       -  if contact exists : update the missing fields 
       -  if new contact : create a contact in Chatwoot
     
- The frontend PR
    -  shows the order information in sidebar
    -  lets you perform actions over the orders

--- 

Pending Questions 

- Should we use the Oauth flow for authentication or `custom_apps` in shopify ? ( consider the pros and cons for self hosted installations / Chatwoot cloud )

**Comment by substr2837** [comment]
Hi @sojan-official , Yes, I still working on it. Sorry didn't notice it, just opened my GitHub again today. I'll update the implementation following the feedback. Thanks.

**Comment by nithindavid** [comment]
Hey @substr2837, I Hope everything is good. Did you get a chance to check on the feedback? Please let us know if you need any help from our team to get this merged.

**Comment by szluyufeng** [comment]
Any progress?

**Comment by substr2837** [comment]
Hi there! Apologies for the delay. I'll split the PR for the BE and FE, and I'll be putting it on the comment section.

**Comment by pranavrajs** [comment]
@substr2837 I will close this PR for now as it is open for a while. If you are willing to contribute, please raise a fresh PR.

**Comment by sojan-official** [comment]
ref: https://github.com/chatwoot/chatwoot/pull/11101

**Pull request closed without merging**
