### PR TITLE
Enhancement: Add date in agent report file

### PR DESCRIPTION
**Pull request by SanjuSudheerM**
## Description

Add the date in the agent report filename.

## Type of change

New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Navigate to the report section and download the agent report file by clicking the top green button. The downloaded file name should be in the format of agent-report-DD-MM-YYYY.csv

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by nithindavid — APPROVED** [review]
🎉

**Comment by nithindavid** [comment]
@SanjuSudheerM There's a frontend test failing. Can you check that too ?

**Comment by SanjuSudheerM** [comment]
@nithindavid Test cases are running fine for me, could you share some more info?

test-case

**Comment by muhsin-k** [comment]
@SanjuSudheerM 
One of the unit tests is failing.

Screenshot 2021-09-01 at 5 13 28 PM

Please run the command `yarn test`  to run the unit tests

**Comment by SanjuSudheerM** [comment]
@muhsin-k Thank you for the explanation and @nithindavid I have updated the test case to handle the new change.

**Review by pranavrajs — APPROVED** [review]

**Pull request merged**
