### PR TITLE
fix: Contact conversations are showing in the chat list.

### LINKED ISSUE #4014: bug: Contact conversations are showing in the chat list of mentions dashboard
**Describe the bug**

Contact conversations are showing in the chat list of mentions dashboard when we expand the previous conversation section in the sidebar you can see in the below screen recording.

**To Reproduce**

1. Go to mentions dashboard
2. Click on any chat which has a previous conversation
3. Expand the previous conversation header and look into the chat list
4. New you can see that contact conversation is rendering in chat list

**Expected behavior**

No need to show the contact conversation in the chat list in mentions dashboard

**Screenrecording**

https://user-images.githubusercontent.com/64252451/154609044-5f06d618-ee8b-4d83-930f-c18df21327c1.mov

### PR DESCRIPTION
**Pull request by iamsivin**
# Pull Request Template

Fixes #4014 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How Has This Been Tested?

1. Open a chat from mentions or folders view.
2. That chat must have previous conversations.
3. Open the previous conversation from the sidebar.
4. And take look at chat lists.

**Screencast**

https://user-images.githubusercontent.com/64252451/155940335-fa26b249-3f61-4297-a10a-326b3d8f1710.mov

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by pranavrajs** [comment]
@iamsivin I found an issue while testing this. 

If I'm on the conversation URL `/app/accounts/{account_id}/conversations/${conversation_id}` (not inbox/label/view scoped), then the conversation does not change. Please see the loom screencast. https://www.loom.com/share/19e34f3d7daa49399f9df288de7fd52c

**Comment by iamsivin** [comment]
> @iamsivin I found an issue while testing this.
> 
> If I'm on the conversation URL `/app/accounts/{account_id}/conversations/${conversation_id}` (not inbox/label/view scoped), then the conversation does not change. Please see the loom screencast. https://www.loom.com/share/19e34f3d7daa49399f9df288de7fd52c

Looking into it.

**Comment by pranavrajs** [comment]
@iamsivin Made some changes to the PR. Can you please if this works?

**Comment by iamsivin** [comment]
> @iamsivin Made some changes to the PR. Can you please if this works?

Sure

**Comment by iamsivin** [comment]
> @iamsivin Made some changes to the PR. Can you please if this works?

@pranavrajs Tested locally, working as expected.

**Pull request merged**
