### PR TITLE
feat: automation rules recurring event which has a condition to filter last incoming message time

### PR DESCRIPTION
**Pull request by smartdev58**
# Pull Request Template

## Description

Recurring event to check conversations that has last incoming message created at a certain number of hours ago. New event type `Hours From Last Message` and condition `Last Incoming Message Time` `Is x hours before` is defined to be used to filter messages and conversations. This is relevant issue: #4542

Fixes # (issue)
Fixed an issue with namespace conflicts(namespace Account conflicts with model Account: `Account::ConversationsResolutionSchedulerJob` to `Accounts::ConversationsResolutionSchedulerJob` in the file: `conversations_resolution_scheduler_job.rb`

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Tested it from website inbox conversations in agent dashboard
https://www.loom.com/share/d9f0b0f15a35449795fea69fe21b51a8

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by tejaswinichile** [comment]
@smartdev58 We have one PR pending to refactor these frontend pages, we will look into this one, once that is merged.

**Comment by smartdev58** [comment]
> @smartdev58 We have one PR pending to refactor these frontend pages, we will look into this one, once that is merged.

@tejaswinichile Okay, thanks

**Comment by tejaswinichile** [comment]
@smartdev58 Could you try and fix the conflicts?

**Comment by sojan-official** [comment]
Closing this PR since there hasn't been progress for a while. Lets reopen if required

**Pull request closed without merging**
