### PR TITLE
feat: Adds regex to custom attribute definitions

### LINKED ISSUE #6866: There should be option for setting regex for validation of custom attribute
**Is your feature request related to a problem? Please describe.**
If I add custom attributes. There is no valdation. For core attributes there is but we cannot change as per requirements.

**Describe the solution you'd like**
There should be option for setting regex for validation of custom attribute. Or in environment variable.

### PR DESCRIPTION
**Pull request by surabhisuman**
## Description
This allows a user to add/update a custom regex and a cue while defining custom attributes(Only applicable for type- `text`). 
While adding/editing custom attributes, the values are validated against the attribute definition regex, and if it is incorrect, a cue message or default error message is shown and restricts invalid values from being saved.

Fixes #6866 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?
https://www.loom.com/share/158f8a4f83d64380a47724406848f0b7?sid=821fca99-9f95-477a-aab2-13bb163a6a24

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by surabhisuman** [comment]
@sojan-official can you please review this?

**Comment by surabhisuman** [comment]
Hello @pranavrajs , please let me know if there are any concerns on this PR.

**Comment by sojan-official** [comment]
Thank you so much for your contribution. We truly appreciate your efforts. 🙏 

Our team will prioritize reviewing and testing your changes according to our existing schedule and workload. 
Should there be a need for any further actions or information from your side, we'll follow up here. 📨

Once again, we're grateful for your involvement and contribution to our community. 🚀🌟 🙌 


----

@muhsin-k  could you take this forward ?

**Comment by sojan-official** [comment]
@surabhisuman  Based on a quick look, you might also want to do the validation on Chat widget side in the case where the pre-chat form is enabled.

**Comment by surabhisuman** [comment]
Hey @sojan-official @muhsin-k I have added validation on the Chat widget side as well. Can you please review this?

**Comment by muhsin-k** [comment]
@surabhisuman Thanks for the PR. One quick feedback is to make the regex option optional since it is not mandatory. Let's add a checkbox for "Enable regex validation" and only show the regex-related fields when the user checks the box. Please let me know after you make this change. We will test again and merge the PR.

**Comment by surabhisuman** [comment]
@muhsin-k thanks for the review. I have added the checkbox. Please review it.

**Review by muhsin-k — APPROVED** [review]
Tested locally and working great.  @sojan-official Can you review the back end part?

**Comment by surabhisuman** [comment]
Hi @sojan-official, please let me know if there are any concerns on this PR.

**Comment by sojan-official** [comment]
@surabhisuman, my apologies for the delay on this one. The changes look good. We will have this merged.

**Pull request merged**
