### PR TITLE
feat: Read/Delivery status for Whatsapp Cloud API

### PR DESCRIPTION
**Pull request by clairton**
ref: #1021

# Read/Delivery whatsapp cloud api status

## Description

Process field statuses receives in webhook whatsapp cloud api

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Creating a spec

### CODE REVIEW

**Comment by sojan-official** [comment]
@clairton  Thanks a lot for the changes. We will test this out and get back to you.

**Comment by clairton** [comment]
@sojan-official https://github.com/chatwoot/chatwoot/pull/5142 this PR, change some things would be tested together at the same time

**Comment by drdaga** [comment]
> ref: #1021
> 
> # Read/Delivery whatsapp cloud api status
> ## Description
> Process field statuses receives in webhook whatsapp cloud api
> 
> ## Type of change
> Please delete options that are not relevant.
> 
> * [ ]  New feature (non-breaking change which adds functionality)
> 
> ## How Has This Been Tested?
> Creating a spec

jst a quick question is it possible to send read message notification to messages read in chatwoot ??

**Comment by clairton** [comment]
> > ref: #1021
> > # Read/Delivery whatsapp cloud api status
> > ## Description
> > Process field statuses receives in webhook whatsapp cloud api
> > ## Type of change
> > Please delete options that are not relevant.
> > 
> > * [ ]   New feature (non-breaking change which adds functionality)
> > 
> > ## How Has This Been Tested?
> > Creating a spec
> 
> jst a quick question is it possible to send read message notification to messages read in chatwoot ??

Yes with this https://developers.facebook.com/docs/whatsapp/cloud-api/webhooks/payload-examples#message-status-updates

**Comment by drdaga** [comment]
> > > ref: #1021
> > > # Read/Delivery whatsapp cloud api status
> > > ## Description
> > > Process field statuses receives in webhook whatsapp cloud api
> > > ## Type of change
> > > Please delete options that are not relevant.
> > > 
> > > * [ ]    New feature (non-breaking change which adds functionality)
> > > 
> > > ## How Has This Been Tested?
> > > Creating a spec
> > 
> > 
> > jst a quick question is it possible to send read message notification to messages read in chatwoot ??
> 
> Yes with this https://developers.facebook.com/docs/whatsapp/cloud-api/webhooks/payload-examples#message-status-updates

actually i was talking about this 

https://developers.facebook.com/docs/whatsapp/cloud-api/guides/mark-message-as-read


you can consider adding this also like if message is is read in chat woot it can be masked as read

**Comment by clairton** [comment]
Hi @drdaga, awesome! This is chatwoot to whatsapp, now implemented from whatsapp to chatwoot only.

**Comment by clairton** [comment]
Any channel already implement this @drdaga?

**Comment by clairton** [comment]
Hi guys, is everything ok with this PR?

**Comment by sojan-official** [comment]
@clairton We didn't get the chance to test this yet as we were busy with the 2.8 release. We will get to this over this week.

**Comment by clairton** [comment]
Now, this work too (https://developers.facebook.com/docs/whatsapp/cloud-api/guides/mark-message-as-read)

**Comment by sojan-official** [comment]
@clairton  Thanks for the further updates. Apologies for the delay in the review. The team got caught up with some other high-priority items. But rest assured, this remains a priority on our to-do list.

**Comment by drdaga** [comment]
> Now, this work too (https://developers.facebook.com/docs/whatsapp/cloud-api/guides/mark-message-as-read)

i tried to check but i think this not working can u check again ??

**Comment by clairton** [comment]
> > Now, this work too (https://developers.facebook.com/docs/whatsapp/cloud-api/guides/mark-message-as-read)
> 
> i tried to check but i think this not working can u check again ??

Can you test again?

**Comment by sojan-official** [comment]
@clairton, apologies for the delay on this. At the moment, we are testing these changes.  We might have to wait for the behaviour of marking incoming messages read at the Whatsapp end. This behaviour is something which we haven't speced out well. It might not be the behaviour that some  Chatwoot users want.

Example: 
- An agent who opened up the conversation by mistake would be compelled to make an immediate reply since the end customer now sees the read status, and not getting a reply would make them feel ignored.  

So the team might be stripping some code over this PR before merging, only retaining the read and error status processing for outgoing messages. After further evaluation, let's get to the latter behaviour as a separate issue and PR.

**Comment by clairton** [comment]
> @clairton, apologies for the delay on this. At the moment, we are testing these changes. We might have to wait for the behaviour of marking incoming messages read at the Whatsapp end. This behaviour is something which we haven't speced out well. It might not be the behaviour that some Chatwoot users want.
> 
> Example:
> 
> * An agent who opened up the conversation by mistake would be compelled to make an immediate reply since the end customer now sees the read status, and not getting a reply would make them feel ignored.
> 
> So the team might be stripping some code over this PR before merging, only retaining the read and error status processing for outgoing messages. After further evaluation, let's get to the latter behaviour as a separate issue and PR.

**Comment by clairton** [comment]
I agree, done!

**Comment by sojan-official** [comment]
QA 


https://user-images.githubusercontent.com/73185/204522418-a514a719-7990-465b-8d63-4936f97a0de5.mov

**Review by nithindavid — APPROVED** [review]

**Comment by sojan-official** [comment]
## Design change to the indicators 
Screenshot 2022-11-29 at 3 33 28 PM

**Comment by sojan-official** [comment]
@clairton We have completed the QA and have merged this. It will be included in our upcoming release. 
Thanks again for working on this. !!!

**Pull request merged**
