### PR TITLE
Run chatwoot prepare and migrate as a part of docker image deploying …

### PR DESCRIPTION
**Pull request by srameshr**
# Pull Request Template

## Description

The Dockerfiles and especially the rails command to run the migration for a new and upgraded instance is not part of the official docker web or worker image file and this commit adds the file as well as the command to run that so docker deployment is simpler.

Fixes # (issue)
https://github.com/chatwoot/chatwoot/issues/1882

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by srameshr** [comment]
@nithindavid @sojan-official

**Comment by nithindavid** [comment]
Can you fix the title and follow the pr guidelines? Also create an issue and attach to this pr

**Comment by srameshr** [comment]
@nithindavid Done

**Comment by srameshr** [comment]
@nithindavid Is the PR according to the template?

**Comment by srameshr** [comment]
@nithindavid @sojan-official Could you help me with this? I don't want to run migration commands manually every time a new version comes out.

**Comment by sojan-official** [comment]
@srameshr  Thanks for the PR.  But I am not a big fan of coupling database migrations on server startup. It comes with a lot of caveats as data migrations can be long-running and error-prone. ( read: https://pythonspeed.com/articles/schema-migrations-server-startup/  )

So in the ideal case, All the migrations that you add should be compatible with the N ( the new code you are about to ship) and (N-1) the previous version you run in production. 
You can spin up a single container with the newer code for production deployments and run the migrations from it. Ensure your database is stable before spinning up more containers with the latest version of the code and diverting the traffic.

So I wouldn't advise having the step in the container startup process. For production running migrations manually is a pain we must live with. For local development, you can set up a shell command that automatically runs the migrations before starting the server.  

---

To build the chatwoot web and worker images, We already have the `docker-compose.production.yaml`. You could run 

```
docker-compose -f docker-compose.production.yaml build
``` 

---

Ps: It helps the maintainers if you raise the proposal before raising the PR.  This lets the team communicate ideas and set expectations on when we can merge the changes. It also saves effort in cases where the idea does not fit our immediate roadmap. 
( ref: https://www.chatwoot.com/docs/contributing-guide )

**Comment by srameshr** [comment]
@sojan-official Let me think about this. Because migrations are the only way to get new features to every customer at the cost of some downtime.
Also for chatwoot that's running on K8 with no access to console or docker-compose how do you think migrations should be handled?

**Comment by sojan-official** [comment]
@srameshr You could leverage jobs

ref:
https://andrewlock.net/deploying-asp-net-core-applications-to-kubernetes-part-7-running-database-migrations/
https://thoughtbot.com/blog/zero-downtime-rails-deployments-with-kubernetes

**Pull request closed without merging**
