### PR TITLE
feat: Auto save IMAP/SMTP config

### PR DESCRIPTION
**Pull request by tejaswinichile**
Fixes: https://linear.app/chatwoot/issue/CW-2128/update-smtp-and-imap-for-standard-providers

https://www.loom.com/share/5724f8ff9d674c5ab8814fac50f86992

Screenshot 2023-07-21 at 5 00 50 PM

### CODE REVIEW

**Review by sojan-official — APPROVED** [review]
Code LGTM

**Review by vishnu-narayanan — APPROVED** [review]
LGTM. IMAP/SMTP is getting pre-filled with values when selecting standard providers.


Sidenote on Yahoo mail
----
- Tried to get this working with Yahoo email
- Getting invalid credentials on imap
- Yahoo has disabled email access for third-party apps
- The official suggestion is to use app passwords (https://help.yahoo.com/kb/generate-third-party-passwords-sln15241.html)
- Funny thing is, yahoo has turned off app password generation 🤦 


image

**Comment by vishnu-narayanan** [comment]
cc: @tejaswinichile @sojan-official

**Comment by iamsivin** [comment]
Updated images the alignment issues
image

**Comment by pranavrajs** [comment]
Closing this here as the inbox revamp design update is already in progress.

**Pull request closed without merging**
