### PR TITLE
feat: message signature on whatsapp

### PR DESCRIPTION
**Pull request by clairton**
# Pull Request Template

## Description

fixes: https://github.com/chatwoot/chatwoot/issues/5855

Prefix agent on whatsapp message

## Type of change

Please delete options that are not relevant.

- [X] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Send message with whatsapp cloud api

Captura de Tela 2023-03-27 às 17 05 13
Captura de Tela 2023-03-27 às 17 05 00

### CODE REVIEW

**Comment by scmmishra** [comment]
@clairton while I understand the use case, I don't think this feature is helpful for the broad user base. The change is too opinionated to be the default (and the only) behaviour of WhatsApp messaging; it could be considered if this was available as a setting that users could enable, but even with that, it's hard for me to understand the value of this change

**Comment by sojan-official** [comment]
ref: https://github.com/chatwoot/chatwoot/issues/5855

**Comment by scmmishra** [comment]
@clairton, seeing this thread, It seems like there is enough conversation in the community for this; I would suggest changing the approach. Let this be an inbox configuration for WhatsApp, "Send message signature", and if enabled, we can format the message to include the message signature or the agent's name, whichever is available at the end of the message.

This will make this an entirely opt-in feature. @sojan-official @pranavrajs need your thoughts on this

CC: @tejaswinichile @nithindavid

**Comment by pranavrajs** [comment]
Folks, I suggest extending the personal signature option rather than adding a new field in the inbox or anything. Right now, it is enabled only the email channels. 

Screenshot 2023-03-29 at 12 55 07 PM

If we enable it on WhatsApp, that will make the feature consistent across the channels. As a further step, we can try enabling it on Facebook, Twitter and Instagram.

**Comment by clairton** [comment]
I think create a toggle in whatsapp inbox “identify agent in message” disabled by default, when it enable prefix message with agent name like so “agent name: the message content”. E-mail signature use more information witch WhatsApp message. But if your prefer use the same email signature ok, I do with signature email 😀

@sojan-official @pranavrajs @scmmishra

**Comment by vagner-dias** [comment]
up

**Comment by pranavrajs** [comment]
@clairton @glauberssoutodossantos I understand the struggle, but having more options to do the same thing is not ideal. Let's stick with the signature for now and see if there are any issues caused by it. If so, we can take it up in the following PRs. 

@clairton If you can update the PR with the suggested change soon, we can get that in Monday's release.

**Comment by clairton** [comment]
> @clairton @glauberssoutodossantos I understand the struggle, but having more options to do the same thing is not ideal. Let's stick with the signature for now and see if there are any issues caused by it. If so, we can take it up in the following PRs.
> 
> @clairton If you can update the PR with the suggested change soon, we can get that in Monday's release.

@pranavrajs done! =)

**Comment by clairton** [comment]
Settings:
Captura de Tela 2023-04-14 às 14 10 51


Signature:
Captura de Tela 2023-04-14 às 14 11 23

Message With Signature:
Captura de Tela 2023-04-14 às 14 11 41

**Comment by vagner-dias** [comment]
@clairton, Question: If we configure the signature to be in bold, will the code set it in bold too?

**Comment by clairton** [comment]
> @clairton, Question: If we configure the signature to be in bold, will the code set it in bold too?
🙄, it put *

Settings:
Captura de Tela 2023-04-14 às 16 22 50

In whatsapp message:
Captura de Tela 2023-04-14 às 16 23 08

**Comment by clairton** [comment]
> @clairton, Question: If we configure the signature to be in bold, will the code set it in bold too?

Would be transform html to markdown...

**Comment by clairton** [comment]
It works like this, I don't know how it could improve.

Settings:
Captura de Tela 2023-04-14 às 16 22 50

Postgres:
Captura de Tela 2023-04-14 às 17 29 56

Whatsapp

Captura de Tela 2023-04-14 às 16 23 08

**Comment by vagner-dias** [comment]
IMHO the double asterisk ended up having a nice effect.

See: so far we do not have this feature and this is already a important improvement. It can be also be improved overtime.

**Comment by vagner-dias** [comment]
> @clairton @glauberssoutodossantos I understand the struggle, but having more options to do the same thing is not ideal. Let's stick with the signature for now and see if there are any issues caused by it. If so, we can take it up in the following PRs.
> 
> @clairton If you can update the PR with the suggested change soon, we can get that in Monday's release.

Hello @pranavrajs , is the PR good to include on today's release?

Thank you!

**Comment by pranavrajs** [comment]
@vagner-dias There are a couple of outstanding questions on this one.

@clairton I didn't get the changes completely. Sorry if it is a repeated question. I am trying to understand why we need the `Send message signature` flag. 

If you see the editor in the email channel (shown below), the user can disable the signature. If the user doesn't need to add the signature, they can avoid it. 

Screenshot 2023-04-19 at 6 53 51 PM

An inbox-level setting is not really required here.

**Comment by pranavrajs** [comment]
@clairton I would suggest turning on the message signature option for the WhatsApp channel first and seeing if it solves the problem.

https://github.com/chatwoot/chatwoot/blob/527042afd1ca917f37e4cdcdbeef4cf7d6e5055c/app/javascript/dashboard/components/widgets/WootWriter/ReplyBottomPanel.vue#L279-L281

**Comment by vagner-dias** [comment]
HI @clairton,

Maybe this is "simpler" to implement than the initial approach? I mean, less code, etc?

**Comment by WallacyBR** [comment]
This feature was released?

**Comment by vagner-dias** [comment]
Hello @sojan-official, @clairton @pranavrajs 

Do you guys plan to release this feature or even something similar?

Is there anything I can help with?

Regards.

**Comment by clairton** [comment]
Hello, email subscription is an option, but my company's whatsapp subscription is required. That's why I ended up focusing on other subjects and putting this in a fork 😅

**Comment by WallacyBR** [comment]
Someone can review this?

**Comment by sojan-official** [comment]
Closing this since we have messages signature enabled for WhatsApp accounts in our latest version.

**Pull request closed without merging**
