### PR TITLE
feat: update color palette [CW-2293]

### PR DESCRIPTION
**Pull request by scmmishra**

### CODE REVIEW

**Review by iamsivin — APPROVED** [review]

**Comment by nithindavid** [comment]
@iamsivin Could you add `color-scheme: dark;` to `:root` to make the scrollbars switch to dark theme? https://stackoverflow.com/questions/65940522/how-do-i-switch-to-chromes-dark-scrollbar-like-github-does

**Comment by nithindavid** [comment]
@iamsivin We need to fix articles landing page, the container class used has a max width.

image

**Comment by iamsivin** [comment]
> @iamsivin Could you add `color-scheme: dark;` to `:root` to make the scrollbars switch to dark theme? https://stackoverflow.com/questions/65940522/how-do-i-switch-to-chromes-dark-scrollbar-like-github-does

Done

**Comment by iamsivin** [comment]
> @iamsivin We need to fix articles landing page, the container class used has a max width.
> 
Done

**Pull request merged**
