### PR TITLE
XMPP channel

### PR DESCRIPTION
**Pull request by singpolyma**
## Description

This adds an XMPP channel so that support can be done over an existing Jabber ID somewhere.  It supports sending rich message, sending and receiving attachments, delivery and read receipts, and synchronization with the server even if other clients or bots are also using the same account outside outside of chatwoot.
    
For real-time delivery, this implementation does not poll but instead runs a long-running worker that stays connected to every configured XMPP channel.

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## How Has This Been Tested?

I have connected it to my local XMPP server and sent many messages of every type to test the functionality in both directions.  I also play to deploy it in production for our support team soon.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by sojan-official** [comment]
Hey @singpolyma, thanks a lot for the changes. We will get to reviewing this once the team have some bandwidth. 
Hopefully, more community members could try it out and provide feedback.

**Comment by Amolith** [comment]
@singpolyma until this is merged with upstream, how would one go about setting up your fork?

**Comment by singpolyma** [comment]
@Amolith We are offering people to try it on our instance, but if you want to run it yourself, just set up Chatwoot normally per their instructions, except use git clone from my branch instead.  Then however you set up sidekiq to run you need to make sure you also need to run `bin/xmpp` using the same environment.  I believe I added it to the Procfile here if you use that, but if you use something else you just need to be sure it is running.

**Comment by Amolith** [comment]
@singpolyma am I missing something or do they not have any "manual" installation instructions? 

I tried editing the installation script mentioned in [the docs](https://www.chatwoot.com/docs/self-hosted/deployment/linux-vm) to pull from your fork/branch, but it keeps failing with some obtuse Tailwind compilation errors. I was going to just try setting each component up manually but I don't see any docs for that anywhere on their site.

**Comment by singpolyma** [comment]
@github-actions hi

**Comment by clairton** [comment]
+1

**Comment by aboveagency** [comment]
+1 for finalizing this PR. This would enable chatwoot users to have an inbound XMPP support channel, as well as a phone number that runs ontop of JMP.chat and XMPP - very useful for those who don't want to go through Twilio. This PR has been around for a year now - would be great to see it reviewed and the tests fixed.

**Comment by sojan-official** [comment]
Hi @singpolyma,

Firstly, we'd like to sincerely thank you for your contribution and the effort you've put into this PR. We've been closely reviewing our product requests and priorities, and we noticed that an XMPP channel integration has emerged as a more niche requirement than initially anticipated. Consequently, our team has been focusing on other areas with broader demand.

Given these factors and considering that the PR has been inactive for some time, we've decided to close it for now. However, we want to emphasize that this isn't a reflection of the quality of your work or the value of your idea. We are very much open to revisiting this in the future should there be a stronger demand from the community.

In the meantime, if this feature is still crucial for you or others, we recommend maintaining a separate fork or exploring the use of our API channel.

Thanks again for your understanding and your contributions to the Chatwoot community. Your efforts are greatly appreciated!

👍

**Comment by singpolyma** [comment]
Thanks for letting me know. We will of course continue to operate our fork as we have been doing for over a year now. While I'd love to see this merged upstream, I understand that every contribution ultimately carries some small weight of maintenance and so just know that if you ever want this feature if main it'll still be here waiting for you :)

**Pull request closed without merging**
