### PR TITLE
fix: Avoid duplicate invitation emails when adding an agent

### PR DESCRIPTION
**Pull request by shivamkb17**
# Pull Request Template

## Description

Agent is getting double invitation mail, After changing these code, This issue is fixed. 
## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by sojan-official** [comment]
@scmmishra  Could you take a look at this ?

**Review by scmmishra — COMMENTED** [review]
This is a bad check, the `1.hour` mark is arbitrary, the user shouldn't have to wait for an hour to receive another confirmation email.

This definitely does not fix the issue at it's core, we need to figure out if the `send_confirmation_if_required` is triggered twice? And if it is, we have to find out why and solve that

**Comment by scmmishra** [comment]
> This is a bad check, the `1.hour` mark is arbitrary, the user shouldn't have to wait for an hour to receive another confirmation email.
> 
> This definitely does not fix the issue at it's core, we need to figure out if the `send_confirmation_if_required` is triggered twice? And if it is, we have to find out why and solve that

@shivamkb17 @sojan-official seems like we don't need to manually trigger the confirmation email, see the following

https://github.com/heartcombo/devise/blob/bb18f4d3805be0bf5f45e21be39625c7cfd9c1d6/lib/devise/models/confirmable.rb#L52

We use the `confirmable` module with devise, that ensures that the confirmation email is sent, in that case we can remove that code block from the `AgentBuilder`

**Comment by sojan-official** [comment]
> > This is a bad check, the `1.hour` mark is arbitrary, the user shouldn't have to wait for an hour to receive another confirmation email.
> > This definitely does not fix the issue at it's core, we need to figure out if the `send_confirmation_if_required` is triggered twice? And if it is, we have to find out why and solve that
> 
> @shivamkb17 @sojan-official seems like we don't need to manually trigger the confirmation email, see the following
> 
> https://github.com/heartcombo/devise/blob/bb18f4d3805be0bf5f45e21be39625c7cfd9c1d6/lib/devise/models/confirmable.rb#L52
> 
> We use the `confirmable` module with devise, that ensures that the confirmation email is sent, in that case we can remove that code block from the `AgentBuilder`

make sense to me.  Lets remove the extra code in AgentBuilder

**Review by scmmishra — APPROVED** [review]

**Comment by pranavrajs** [comment]
Tested the flows below:

1/ New Signup
2/ Add agent via dashboard

Both are working fine.

**Pull request merged**
