### PR TITLE
Fix: handling UTF encoded mail

### LINKED ISSUE #4381: unknown characters(????) in email channel
please see this below image i think there's issue in email body  characters for Arabic language

image

### PR DESCRIPTION
**Pull request by tejaswinichile**
# Pull Request Template

## Description

> The Action mailbox presenter was deciding mail.body without considering the mail content type.

> If mail encoding in base64 and non-UTF-8 charset, `mail.body.decoded` decodes the entire mail without knowing the mail body encoding type, and then when we encode it to UTF-8 it encodes it to invalid characters.

> mail.decoded actually works on mail decoding by checking the mail content type, so it decoded the mail body properly from the US-ASCII and then encode it to UTF-8

Fixes #4381 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Test Cases

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by tejaswinichile** [comment]
Fix on staging https://staging.chatwoot.com/app/accounts/3/conversations/2433
Untitled 3

**Review by sojan-official — APPROVED** [review]
the code looks good to me

**Comment by klipitkas** [comment]
Thanks for the fix, do you have a date planned for a release that contains this? Thanks again.

**Comment by vishnu-narayanan** [comment]
We usually release on the 15th of every month. Due to back to back holidays, this release(2.4.0) is pushed to April 18th Monday.

ref: https://discord.com/channels/647412545203994635/865616796290514976/964082404866285588

**Pull request merged**
