### PR TITLE
fix: Duplicate messages in Whatsapp Channel

### PR DESCRIPTION
**Pull request by sojan-official**
fixes: #5433

### CODE REVIEW

**Comment by harismateen** [comment]
@sojan-official is this issue has already resolved?

**Comment by sojan-official** [comment]
@harismateen  the fix is currently on the develop branch and be available in the upcoming release. It is active on Chatwoot cloud.

**Comment by harismateen** [comment]
@sojan-official great. Can i ask when is the next release date?

**Comment by guuwdias** [comment]
I have this problem

**Comment by harismateen** [comment]
> @harismateen  the fix is currently on the develop branch and be available in the upcoming release. It is active on Chatwoot cloud. 

@sojan-official hi Sojan, can i check if this has fixed in last released?

**Pull request merged**
