### PR TITLE
Chore: Cleanup attachment handling for Facebook & Whatsapp

### LINKED ISSUE #1047: Attachment capability in Facebook Messenger integration
**Is your feature request related to a problem? Please describe.**

I've asked this question to the wonderful founders of Chatwoot and I already have an answer. I'm just logging it in as a formal request in the hopes that it may be added in the future. 

It would be nice if the Facebook Messenger integration has the ability to attach a file in the reply conversation, much like in the website channel. Right now Chatwoot is an amazing software for us. It does everything we hoped for except for that one attachment capability within facebook. In our current setup, if a customer (in Facebook channel) requests for a photo about our products, we go back to the native facebook messenger app so we can send them the photo. 

**Describe the solution you'd like**

I would like for us to be able to send a photo or file attachment within the Facebook channel conversation. 

**Describe alternatives you've considered**

**Additional context**

That's about it! very grateful for every one's contribution to this project. You guys are awesome!

### PR DESCRIPTION
**Pull request by sojan-official**
# Pull Request Template

## Description

Chore: Fix fb file uploads

Fixes  #1047

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by WevrLabs** [comment]
Nice!
I think Twitter's API supports attachments as well, so it will be nice to have the functionality extends there too:
[https://developer.twitter.com/en/docs/direct-messages/message-attachments/guides/attaching-media](https://developer.twitter.com/en/docs/direct-messages/message-attachments/guides/attaching-media)

**Comment by pranavrajs** [comment]
@WevrLabs That will covered in #819

**Comment by dixytudla** [comment]
@pranavrajs @sojan-official Thanks for this sirs! can't wait to be able to use it. This will be available on v1.7?

**Comment by sojan-official** [comment]
@dixytudla  yep. If you are feeling adventurous you can update the installation to the latest development and start using the functionality right away. 

In the caprover update steps for web and worker. 
use: `FROM chatwoot@sha256:7236581b69b241b5c1e4b4e77a60b03504d16696a020c37c1cbec036b734c333` instead of  `FROM chatwoot/chatwoot:latest`

you can obtain latest images from. https://hub.docker.com/r/chatwoot/chatwoot/tags  but do watch out that develop images might be relatively less stable.

**Comment by dixytudla** [comment]
Yes! I shall try that and let you know right away!

**Comment by dixytudla** [comment]
@sojan-official Hi Sojan, I attempted to update but currently getting this error:

Error: {"message":"pull access denied for chatwoot, repository does not exist or may require 'docker login'"}
pull access denied for chatwoot, repository does not exist or may require 'docker login'

**Comment by dixytudla** [comment]
@sojan-official I was able to update the latest develop image. The app works flawlessly! Could not ask for anything more. This thing is amazing!

**Pull request merged**
