### PR TITLE
swagger: fixed invalid specification

### PR DESCRIPTION
**Pull request by giautm**
# Fixed Swagger Specification

## Description

Currently, the swagger spec doesn't follow the Swagger 2.0 specification. So, I facing 4 errors when trying generate the Golang client for chatwoot.

```
go run -mod=mod github.com/go-swagger/go-swagger/cmd/swagger generate client -f https://raw.githubusercontent.com/chatwoot/chatwoot/develop/swagger/swagger.json
2022/09/22 23:45:40 validating spec https://raw.githubusercontent.com/chatwoot/chatwoot/develop/swagger/swagger.json
The swagger spec at "https://raw.githubusercontent.com/chatwoot/chatwoot/develop/swagger/swagger.json" is invalid against swagger specification 2.0. see errors :
- "definitions.contact_update.properties.avatar.type" must validate at least one schema (anyOf)
- definitions.contact_update.properties.avatar.type in body must be of type array: "string"
- "definitions.contact_create.properties.avatar.type" must validate at least one schema (anyOf)
- definitions.contact_create.properties.avatar.type in body must be of type array: "string"

exit status 1
```

Due to the spec, the binary field should use `format: binary` beside `type: string`. Source: [Data Types](https://swagger.io/specification/v2)

The two next errors related to duplicate fields: 
- In `conversation_show`, the `id` field was already defined in `conversation`, so we don't need to include  `$ref: '#/definitions/generic_id'`
- In `extended_message`, the `sender` field was already defined in `message`. So, we should remove it from `with_source_sender`. This resource is only used in one place, so it will not break anything else.

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Update the swagger.json and generate the client code.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by giautm** [comment]
@sojan-official can you review the PR, please?

**Comment by sojan-official** [comment]
@giautm  Thanks a lot for the changes. We will have this reviewed and merged. 

Do you think we should update the validator in our circle pipeline?
https://github.com/chatwoot/chatwoot/blob/8e5d8fcdaf944dc05007e4bc6725c995d22d07ee/.circleci/config.yml#L83

**Comment by giautm** [comment]
> @giautm  Thanks a lot for the changes. We will have this reviewed and merged. 
> 
> 
> 
> Do you think we should update the validator in our circle pipeline?
> 
> https://github.com/chatwoot/chatwoot/blob/8e5d8fcdaf944dc05007e4bc6725c995d22d07ee/.circleci/config.yml#L83

Sure, I think the validator need upgrade or change to another tools that more stricky

**Comment by giautm** [comment]
Latest version of openapi-generator-cli still report the `string <binary>` as a warning, not error.

```sh
java -jar ./openapi-generator-cli-6.2.0.jar validate -i swagger/swagger.json --recommend
Validating spec (swagger/swagger.json)
[main] WARN  io.swagger.util.PropertyDeserializer - no property from string <binary>, null, {ENUM=null, TITLE=null, DESCRIPTION=Send the form data with the avatar image binary or use the avatar_url, DEFAULT=null, PATTERN=null, DESCRIMINATOR=null, MIN_ITEMS=null, MAX_ITEMS=null, MIN_PROPERTIES=null, MAX_PROPERTIES=null, MIN_LENGTH=null, MAX_LENGTH=null, MINIMUM=null, MAXIMUM=null, EXCLUSIVE_MINIMUM=null, EXCLUSIVE_MAXIMUM=null, UNIQUE_ITEMS=null, EXAMPLE=null, TYPE=string <binary>, FORMAT=null, READ_ONLY=null, VENDOR_EXTENSIONS={}, MULTIPLE_OF=null}
[main] WARN  io.swagger.util.PropertyDeserializer - no property from string <binary>, null, {ENUM=null, TITLE=null, DESCRIPTION=Send the form data with the avatar image binary or use the avatar_url, DEFAULT=null, PATTERN=null, DESCRIMINATOR=null, MIN_ITEMS=null, MAX_ITEMS=null, MIN_PROPERTIES=null, MAX_PROPERTIES=null, MIN_LENGTH=null, MAX_LENGTH=null, MINIMUM=null, MAXIMUM=null, EXCLUSIVE_MINIMUM=null, EXCLUSIVE_MAXIMUM=null, UNIQUE_ITEMS=null, EXAMPLE=null, TYPE=string <binary>, FORMAT=null, READ_ONLY=null, VENDOR_EXTENSIONS={}, MULTIPLE_OF=null}
[main] INFO  o.o.codegen.utils.ModelUtils - [deprecated] inheritance without use of 'discriminator.propertyName' has been deprecated in the 5.x release. Composed schema name: null. Title: null
Warnings: 
        - Apache and Nginx webservers may fail due to legacy CGI constraints enabled by default in
          which header keys with underscore are disallowed. See
          https://stackoverflow.com/a/22856867/151445.
        - Unused model: extended_message

[info] Spec has 2 recommendation(s).
```

**Comment by sojan-official** [comment]
@giautm We apologise for the delay on this one. Based on further thoughts, we decided to stick with the existing validator since the schema is still valid according to the official guidelines.  But in the future, we will review for any warnings before merging changes to the schema. 

thanks again for the changes

**Pull request merged**
