### PR TITLE
fix: update heroku app.json to use premium plans

### LINKED ISSUE #5284: Chatwook 1-Click Heroku fails deployment
The Chatwoot 1-Click Heroku install fails at the deployment stage. Could you advise?

### PR DESCRIPTION
**Pull request by vishnu-narayanan**
# Pull Request Template

## Description

Use premium/paid dynos and addons as Heroku is deprecated free dynos/addons.

Web and worker dynos will switch from free hobby dynos to `basic` dynos, which will be `7$/month`. Postgres and Redis will switch from `hobby-dev` to `mini` plans, which will be `0.01$/month`.

Fixes #5284 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Deployed on Heroku using this branch

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by vishnu-narayanan** [comment]
deployment failed with premium plans as well
image

**Comment by vishnu-narayanan** [comment]
deployment still failing after setting default stack to `heroku-20`

image

**Comment by vishnu-narayanan** [comment]
@sojan-official We could choose to have this change merged now or wait till Heroku deprecates the free plans.  Deployment is successful with this free dynos  via https://github.com/chatwoot/chatwoot/pull/5338

cc: @pranavrajs

**Review by sojan-official — APPROVED** [review]

**Comment by vishnu-narayanan** [comment]
>When should I update my app.json file to use the new dyno and data plans?
Eco Dynos
If you want to switch from using free to Eco dynos, it's recommended to update your app.json file prior to November 28th, 2022. Ensure that you are subscribed to Eco prior to updating your files. To help ease the migration to Eco, billing for Eco dynos doesn't start until December 1st, 2022.
Basic Dynos
Basic dynos aren't yet available. If you use Hobby dynos in your app.json files, don't update them to Basic until after November 28th, 2022. Even if you don't update your file after this date, any app.json files that use hobby dynos will provision basic dynos instead for the foreseeable future. As this plan is just a name change, billing commences immediately.
Mini Data Plans
If you want to switch from using hobby-dev to mini data plans, it's recommended to update your app.json file prior to November 28th, 2022. To help ease the migration from hobby-dev to the new plan, billing for Mini plans doesn't start until December 1st, 2022.
Basic Postgres Plans
If you want to switch from using hobby-basic to basic Heroku Postgres plans, it's recommended to update your app.json file prior to November 28th, 2022. As this plan is just a name change, billing commences immediately.
See our [blog post](https://blog.heroku.com/new-low-cost-plans) and the [Low-Cost Plans FAQ](https://help.heroku.com/KP5RQQVO/low-cost-plans-faq) for more info related to our new plans.

https://help.heroku.com/8Q7RIYBC/when-should-i-update-my-app-json-file-to-use-the-new-dyno-and-data-plans

**Comment by vishnu-narayanan** [comment]
image

**Pull request merged**
