### PR TITLE
Feat: add agents in macros

### LINKED ISSUE #5736: Macros - Assign agents
- Add the “Assign Agent” option (Support both assign/unassign)

### PR DESCRIPTION
**Pull request by tejaswinichile**
# Pull Request Template

## Description

Fixes #5736 

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Tested on local.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by fayazara — APPROVED** [review]
Looks Good.

Tested locally
1. Macro with only one action - Assign agent
2. Macros with multiple actions including an agent assignment

https://www.loom.com/share/2330b2716ba74443a621f1dd4a424be4

**Comment by pranavrajs** [comment]
@tejaswinichile @fayazara  Found a bug here. I can select multiple agents which should not be allowed.

**Comment by fayazara** [comment]
> Screenshot 2022-11-08 at 8 26 07 PM
> 
> @tejaswinichile @fayazara Found a bug here. I can select multiple agents which should not be allowed.

@pranavrajs I have already handled this here. - https://github.com/chatwoot/chatwoot/pull/4548/files#:~:text=inputType%20%3D%3D%3D%20%27-,search_select,-%27%22

@iamsivin Can you please retest the bug you mentioned  in https://github.com/chatwoot/chatwoot/pull/4548#pullrequestreview-1167398100, tested this today and the automations are now running as expected.

Once merged I can just change the `inputType` key for above macro action

**Comment by pranavrajs** [comment]
@fayazara I will get this merged in that case and let us test both of these together once the automation changes are merged.

**Pull request merged**
