### PR TITLE
fix: Fixes unread view blocking page scroll

### LINKED ISSUE #2545: Cannot scroll on mobile view if campaign is active
Issues:

- Cannot scroll the website if the campaign is active
- The position of the campaign message is random
- Cannot see the close button

Screenshot 2021-06-29 at 9 51 47 PM

### PR DESCRIPTION
**Pull request by nithindavid**
Fixes #2545 

**Why**
The woot-holder was occupying the entire page on mobile, which blocks user to scroll on parent page.  @AllanJard Thanks for the snippet.

### CODE REVIEW

**Comment by pranavrajs** [comment]
Screenshot 2021-07-29 at 8 36 09 PM

This introduces a broken experience in mobile. Please see the screenshot attached.

**Review by pranavrajs — CHANGES_REQUESTED** [review]
The experience is broken, please see the attached screenshot.

**Comment by AllanJard** [comment]
Interestingly I didn't see that with my hack, but I'm using an older version of ChatWoot, so possibly some of the newer CSS is conflicting?

**Comment by pranavrajs** [comment]
@AllanJard I think it works with less than 3 sentences. If you have longer text content, then it seems broken. Please see the screenshot below.

Screenshot 2021-07-29 at 8 41 24 PM

**Comment by nithindavid** [comment]
Missed this case, I'll update it.

**Comment by nithindavid** [comment]
Cases to test.

1. Campaign mode enabled - Enable campaigns and wait for X seconds for the campaign message to appear. See if the message is cut.
2. Unread mode - Send messages to widget when it's it' closed. 

Repeat these two on mobile screens.

**Comment by muhsin-k** [comment]
https://user-images.githubusercontent.com/12408980/128357242-31e7bdff-e735-4c30-85ec-735c937ed212.mov

**Review by muhsin-k — APPROVED** [review]

**Pull request merged**
