### PR TITLE
feat: Agent bot cant assign conversations to teams

### PR DESCRIPTION
**Pull request by giquieu**
# Pull Request Template

## Description

Implemented so that the API can process priority and agent/team changes per Agent Bot.

Fixes # (issue)
#7474 

## Type of change

Please delete options that are not relevant.

- [X] New feature (non-breaking change which adds functionality)
- [X] This change requires a documentation update (Swagger)

## How Has This Been Tested?

Through a Bot, assign agent and team to the conversation.
Using a Bot, I changed the Priority of the conversation.
Both cases were executed correctly.

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings

### CODE REVIEW

**Review by sojan-official — COMMENTED** [review]
- lets also add specs for `toggle_priority` and `assignments` to ensure the values are changes when request is made through bot token. 

ref: https://github.com/chatwoot/chatwoot/blob/1b6360d9d3dddf10bf16aa65ce672cc0710ababb/spec/controllers/api/v1/accounts/conversations_controller_spec.rb#L431

**Comment by giquieu** [comment]
@sojan-official Nice! Can I be of any help?

**Comment by sojan-official** [comment]
@giquieu, if you could add the additional test cases mentioned, that would be great.  Otherwise, we will prioritise based on the team's bandwidth.

**Comment by giquieu** [comment]
@sojan-official I sent some specs, testing priority and assignment changes by the Bot. What do you think?

**Comment by sojan-official** [comment]
@giquieu appologies for the delay on this. We will have this tested and merged. thanks a lot again for the contribution.

**Pull request merged**
