### PR TITLE
Feature: Group conversations 

### LINKED ISSUE #316: group conversations
hey! We're looking at integrating a chat system into our app and this looks like it would be a really great fit! Thanks for open sourcing! 

**Is your feature request related to a problem? Please describe.**
We are a mortgage lender looking to offer mortgages to groups of people. Ideally we'd like to be able to have group conversations, where an operator or customer could add another user to their conversation. 

**Describe the solution you'd like**
I've not looked at the code in too much detail but wondering how feasible this would be?

**Describe alternatives you've considered**
We've looked at paid alternatives like Intercom, i'd be great to build on something we can customise and push features upstream though.

**Additional context**

### PR DESCRIPTION
**Pull request by RonWalker22**
## Description

Add group conversations within web widget. Allow contacts to share a link to the conversation with other members.

Fixes #316

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?
Manually tested. Will add tests after frontend is finished.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

---

I’ll start working on the frontend sometime next week. But I wanted to share my progress so far. I’m nearly finished with the backend. I need to add tests, and fix any issues that come up.  

Also here are some questions/thoughts that came up along the way.  

### shared link url path

The link requires a default url path. I was going to make the default path the current path of the contact who copies the share link. But, I decided instead to make the default url path equal to `websiteURL`. In the future, we might want to create a dedicated setting for `shareLinkURL`.

### web widget full screen 
The web widget automatically opens when conversation is accessed through a shared link. I think that’s great for now. In the future, we might want to create a dedicated setting(boolean) to enable auto full screen.

<strike>
### no new cookies

I was unsure about this. But I decided not to create new cookies for group conversations(don’t want to abuse this privilege). So unlike primary(first) contact, no cookies are set for group conversations. So, a new participant is created every time the share link is used. Also, the group conversation can only be accessed through the share link for everyone except the primary contact.

I’m not sure this is going to work(I’ll know once frontend is done), so I just add cookies at the end if it’s required.
</strike>  

### finding conversation

I’m not sure how reliable the `get_conversation` method is within `widgets_controller.rb`. 
Due to each `contact_inbox` having many conversations, this could lead to issues later. 
We eventually need to tie all contacts to the new `ConversationParticipants` model, instead(or in addition to) the `contact_inbox` model. That will make finding conversations more reliable for secondary contacts. 

---

Let me know what you think about the  above and the progress so far. 

In addition to looking at the code, you can manually test it out(I will add tests later). All you need to do is click on the share link button(it's a new icon near the emoji icon ) and copy the link into a new tab. The web widget should open automatically to the conversation. When you send messages you won't be able to tell it's a new contact communicating yet(still need to do frontend). But you can see that it is indeed a new contact communicating by checking in `rails c` If you look at the last few messages in the conversation, you will see they are coming from different contacts.

### CODE REVIEW

**Comment by RonWalker22** [comment]
Also still need to add localization for Copied Link message.

**Comment by pranavrajs** [comment]
Hey, @RonWalker22 This approach seems good to me.

> I’m not sure this is going to work(I’ll know once frontend is done), so I just add cookies at the end if it’s required.

I guess you will need to do this, please let us know when you hit a roadblock.

**Comment by RonWalker22** [comment]
I should be finished with this sometime this week. I just need to fix an "agent is typing" bug, remove bot messages for those who join the conversation, and add tests. 

Here's the current iteration: https://www.youtube.com/watch?v=1if1bmUcEmA&feature=youtu.be

**Comment by RonWalker22** [comment]
Ready for review

**Comment by RonWalker22** [comment]
I'm not sure where to put this, so i'll post it here: 


# Group Conversation Docs

### Vocab

> **Primary contact** is the contact who started the conversation

> **Secondary contacts** are contacts who later join the conversation


### Intro

Group conversations are available in the web widget channel. To start a group conversation a contact shares the group link(the link icon to the right of the chat input).  


### Enable

Although the group conversation feature technically always enabled, the share link will not be displayed if the channel’s website domain is not present.

So, within the inbox settings, set the "Website Domain" to enable group conversations. The "Website Domain" is used to create the base url for every share link. 


### Manually test

To manually test/play around with the group conversation feature, you will need to use a different browser for each contact or a different tap within the same browser(clear your browser cookies[see 1-A]) for each contact.


---


### Feature Differences

Some web widget channel features work differently within group conversations.

#### Typing Indicator

All contacts can see when the agent is typing. 
All contacts are **unable** to see when other contacts are typing.
The agents are able to see all contacts who are typing.

#### Template messages

All template messages are hidden from secondary contacts. So only primary contacts can view template messages.


#### Chat widget auto open

When a conversation is accessed through a share link, the widget is opened automatically.




---


###### [1-A]

If you want to use the same browser for different contacts:

* After you create the conversation you will receive a cookie named `cw_conversation`.
  * contact 1 is created within this tab
* Delete the `cw_conversation` cookie and then copy and paste the group link within a new tab
* You will then receive a cookie named `cw_group_conversation{id}`
  * contact 2 is created within this tab
* Continue to delete the `cw_group_conversation{id}` cookie and copy and paste the group link if you wish to create any additional contacts.

----

**Comment by sojan-official** [comment]
@RonWalker22  thanks a lot for the work on this PR and the detailed testing instructions. I Will review and test this PR over this week.

**Comment by RonWalker22** [comment]
@sojan-official  Awesome! 

Also, I wanted to point out that I built this feature for a custom API channel. I worked on the web widget channel because it was requested by other community members.

However, this feature is a big shift for the web widget channel. 

It’s great to support group conversations in the web widget channel, but it comes at a huge cost(IMO). 

Whenever someone makes a feature for the web widget channel, they will have to think about how that feature will work within group conversations. I have already made adjustments to the typing indicator, and template messages features. But when someone from the community wants to add an additional feature to the web widget channel, will the responsibility of checking/testing against the group conversation fall on that community member or be pushed on the core team? In any event, extra work, and opportunity for bugs, is created.

**Comment by pranavrajs** [comment]
> Also, I wanted to point out that I built this feature for a custom API channel. I worked on the web widget channel because it was requested by other community members. However, this feature is a big shift for the web widget channel. It’s great to support group conversations in the web widget channel, but it comes at a huge cost(IMO).

We have the concept of feature flags. I think this feature could initially be in a feature flag and test it out on app.chatwoot.com, then release it to public.

> Whenever someone makes a feature for the web widget channel, they will have to think about how that feature will work within group conversations. I have already made adjustments to the typing indicator, and template messages features. But when someone from the community wants to add an additional feature to the web widget channel, will the responsibility of checking/testing against the group conversation fall on that community member or be pushed on the core team? In any event, extra work, and the opportunity for bugs, is created.

I think in order to keep the product stable in every release, core team actually does a QA. The developer who have added a feature might not be aware of all the features, so the responsibility to make sure that the new feature does not break existing ones reside on the core team.

**Comment by pranavrajs** [comment]
@RonWalker22 An update here, we are just discussing the UX for multiple participants on the dashboard. There might be some tweaks which we want to do. Otherwise, PR looks good. I will post a detailed review this week.

**Comment by RonWalker22** [comment]
some backend improvement ideas for future iterations of this feature.

# Improvements:

### Cookies

* right now
  * for all secondary contacts, a new cookie and contact is created for every new conversation they join.(this doesn't apply to primary contacts)

* future
  * a new cookie should still be created when joining a new conversation. But a new contact should not be created if one already exists.

### PubsubToken

* right now
  * all secondary contacts use the primary contact's PubsubToken.
* future
  * every contact should use their own PubsubToken.

**Comment by pranavrajs** [comment]
@RonWalker22 We had a change about the way we were handling the message sender, instead of two attribute we created a polymorphic sender attribute. I merge the changes and resolve the conflict this weekend.

**Comment by CL545740896** [comment]
Can it  add a Group Channel with agents? For Web internal Account

**Comment by sojan-official** [comment]
@CL545740896  Not at the moment. But its a use case which we are tracking.

**Comment by RonWalker22** [comment]
@pranavrajs this has been open for a while, any updates? Should we close this?

**Comment by pranavrajs** [comment]
@RonWalker22 Really sorry about, this got deproiritized due to a lot of reason. We still want to get this merged, hopefully by November end sprint. We are having a couple of updates with popout buttons and multiple conversation on widget. We will take this up afterwards. Thanks again for the work and patience.

**Comment by sojan-official** [comment]
Hey @RonWalker22, unfortunately, we weren't able to get to this PR yet because of other higher priority items.  Looking at the roadmap, it seems like it will be even more delayed before the team can get back to this.  

With the newer pieces like HMAC identification and multiple conversations, we will have many more scenarios to think through and test before enabling group conversations. So I will close this PR for now until we have a solid plan to cover this use case.  

Apologies again for the lapse in communication. Once again appreciate the effort you have put into these changes.

**Pull request closed without merging**
