### PR TITLE
fix(1285): make the field not selectable

### LINKED ISSUE #1285: Bug: Clicking multiple times creates a selection for the text
Screenshot 2020-09-29 at 12 21 45 PM

Clicking multiple times creates a selection for the text on widget

### PR DESCRIPTION
**Pull request by Nico385412**
# Pull Request Template

## Description

I would to make my first issue, and this issue is quite simple to fix ^^

Fixes #1285 

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

I added the css rule on https://www.chatwoot.com/help-center/ directly on the div

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by pranavrajs** [comment]
@Nico385412 Thanks for the PR. This seems to be working, but the solution is not complete. We have 2 different designs for the widget. Can you please add the same for both designs? You can see the details about this here https://www.chatwoot.com/docs/website-sdk

**Comment by Nico385412** [comment]
@pranavrajs It should be okey now :D 
(Sorry for the delay ^^)

**Review by pranavrajs — CHANGES_REQUESTED** [review]
@Nico385412 Thanks for the update on this. This solution works, but the code seams to unnecessarily repeated. In my opinion, you only need to set `user-select: none` on `.woot-widget-bubble`. It should cover all the cases. Would you be able to make that change?

**Comment by Nico385412** [comment]
@pranavrajs it should be ok now :D

**Review by pranavrajs — APPROVED** [review]

**Pull request merged**
