### PR TITLE
Enhancement: Add background color to draggable blocks in the sidebar

### PR DESCRIPTION
**Pull request by SanjuSudheerM**
Enhanc: Add background color to draggable blocks in the sidebar

## Description

#3554 

Fixes # (issue)

Added background-color property to the draggable element `list-group-item`

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

On dragging the section a background color of white will appear to it.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

fix

### CODE REVIEW

**Comment by nithindavid** [comment]
@SanjuSudheerM PR looks neat 💯  Can you update the PR title ?

**Comment by SanjuSudheerM** [comment]
@nithindavid updated the PR title.

**Comment by nithindavid** [comment]
@SanjuSudheerM While testing I found that we have a contact sidebar with same drag functions. Can you update the change to fix that too ?



Probably in `app/javascript/dashboard/modules/contact/components/ContactPanel.vue`

**Comment by SanjuSudheerM** [comment]
@nithindavid I made the above-said changes, but the pre-commit hook fails with the following message

```
Your Ruby version is 2.7.3, but your Gemfile specified 3.0.2
husky - pre-commit hook exited with code 18 (error)
```
I have no ruby file change in local and eslint is passing. Please let me know if you have any hacks.

**Comment by nithindavid** [comment]
You need to upgrade your Ruby version. For hack try `git commit -m "COMMIT MESSAGE " --no-verify`

**Review by nithindavid — APPROVED** [review]

**Pull request merged**
