### PR TITLE
fix: change teamid

### PR DESCRIPTION
**Pull request by s00d**
## Description

teamId does not change, added watch

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by pranavrajs** [comment]
@s00d Can you please share the error here?

**Comment by s00d** [comment]
> @s00d Can you please share the error here?

if you select Teams and then select chat, the selected team in the left menu switches back to all dialogs, in general, that's it, my fix fixes this, you just don't have tracking of the teamid change

**Comment by scmmishra** [comment]
> > @s00d Can you please share the error here?
> 
> if you select Teams and then select chat, the selected team in the left menu switches back to all dialogs, in general, that's it, my fix fixes this, you just don't have tracking of the teamid change
> 
> for this, there must be teams in the left menu, at first, they need to be created :)

@s00d I was unable to reproduce this, can you provide detailed steps?

**Comment by s00d** [comment]
> > > @s00d Can you please share the error here?
> > 
> > 
> > if you select Teams and then select chat, the selected team in the left menu switches back to all dialogs, in general, that's it, my fix fixes this, you just don't have tracking of the teamid change
> > for this, there must be teams in the left menu, at first, they need to be created :)
> 
> @s00d I was unable to reproduce this, can you provide detailed steps?

Are you serious right now? What can't you repeat in the instructions with just two steps?

**Review by scmmishra — APPROVED** [review]
Hey @s00d managed to reproduce this, apologies for the confusion. Approving the PR

**Pull request merged**
