### PR TITLE
Fix: Outgoing email sender header translation issue

### LINKED ISSUE #3380: Translation issue - outgoing email sender (FROM)
**Describe the bug**

By default, all emails sent by agents have the following "from" header in any language:
**Agent_Name from CompanyName <emailaddress@domain.com>**

**To Reproduce**

1. Go to Profile Setting and set your language to "French"
2. Go to Email Inbox and add an answer to a conversation
3. Login to the recipient email address to open the message you've just sent

**Expected behavior**

The FROM header should be **Agent_Name de CompanyName <emailaddress@domain.com>**, not **Agent_Name from CompanyName <emailaddress@domain.com>**

Same issue with conversation continuity, chat transcripts.

### PR DESCRIPTION
**Pull request by akhilgkrishnan**
# Pull Request Template

## Description

 Outgoing email-sender header translation issue fixed.("from" header translation fix)

Fixes #3380 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Tested using RSpec

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by sojan-official** [comment]
@akhilgkrishnan  Just a note on the translations. We are only required to edit the English version ie locale/en. Crowdin will take care of adding the changes to all other language files. It will help us to keep the PRs smaller.

**Comment by akhilgkrishnan** [comment]
> @akhilgkrishnan Just a note on the translations. We are only required to edit the English version ie locale/en. Crowdin will take care of adding the changes to all other language files. It will help us to keep the PRs smaller.

@sojan-official the issue was basically for french, can I update that one also? from -> "de"

**Comment by sojan-official** [comment]
@akhilgkrishnan Once we convert this into translatable strings, it will be picked up by crowdin and our community translators will create the appropriate version of the string into the matching language file. We will be bringing these translations back into the chatwoot repo before cutting a new release. 

Crowdin expects all the translations to happen there instead of in our GitHub.

**Review by sojan-official — APPROVED** [review]
Thanks for the changes @akhilgkrishnan  We will QA and get this merged. 🎉

**Pull request merged**
