### PR TITLE
feat: Setup cypress

### PR DESCRIPTION
**Pull request by iamsivin**
# Pull Request Template

## Description

Please include a summary of the change and issue(s) fixed. Also, mention relevant motivation, context, and any dependencies that this change requires.
Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

`yarn run cypress`

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by sojan-official** [comment]
@iamsivin  we already have cypress added via cypress rails. This lets us run seed commands in the backend when required for specific scenarios. Probably take a look and see if it works before we add it via npm 

https://www.chatwoot.com/docs/contributing-guide/tests/cypress/

**Comment by pranavrajs** [comment]
@sojan-official This PR is doing an upgrade of the existing cypress config we set up. We have 4.x version installed, but the latest version 11.x. @iamsivin tried to upgrade to the latest while he was doing experiments with the test setup we have.

**Comment by sojan-official** [comment]
@iamsivin will we be taking this forward ?

**Comment by iamsivin** [comment]
> @iamsivin will we be taking this forward?

We can move this forward. Need to build some knowledge on WordPress.

**Comment by scmmishra** [comment]
Closing this for now, we can take a look once we have the bandwidth

**Pull request closed without merging**
