### PR TITLE
Auto resolve conversations after n days of inactivity

### LINKED ISSUE #418: Auto resolve after `n` days of inactivity
**Is your enhancement request related to a problem? Please describe.**
Add a feature to resolve the conversation after `n` days of inactivity. If I'm waiting for a response from the customer and he has not responded in `n` days, the conversation needs to resolved automatically.

**Describe the solution you'd like**
Add a setting in account `auto_resolve_duration` which can be set by an admin, if there is no message or any activity happening in that duration, mark the conversation as resolved.

### Acceptance criteria

- Add a DB field on account `auto_resolve_duration`
- The conversation should auto-resolve if there is no activity.

### PR DESCRIPTION
**Pull request by akashdotsrivastava**
## Description

Closes #418 

1. Added new option to account settings: `Number of days after a ticket should auto resolve if there is no activity` 
(`auto_resolve_duration` in db) (non-mandatory, more than 1)
Screenshot 2020-10-04 at 10 51 00 PM

2. If auto resolve duration added for an account, a new background job (`AutoResolveConversationsJob`) is scheduled each time:
    a. A new conversation is created
    b. A resolved conversation is reopened
    to run after (allowed time of inactivity - time since last activity in conversation)
3. When `AutoResolveConversationsJob` is ran, it checks if there has been activity since the last time job was scheduled for this conversation. If yes, reschedules the job after the appropriate difference of time from inactivity, otherwise resolves the conversation without a resolver, and finishes the job.
4. Job is resolved without a resolver, so it is marked resolved by system, and shows up a similar resolved message
Screenshot 2020-10-04 at 10 49 50 PM

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## How Has This Been Tested?

- Tested that the new field added to accounts (auto_resolve_duration) does not produce issues when accounts updated without it. Also minimum 1 day allowed as the auto resolved duration, if at all added
- Tested that right resolved status message when resolved by the system, and it does not break the existing resolve/open flow
- Added specs for all rails changes done.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by pranavrajs** [comment]
@akashdotsrivastava I've merged the changes, you should be able to rebase this branch with master now. Please let me know if you need something from me.

**Comment by akashdotsrivastava** [comment]
@pranavrajs Thanks.
Done with changes at my end. Details in the PR description. Feedback/review needed.

**Review by sojan-official — APPROVED** [review]
@akashdotsrivastava  Thanks a lot for the changes. The changes look good to me so far. We will QA this and merge it.  

- Sorry for the lack of instruction on the translations part.  We only expect the English translations, 😅 I  will update the contribution guidelines mentioning the same. 

There might be a couple of cases which we would need to think about as we build on this further.
- When someone enables the auto resolving, the expectation will be that it will work for their existing open tickets. So will have to trigger jobs for the existing open conversations at that point
- Someone enabling this with a higher duration like 100 days and then later decides to reduce the time frame to a shorter duration like 10 days. The existing jobs won't schedule until 100 days. 

Considering these cases another approach we could take is a single job, that is enqueued at the account level. Which iterates through all the open conversations in batches and resolves the ones that have passed the threshold. 

cc: @sony-mathew  @pranavrajs

**Comment by akashdotsrivastava** [comment]
@sojan-official Thanks for the feedback. That makes sense.
I think I'll just go ahead and make the changes for the use cases you suggested. I'll update this PR itself if it is still open by the time I push new changes, otherwise will open another PR.

**Pull request merged**
