### PR TITLE
Update

### PR DESCRIPTION
**Pull request by Justman10000**
## Description

Fixes spelling mistakes

### CODE REVIEW

**Comment by Justman10000** [comment]
@sojan-official

**Comment by Justman10000** [comment]
@sojan-official

There?

**Comment by sojan-official** [comment]
@Justman10000  could you share details on the error that we are trying for webpacker ? 
also, let's skip trivial changes. Please go through https://www.chatwoot.com/docs/handbook/engineering/pr-guidelines#avoid-cosmetic-changes

**Comment by pranavrajs** [comment]
@Justman10000 Appreciate the effort, but it is not clear what the changes with webpacker are related to. Please feel free to open an issue and discuss. We will reopen the PR if it is required.

**Pull request closed without merging**
