### PR TITLE
fix: Token type `hr` not supported by Markdown parser

### PR DESCRIPTION
**Pull request by scmmishra**
For the message schema we provide, `---` which is a horizontal rule element is not handled. This results in an error. This PR adds a exception catch to ensure that the signatures continues to work

To test, update the signature from the DB console to the following

```
---

Signature
```

Try using the editor after that, the dashes should be gone without error

### CODE REVIEW

**Comment by scmmishra** [comment]
@nithindavid need your thoughts here, on what schema should I use for the Markdown parser

**Comment by nithindavid** [comment]
@scmmishra Do we need the conversion  to common mark if we add serialiser which would remove/support the hr?

**Comment by scmmishra** [comment]
> @scmmishra Do we need the conversion to common mark if we add serialiser which would remove/support the hr?

We had to do this in this PR: https://github.com/chatwoot/chatwoot/pull/7944
The problem was that signatures like `- Jack` would get converted to `* Jack` by the editor automatically after pushing it. So any search replace methods used to manage signatures stopped working. So we thought it's best to Sanitze it by the parsers & serializer used internally by the editor to convert it to a compliant common mark format

**Comment by scmmishra** [comment]
@nithindavid this is ready for review

**Comment by scmmishra** [comment]
@iamsivin @nithindavid let me know if this is good to go

**Comment by iamsivin** [comment]
> @iamsivin @nithindavid let me know if this is good to go

@scmmishra Is it possible to add test cases for this PR?

**Comment by scmmishra** [comment]
> > @iamsivin @nithindavid let me know if this is good to go
> 
> 
> 
> @scmmishra Is it possible to add test cases for this PR?

Added it to editorHelper.spec.js, anything in particular to have tested?

**Comment by iamsivin** [comment]
> > > @iamsivin @nithindavid let me know if this is good to go
> > 
> > 
> > @scmmishra Is it possible to add test cases for this PR?
> 
> Added it to editorHelper.spec.js, anything in particular to have tested?

Not that, I mean the test case for testing the PR locally.

**Review by iamsivin — APPROVED** [review]
Code LGTM

**Comment by scmmishra** [comment]
> > > > @iamsivin @nithindavid let me know if this is good to go
> 
> > > 
> 
> > > 
> 
> > > @scmmishra Is it possible to add test cases for this PR?
> 
> > 
> 
> > Added it to editorHelper.spec.js, anything in particular to have tested?
> 
> 
> 
> Not that, I mean the test case for testing the PR locally.

Done

**Pull request merged**
