### PR TITLE
feat: add footer into vueapp

### LINKED ISSUE #7139: feat: Add footer partitial into vueapp layout
### Is your feature or enhancement related to a problem? Please describe.

To feel free to add any changes into footer  without resolving the conflict which hard change in vueapp layout

### Describe the solution you'd like

New feat: Add footer `partitial` into `vueapp` layout

### Describe alternatives you've considered

_No response_

### Additional context

For example:

https://github.com/TommyTechWorkshop/chatwoot/commit/968642da40fe82636e576ac1e63112decb3d073d
https://github.com/TommyTechWorkshop/chatwoot/commit/4a5db26593e1c485449c11947d65a15cabaf501f

### PR DESCRIPTION
**Pull request by memorycancel**
Closes #7139 

New feat: Add footer `partitial` into `vueapp` layout

To feel free to add any changes into footer  without resolving the conflict which hard change in vueapp layout

For example:

https://github.com/TommyTechWorkshop/chatwoot/commit/968642da40fe82636e576ac1e63112decb3d073d
https://github.com/TommyTechWorkshop/chatwoot/commit/4a5db26593e1c485449c11947d65a15cabaf501f

In addition, is there a plan to decoupling the these codes in to separate folder which is like `GitLab`, so the forkers can customize their business without resolving the conflicts when merge the latest code from upstream. 
Could you please have a look at this, thanks @sojan-official  @pranavrajs

----
Besides, can we implement a mechanism to override the same name file which like 

`custom/app/views/dashboard/_footer.html.erb` 
 override 
`app/views/dashboard/_footer.html.erb`

### CODE REVIEW

**Comment by memorycancel** [comment]
Besides, can we implement a mechanism to override the same name file which like 

`custom/app/views/dashboard/_footer.html.erb` 
 override 
`app/views/dashboard/_footer.html.erb`

@sojan-official @pranavrajs

**Comment by memorycancel** [comment]
> Besides, can we implement a mechanism to override the same name file which like
> 
> `custom/app/views/dashboard/_footer.html.erb` override `app/views/dashboard/_footer.html.erb`
> 
> @sojan-official @pranavrajs

I tried to implement in this PR: https://github.com/chatwoot/chatwoot/pull/7213/files 
Could you please comment, thanks! @sojan-official @pranavrajs

**Comment by pranavrajs** [comment]
@memorycancel Sorry, we cannot take this in at the moment. It feels like a custom use-case and doesn't add much value to the product. We can re-open the PR in future if there is a strong community ask.

**Comment by pranavrajs** [comment]
If it still needed, maintaining a fork is the way to go. 👍

**Comment by memorycancel** [comment]
> @memorycancel Sorry, we cannot take this in at the moment. It feels like a custom use-case and doesn't add much value to the product. We can re-open the PR in future if there is a strong community ask.

Thank you

**Pull request closed without merging**
