### PR TITLE
feat: Ability to lock the conversation to a single thread in API channels

### PR DESCRIPTION
**Pull request by giquieu**
# Pull Request Template

## Description

Added the possibility to mark as a single conversation in the API type inbox. This allows the conversation builder to search for the last conversation.
I thought about searching for the last conversation with created_at: desc order, as is done in some channels... but I didn't change the way the conversation is searched.

Fixes # (issue)
#7726 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Added test case in conversation_builder_spec;

I started a new conversation via API, sent some messages and ended it.
I started another conversation in the same channel, and verified that the conversation remained the same.

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by BrOrlandi** [comment]
I think the implementation is really simple, as the lock is already possible in other kinds of inboxes. I hope this feature is merged soon!

**Comment by eliezerazevedo** [comment]
I am hoping that this PR will be merged soon.

**Comment by sojan-official** [comment]
@giquieu  Appologies on the delay on this one. We are currently testing this and will have this merged. Thanks a lot for the help !

**Review by sojan-official — APPROVED** [review]
- verified to be working

**Pull request merged**
