### PR TITLE
chore: Bump ruby from 2.7.1 to 2.7.2

### PR DESCRIPTION
**Pull request by azyzio**
Re issue #1399

### CODE REVIEW

**Comment by SmartManoj** [comment]
Too much file changes 😐

**Review by sojan-official — APPROVED** [review]

**Comment by azyzio** [comment]
@SmartManoj what do you mean?

**Comment by SmartManoj** [comment]
Did you use any script to bump?

**Comment by azyzio** [comment]
@SmartManoj I still don't know what you mean. What script?

**Comment by SmartManoj** [comment]
https://pypi.org/project/bumpversion/

**Comment by azyzio** [comment]
@SmartManoj I didn't use it

**Comment by troscoe** [comment]
Production deployment guide for Linux VM @ https://www.chatwoot.com/docs/deployment/deploy-chatwoot-in-linux-vm refers to develop branch scripts https://raw.githubusercontent.com/chatwoot/chatwoot/develop/deployment/setup_18.04.sh and https://raw.githubusercontent.com/chatwoot/chatwoot/develop/deployment/setup_20.04.sh.

Unfortunately both those scripts checkout master branch which is still on 2.7.1.

https://github.com/chatwoot/chatwoot/pull/1462

**Pull request merged**
