### PR TITLE
fix: Widget away text translations

### PR DESCRIPTION
**Pull request by muhsin-k**
Fixes https://linear.app/chatwoot/issue/CW-3108/translate-preposition-at

### CODE REVIEW

**Review by iamsivin — APPROVED** [review]
LGTM

**Review by pranavrajs — CHANGES_REQUESTED** [review]
image

**Review by scmmishra — APPROVED** [review]

**Review by iamsivin — APPROVED** [review]

**Comment by muhsin-k** [comment]
Note: I will be working to simplify the timeLeftToBackInOnline logic. Lets merge this PR after that.

**Comment by vishnu-narayanan** [comment]
Fixes https://github.com/chatwoot/chatwoot/issues/9285

**Comment by muhsin-k** [comment]
Closing this here, will reopen when we get back to this.

**Pull request closed without merging**
