### PR TITLE
fix: db/seeds.rb field contact_inbox is undefined

### PR DESCRIPTION
**Pull request by givetimetolife**
# Pull Request Template

## Description

run: `docker-compose run --rm rails bundle exec rails db:chatwoot_prepare` error: field contact_inbox is undefine

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by giquieu** [comment]
Hello,
I don't think it's ideal to remove the contact's inbox.
It seems to be the right thing to send the inbox contact and keep both props.
Maybe I could be wrong... @sojan-official What do you think?

`contact_inbox = ::ContactInboxWithContactBuilder.new(
    source_id: user.id,
    inbox: inbox,
    hmac_verified: true,
    contact_attributes: { name: 'jane', email: 'jane@example.com', phone_number: '+2320000' }
  ).perform

  conversation = Conversation.create!(
    account: account,
    inbox: inbox,
    status: :open,
    assignee: user,
    contact: contact_inbox.contact,
    contact_inbox: contact_inbox,
    additional_attributes: {}
  )`

**Comment by sojan-official** [comment]
> Hello, I don't think it's ideal to remove the contact's inbox. It seems to be the right thing to send the inbox contact and keep both props. Maybe I could be wrong... @sojan-official What do you think?
> 
> seeds.rb: Line 49-64
> 
> ```
>   contact_inbox = ::ContactInboxWithContactBuilder.new(
>     source_id: user.id,
>     inbox: inbox,
>     hmac_verified: true,
>     contact_attributes: { name: 'jane', email: 'jane@example.com', phone_number: '+2320000' }
>   ).perform
> 
>   conversation = Conversation.create!(
>     account: account,
>     inbox: inbox,
>     status: :open,
>     assignee: user,
>     contact: contact_inbox.contact, <-
>     contact_inbox: contact_inbox, <-
>     additional_attributes: {}
>   )
> ```

yep this is right

**Comment by givetimetolife** [comment]
Thanks for your help, I have updated the current push request.  
Excited to do something for chatwoot! Since I'm new to ruby, the first commit was a bit sloppy.  @giquieu @sojan-official

**Comment by sojan-official** [comment]
@givetimetolife  Welcome onboard :D

**Pull request merged**
