### PR TITLE
feat: add gh action to build arm64 docker images

### PR DESCRIPTION
**Pull request by vishnu-narayanan**
# Pull Request Template

## Description

We are using docker hub automated builds to build and push chatwoot images. Docker hub does not support multiarch
images for automated builds. This PR is try to build the images using github-action.
 
- Add gh action to build chatwoot arm64 image.
- This does not push the resulting image to dockerhub at the moment.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by sojan-official** [comment]
@vishnu-narayanan  should we close this PR for now?

**Comment by vishnu-narayanan** [comment]
Reopening this again to check `arm` compatability.

**Comment by sojan-official** [comment]
note: fix issue with grpc
------
```
 > [linux/386 pre-builder  7/13] RUN if [ "production" = "production" ]; then   bundle config set without 'development test'; bundle install -j 4 -r 3;   else bundle install -j 4 -r 3;   fi:
#40 5236.0 levels) in create_threads'
#40 5236.0 
#40 5236.0 An error occurred while installing grpc (1.43.1), and Bundler cannot continue.
#40 5236.0 
#40 5236.0 In Gemfile:
#40 5236.0   google-cloud-dialogflow was resolved to 1.2.0, which depends on
#40 5236.0     google-cloud-dialogflow-v2 was resolved to 0.6.4, which depends on
#40 5236.0       gapic-common was resolved to 0.3.4, which depends on
#40 5236.0         googleapis-common-protos was resolved to 1.3.12, which depends on
#40 5236.0           grpc
------
Dockerfile:43
```

**Comment by sojan-official** [comment]
@vishnu-narayanan  is this PR relevant now that we have https://github.com/chatwoot/chatwoot/commit/7b1630b468dda69914b5b7874fddddb5af29b30a ?

**Pull request closed without merging**
