### PR TITLE
chore: Account auto resolution time validation

### LINKED ISSUE #3474: chore: Add validation for account auto resolution time
At the moment a person can configure even value `999999` for account auto resolution time in the account settings page. Which in the backend would give an `::DatetimeFieldOverflow: ERROR: timestamp out of range`

- [ ] Set maximum auto resolution time period to 999 days
- [ ] Frontend validation to show error if range crosses that
- [ ] Backend validation to prevent values saved over 999 days

### PR DESCRIPTION
**Pull request by shivamsinghchahar**
# Pull Request Template

## Description

- Added `less_than_or_equal_to: 999` validation for `auto_resolve_duration`.
- Added validation on the frontend for auto-resolve duration field in account settings.
- Updated the error message on the frontend.

Fixes #3474 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Tested manually and also added a unit test.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by pranavrajs** [comment]
@tejaswinichile Can you please test this out and take the next steps?

**Comment by shivamsinghchahar** [comment]
Is there anything needed on this PR from my side?

**Comment by tejaswinichile** [comment]
Tested on my local working fine. 💯

**Review by tejaswinichile — APPROVED** [review]
LGTM

**Pull request merged**
