### PR TITLE
feat: Add option to select custom slack channel

### LINKED ISSUE #1488: Allow users to use a custom slack channel name
Right now, the default Slack channel name is assumed as #customer-conversations. 

Allow the users to select a different channel name or create a new channel from the UI.

### PR DESCRIPTION
**Pull request by pranjal0819**
## Description

Allow the users to select a different channel name from the UI.

Fixes #1488 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## How Has This Been Tested?

image

## Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by pranjal0819** [comment]
Need to do:

1. Add test case
2. Update document

**Comment by pranjal0819** [comment]
@sojan-official Any changes required?

**Comment by sojan-official** [comment]
@pranjal0819  The changes look good to me. I didn't get a chance to test it yet.
Could you handle the failing test cases as well ?  I will do the QA meanwhile.

**Comment by pranjal0819** [comment]
> @pranjal0819 The changes look good to me. I didn't get a chance to test it yet.
> Could you handle the failing test cases as well ? I will do the QA meanwhile.

I handle the failing test case when the user select a Direct message or didn't select any channel

**Comment by pranavrajs** [comment]
@pranjal0819 Shall I take it from here and merge it?

**Comment by tasn** [comment]
Does it also support private channels? 🙏🏻

**Comment by pranjal0819** [comment]
> @pranjal0819 Shall I take it from here and merge it?

I write the test case after that

**Comment by pranavrajs** [comment]
@sojan-official Deploying this to staging now for testing.

**Comment by pranjal0819** [comment]
@pranavrajs Any changes required?

**Pull request closed without merging**
