### PR TITLE
Fixed installation of gem bundles (lograge, rack-mini-profiler, stack…

### PR DESCRIPTION
**Pull request by shaheer-haider**
# Pull Request Template
Fix Containers Installation Issue for Development

## Description

Gems is not able to install the following packages
* lograge (0.12.0)
* rack-mini-profiler (3.0.0)
* stackprof (0.2.24)
* nokogiri (1.14.3)
* request_store (1.5.1)

Please include a summary of the change and issue(s) fixed. Also, mention relevant motivation, context, and any dependencies that this change requires.

After adding the following line to the Dockerfile, the issue is resolved
~~~~
RUN apk update && RUN apk add --no-cache build-base
~~~~

Fixes **#https://github.com/chatwoot/chatwoot/pull/6897**

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by shaheer-haider** [comment]
Updated the branch so it can be merged easily.

**Comment by shaheer-haider** [comment]
I just cloned the repo and tried to build the development image using
~~~~
docker compose build
~~~~

It was building fine and images were running too but the rails server wasn't running properly due to some missing packages, which are:
lograge (0.12.0)
rack-mini-profiler (3.0.0)
stackprof (0.2.24)
nokogiri (1.14.3)
request_store (1.5.1)

I added a command `RUN apk update && RUN apk add --no-cache build-base` in docker files to update and install the build-base so these packages install properly.

**Comment by sojan-official** [comment]
@vishnu-narayanan  can you check ?

**Comment by shaheer-haider** [comment]
What's the status @sojan-official

**Comment by vishnu-narayanan** [comment]
@shaheer-haider Thank you for the PR.

**Comment by shaheer-haider** [comment]
> @shaheer-haider Thank you for the PR.

You're welcome.

**Review by vishnu-narayanan — APPROVED** [review]

**Pull request merged**
