### PR TITLE
Adding .foreman file so the PORT can be specified there

### PR DESCRIPTION
**Pull request by ankurp**
# Pull Request Template

## Description

Instead of specifying PORT manually for rails backend in `Procfile.dev` we can specify it in the `.foreman` file. We also default procfile to use `Procfile.dev` when running `foreman start`

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Manually run locally.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by ankurp** [comment]
Is this good to merge or any review comments?

**Comment by sojan-official** [comment]
@ankurp we also have community members using [overmind](https://github.com/DarthSim/overmind) . So just need to test out how the changes behave with it.  

I Will get back once I get a chance to test it in my local.

**Comment by ankurp** [comment]
Was someone able to verify this. If not we can close this.

**Comment by sojan-official** [comment]
Tested this with overmind 

```
overmind start  -f Procfile.dev RAILS_ENV=development
```

Rails server is booting up on port `5000` in my local. 
 
Hence closing this PR as it's more of a cosmetic change but comes with a risk of breaking the existing workflows.

**Pull request closed without merging**
