### PR TITLE
feat: Assign team with teams none option

### PR DESCRIPTION
**Pull request by tejaswinichile**
#5735 

https://www.loom.com/share/0fc2b6f1f61a4dd394d5a1e6534d267e

### CODE REVIEW

**Comment by fayazara** [comment]
> @tejaswinichile @pranavrajs I think this should not be in `Assign Team -> None`.
> 
> This is very confusing, Had the read the code to see where this option actually is 😅 .

**Comment by tejaswinichile** [comment]
@fayazara Should we just have the `Unassign Team` as a separate action, without params?

**Comment by fayazara** [comment]
> @fayazara Should we just have the `Unassign Team` as a separate action, without params?

Yes, like - `Remove assigned team`. Let me add this.

**Comment by tejaswinichile** [comment]
https://www.loom.com/share/94ca79626b034f7b8c92775393798f82


@fayazara Added the updated video with the new 'Remove assigned team' action.

**Review by fayazara — APPROVED** [review]
Working perfectly.

Tested - Adding Macro, Editing and Executing.
https://www.loom.com/share/cffe4913c7974adc97332e893b9e19a8

**Pull request merged**
