### PR TITLE
chore: Christmas Promo

### PR DESCRIPTION
**Pull request by fayazara**
## Description

Adds a christmas promo popup which show a voucher code that can be used while purchasing.

https://user-images.githubusercontent.com/15716057/210543529-077da38c-a619-4d76-ae7a-9eb438e199de.mp4

Fixes https://github.com/chatwoot/marketing/issues/170

### CODE REVIEW

**Comment by fayazara** [comment]
@Hricha-Shandily please have a look at this.

**Comment by Hricha-Shandily** [comment]
@fayazara This is mostly okay. A couple of minor points:

- We can change the subtext to this: `Use the code: "XMASCHATWOOT22" during checkout.` 
- The red background on the popup looks a bit too bright. 🤔 We can either use the blue brand colour or the same popup design used on the website. WDYT?

Any comments, @scmmishra ?

**Comment by scmmishra** [comment]
> Any comments, @scmmishra ?

If possible we can send them to the checkout page with the coupon applied? Or maybe just add a link to the checkout page or the billing page alone. It'll reduce a lot of friction.

**Comment by fayazara** [comment]
> > Any comments, @scmmishra ?
> 
> If possible we can add a link in the modal that sends them to the checkout page with the coupon applied? Or maybe just add a link to the checkout page or the billing page alone. It'll reduce a lot of friction.

I can send them to the pricing page, since they still need to pick a plan.

@Hricha-Shandily thoughts?

**Pull request merged**
