### PR TITLE
Feature/devise users

### PR DESCRIPTION
**Pull request by laurenball**

### CODE REVIEW

**Comment by laurenball** [comment]
hi @sojan-official! this is pretty close, but I'm having a difficult time with the local server on my end. it seems like every time there's an error, I have to rebuild and seed the database in order to get the page to load again. have you bumped into this? it's possible it has to do with my changes, but I figured I should ask

**Comment by sojan-official** [comment]
@laurenball thanks a lot for the PR.  I haven't encountered the particular issue that you mentioned. but no worries, Will debug it over this week and give you an update.

**Comment by laurenball** [comment]
thank you so much @sojan-official! for hacktoberfest purposes, I'm going to see if y'all have another small thing I can pick up before the month ends

**Comment by sojan-official** [comment]
@laurenball  :D if you can't find anything in the issues. feel free to add some specs for a model or controller, which doesn't have any already.  Will be happy to merge.

**Comment by sojan-official** [comment]
@laurenball Thanks a lot for your wonderful effort on this branch. 

As per the recent developments and the direction which we want to head towards,  some of the changes in this PR might not be relevant. Also helped us realize that the process we had during hacktoberfest wasn't all that great, assigning issues without clearly understanding the requirements. we are working on that front. 

I don't want the time you spent on this PR to be in vain, so let me take it up this weekend and salvage what we can into the master.  Really sorry for not getting back on this for a while.

**Comment by laurenball** [comment]
hey @sojan-official, it's no big deal! Sometimes things don't work out. If you think there are better ways forward (and I'm *sure* there are), we can close it with no bad feelings from me. I've been meaning to ping you for a bit now, so sorry for not saying as much sooner!

go forth and prosper :)

**Comment by laurenball** [comment]
which is to say, you don't need to spend your weekend trying to get my haphazard code working :)

**Comment by sojan-official** [comment]
The code is well written for it's intended purpose.
It's more about our initial idea of splitting the model. Upon revisiting it's not offering us much performance gain. Also having the two models that deal with user information might end up confusing for our future contributors. 
And over the PRs that came in last month, we were able to strip off a couple of the extra attributes from the user model as well. 

Thanks a lot again for taking it in good spirits. hopefully, we will see more contributions from you in the future 🙈

**Pull request closed without merging**
