### PR TITLE
fix: Slack integration redirect url missing client ID

### PR DESCRIPTION
**Pull request by sojan-official**
Fixes: #2304

### CODE REVIEW

**Review by nithindavid — APPROVED** [review]

**Comment by wflanagan** [comment]
@sojan-official Is it possible to get a new docker image?

**Comment by sojan-official** [comment]
@wflanagan  you can use the `develop` branch image until we release the next version. 

https://hub.docker.com/layers/94291362/chatwoot/chatwoot/develop/images/sha256-cf87f8eebb47435a4389a6435489cee385862347e7e866167da55308263c4832?context=explore

**Comment by wflanagan** [comment]
@sojan-official Thanks, I appreciate that. But, I think that's not a public image. I can't access it via that URL anyway.

**Comment by sojan-official** [comment]
> @sojan-official Thanks, I appreciate that. But, I think that's not a public image. I can't access it via that URL anyway.

https://hub.docker.com/r/chatwoot/chatwoot/tags please use the develop tag

**Pull request merged**
