### PR TITLE
Feat - New filters for contacts and conversations

### LINKED ISSUE #3938: Add support for Created At, Last Activity At filters in the UI
As per https://github.com/chatwoot/chatwoot/issues/3840, the support in the API for last_activity_at and created_at is added. Add this to the UI for the conversation filter as well.

- [ ] For Is greater than, Is less than use date picker.
- [ ] For is X days before, use number input, validation number should be greater than 0, less than 999
- [ ] Support the filter both on conversation and contact.

### PR DESCRIPTION
**Pull request by fayazara**
## Description
Adds new filters types for contacts and conversations
1. Created at
2. Last Activity

Allows users to filter data with above attributes with operators Is greater than (date picker), Is lesser than (date picker), Is X days before (Number input between 0 to 999)

Fixes #3938

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by fayazara** [comment]
@tejaswinichile What attribute key are you expecting for these filters **Is greater than**, **Is lesser than**, **Is x days before**?

I am sending them like these `is_greater_than`, `is_lesser_than`, `is_x_days_before`

**Comment by tejaswinichile** [comment]
```
{
    "payload":[
        {"attribute_key":"created_at","filter_operator":"days_before","values":["158"]},
        {"attribute_key":"created_at","filter_operator":"is_less_than","values":["2022-01-30"]}
    ]
}
````
date_filter


This is how the payload will look.

**Comment by fayazara** [comment]
@iamsivin please check now, I have update the keys.

**Comment by iamsivin** [comment]
> @iamsivin please check now, I have updated the keys.

Tested it locally, Looks Good to me 👍🏻

**Review by iamsivin — APPROVED** [review]

**Pull request merged**
