### PR TITLE
fix: plus icon in sidebar items should route to create page

### PR DESCRIPTION
**Pull request by surajput32**
## Description
- '+' icon for 'Add team' in the sidebar will redirect us to a new teams page
- '+' icon for 'Add label' in the sidebar will open up a modal for new label

Fixes https://github.com/chatwoot/chatwoot/issues/1965

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
I tested the functionality on my local machine.

Please describe the tests that you ran to verify your changes:
+ I clicked the new item icon i.e.(+ icon) in front of teams in the sidebar and successfully created a new team.
+ I clicked the new item icon i.e.(+ icon) in front of labels in the sidebar and successfully created a new label.

Provide instructions so we can reproduce the issue:
1. In `app/javascript/dashboard/components/layout/Sidebar.vue`, add `newLink: true` to `labelSection()` & `teamSection()`.
2. Now, you will see a '+' icon in front of `teams` and `labels` in the sidebar.
3. If you click on any of these, they will redirect us to the inbox page only.

## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by nithindavid** [comment]
@surajput32 Thanks for the PR :) Let this test this on my side.

**Comment by nithindavid** [comment]
@surajput32 I tested this on my local but the new icon buttons are not appearing. Can you check if this issue ? 

image

**Comment by surajput32** [comment]
@nithindavid Have you added `newLink: true` to `labelSection()` & `teamSection()` in `app/javascript/dashboard/components/layout/Sidebar.vue`?

**Comment by nithindavid** [comment]
> @nithindavid Have you added `newLink: true` to `labelSection()` & `teamSection()` in `app/javascript/dashboard/components/layout/Sidebar.vue`?
> I think it should be configurable i.e. those who want this icon, will have to add `newLink: true` to that section. But if we are thinking to make it default(i.e. Each section must have this icon), I will add `newLink: true` to them.
> 
> Let me know your thoughts.


@surajput32 Yes that would be great :) Also Sorry for editing your comment.
cc: @pranavrajs @sojan-official @muhsin-k

**Comment by surajput32** [comment]
Okay @nithindavid . I will add the change & let you know.

**Comment by surajput32** [comment]
@nithindavid I did the change however facing issue in alignment of `Cancel` button on `Add label` modal. Could you help me?

edited_chatwoot

**Comment by nithindavid** [comment]
@surajput32 You can remove the `div with columns medium-12` wrapping the buttons and keep them as direct children to modal-footer

**Comment by nithindavid** [comment]
I checked the PR. Nice work 🎉

**Comment by surajput32** [comment]
Thanks @nithindavid for the help. I did the changes. Please review.

**Pull request merged**
