### PR TITLE
Feature: Add persian translation

### PR DESCRIPTION
**Pull request by thg303**
# Adds Persian Translation

## Description

It would be nice to have the Persian language in the UI. it would help native speakers as mentioned in the issue.

Fixes issue #1016

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

I build a development environment instance on my LMDE machine and it looked ok.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by sojan-official** [comment]
@thg303 Thanks a lot for working on this. we will take this up for 1.7 release.

**Comment by thg303** [comment]
Thank you @sojan-official, by the way, one thing I have to mention is that "Persian" like "Arabic" and "Hebrew" has a right-to-left nature. So it would be great if we could support a "right-to-left" layout for the panel. I wonder if there's anything like that in the road-map or any consideration should I take, if it's ok to submit a PR for that?

**Comment by sojan-official** [comment]
@thg303 yes we do have it in backlog, would be great if you think you can take it forward. It was just that we don't have enough bandwidth to take it on ATM.

the approach we are thinking is to add the RTL attribute to the language config. Append the html with `dir="rtl"` based on the config. we will also have to iron out the layout breakages and css fixes.  I have repurposed https://github.com/chatwoot/chatwoot/issues/686 to take this on. 

will assign it to you if you are interested.

**Comment by pranavrajs** [comment]
@thg303 RTL support might require a good amount of effort. If you start a PR, I will be able to contribute and test it.

**Comment by pranavrajs** [comment]
@thg303 Thanks for the work and the PR. We use translate.chatwoot.com for translation related changes, I would suggest you take a look at that in the future :)

**Pull request merged**
