### PR TITLE
feat: Adds support for superscript in help center articles

### PR DESCRIPTION
**Pull request by nithindavid**
## Description

Loom https://www.loom.com/share/fdaf67a0e93c4861a7a4b0560e21f3fd

Fixes # (issue) https://linear.app/chatwoot/issue/CW-1476/support-all-markdown-options-in-the-article-editor

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by nithindavid** [comment]
@sojan-official Should I use the superscript renderer for places where we are rendering message content? eg `app/views/mailers/conversation_reply_mailer/conversation_transcript.html.erb`

**Comment by sojan-official** [comment]
@nithindavid Let's create a class `ChatwootMarkdownRenderer` and use that every instead of command mark renderer. 
and inside that do the processing. LMK if you need help with this.

**Comment by nithindavid** [comment]
@sojan-official I have added the class. Can you check and let me know if this is correct?

I'm getting Rubocop warning in the spec file for `let(:doc) { instance_double('CommonMarker doc instance') }` Can you help me?

**Comment by sojan-official** [comment]
Verified in local 
----------

Screenshot 2023-06-14 at 3 36 43 PM

**Pull request merged**
