### PR TITLE
fix: unable to send audio messages on Telegram

### PR DESCRIPTION
**Pull request by giquieu**
# Pull Request Template

## Description

Changed the lib used to record the audio (videojs-record).

Changed the audio recording format to .ogg, this will keep compatibility with sending to channels, Telegram, Whatsapp, Web Widget and API.

Changed the visualization of recording waves, it is now using bars, the same format used by applications (Whatsapp and Telegram)
image

Fixes # (issue)
#4115 

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Audio sent to Web Widget.
Sent audio to Telegram.

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by jtperez2** [comment]
any news here??  :)

**Comment by iamsivin** [comment]
@giquieu Nice work⚡️

@giquieu @sojan-official Tested locally with Chrome browser, working as expected. Found a warning showing in dev tools you can see in loom video `[Deprecation] The ScriptProcessorNode is deprecated. Use AudioWorkletNode instead. (<URL>)`

https://www.loom.com/share/25d6f5c9213e4f6dae32ac888b8b942c

@fayazara Can you also take a look here?

**Comment by giquieu** [comment]
@iamsivin ty

I was checking the origin of the warning, it's coming from wavesurfer. When it instantiates microphone management.
There is an issue in the project (https://github.com/katspaugh/wavesurfer.js/issues/1281) that is dealing with the use of AudioWorkletNode.

The ScriptProcessorNode is compatible with all modern browsers:
https://developer.mozilla.org/en-US/docs/Web/API/ScriptProcessorNode#browser_compatibility
Some AudioWorkletNode functions are still incompatible:
https://developer.mozilla.org/en-US/docs/Web/API/AudioWorkletNode#browser_compatibility

I'm following the development of wavesurfer.js and issue #1281.
I hope the PR is approved and in the near future, with news from #1281, I can update to eliminate the warning.

**Comment by sojan-official** [comment]
@giquieu sounds good to me.  let's get to it when https://github.com/katspaugh/wavesurfer.js/issues/1281 is addressed.  
The team will do a final round of QA and get this merged. 

Thanks a lot again for the efforts.

**Review by iamsivin — APPROVED** [review]
@sojan-official @pranavrajs @fayazara Can we merge this? LGTM

**Review by fayazara — APPROVED** [review]
Tested locally, works perfectly!

**Comment by jtperez2** [comment]
we updated to the release v2.5.0 which includes this fix, but still is sending wav instead of ogg.
Channel: Whatsapp by Twlio
Storage: S3
Is there something else to do in order to make it work??

Thanks team!

**Comment by giquieu** [comment]
Hi,
@jtperez2 
I just did a test with my Twilio trial account. I was able to send and receive audio messages.

Could you check the Twilio Monitor if there is anything relevant?
The Chatwoot log could also give some clues.

Check if the request is being sent, for example:
filename=1652842460576.oga (1652842460576 is name of file)
Content-Type: audio/ogg

**Comment by jtperez2** [comment]
Thanks for your answer @giquieu !
I've tried creating again the whatsapp inbox and the matter continues.
We are going to try a fresh install.

**Comment by jtperez2** [comment]
After a fresh install now we have the following error:
image
Any ideas??

Thanks!

**Comment by jtperez2** [comment]
After a fresh install it worked!!

**Pull request merged**
