### PR TITLE
Feature: Add catalan (Catalonia) language

### PR DESCRIPTION
**Pull request by fv3rdugo**
# Pull Request Template

## Description
Add catalan (Catalonia) language to the project. Adapting the expressions to Catalan and using inclusive language.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?
Not yet.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by sojan-official** [comment]
@fv3rdugo thanks a lot for looking into this. could you also help us with the frontend translations?  The dashboard uses the language files in  the directory `app/javascript/dashboard/i18n/locale` 

https://github.com/chatwoot/chatwoot/tree/develop/app/javascript/dashboard/i18n/locale

you could make a  copy of the en folder, rename it to catalan.  and change the values for English keys. . Meanwhile, we will add settings for Catalan into the backend.

**Comment by pranavrajs** [comment]
@fv3rdugo I just added a couple of missing words and issues with the file. Thanks for this work. Everything looks great. ❤️ Here are some screenshots.

Screenshot 2020-04-16 at 3 17 07 PM

Screenshot 2020-04-16 at 3 17 25 PM

**Comment by pranavrajs** [comment]
We will use translate.chatwoot.com for any further changes in the translation files. :)

**Comment by fv3rdugo** [comment]
I see some minor translation errors. Maybe it's better to do it from https://translate.chatwoot.com?

**Comment by pranavrajs** [comment]
@fv3rdugo Yes, that would be ideal.

**Comment by fv3rdugo** [comment]
Hi, 
I want to change the _Conversacions_ word located here app/javascript/dashboard/i18n/ca.js but this strings aren't in Crowdin.

**Comment by pranavrajs** [comment]
I think we added that to no-ignore list, will update it now.

**Pull request merged**
