### PR TITLE
feat: Ability to lock to single conversation

### PR DESCRIPTION
**Pull request by sojan-official**
Adds the ability to lock conversation to a single thread for Whatsapp and Sms Inboxes when using outbound messages.
demo: https://www.loom.com/share/c9e1e563c8914837a4139dfdd2503fef

fixes: #4975

### CODE REVIEW

**Comment by sojan-official** [comment]
Todo 
- [ ] fix Contact conversations duplicating when lock to the single conversation is enabled, and an agent creates a new conversation from the Contact page -> expand contact into sidebar -> new conversation button

**Review by fayazara — COMMENTED** [review]
@sojan-official I just tested this, it appended a new message to existing conversation even after I disabled this option in settings.

https://www.loom.com/share/76d5c0b9e5b746b9bfaf256f5ecde2cb

**Comment by fayazara** [comment]
> @sojan-official I just tested this, it appended a new message to existing conversation even after I disabled this option in settings.
> 
> https://www.loom.com/share/76d5c0b9e5b746b9bfaf256f5ecde2cb

Sorry, please ignore this - I didnt click on save inbox button.

**Review by fayazara — APPROVED** [review]
Tested locally. Working as expected

**Pull request merged**
