### PR TITLE
feat: support audio player on widget

### LINKED ISSUE #3603: feat: Support audio player on widget
- Currently the widget does not support audio files like mp3, wav. So end user/visitor on widget has to download it every time to listen to it.
- Our dashboard supports playing audio files, we could use the same for widget also.

### PR DESCRIPTION
**Pull request by giquieu**
# Pull Request Template

## Description

Adds visualization in the form of an audio player inside the Widget.

Fixes #3603
https://github.com/chatwoot/chatwoot/issues/3603

## Type of change

- [X] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Sent an audio type attachment.
Audio recorded.
Attached photo type.
Sent PDF attachment

image

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] My changes generate no new warnings

### CODE REVIEW

**Review by iamsivin — DISMISSED** [review]
LGTM, Tested locally, working as expected.

**Screencast**

https://user-images.githubusercontent.com/64252451/159713029-b7afed50-abfd-4771-bdc2-fb2d587d78ca.mov

**Comment by iamsivin** [comment]
@giquieu Can you fix the code climate issue?

**Review by fayazara — APPROVED** [review]
Lgtm

**Review by muhsin-k — APPROVED** [review]
@giquieu Nice work ❤️

**Pull request merged**
