### PR TITLE
Fix code climate issues on Plan model

### PR DESCRIPTION
**Pull request by jaquesdias**
Fix issue #57

### CODE REVIEW

**Comment by pranavrajs** [comment]
@sojan-official / @subintp Please take a look

**Comment by pranavrajs** [comment]
@jaquesdias Could you please share your details here? We would like to send you a sticker pack for creating the PR to our repo. We will start shipping it by the end of October.

**Comment by jaquesdias** [comment]
@pranavrajs Really? That's awesome!
My Name is Jaques Dias Costa Junior. You can send the sticker pack to:

SenvenD GmbH
Halbmondstraße 2, Heilbronn 74072 - Germany.

Thanks a lot.

**Comment by pranavrajs** [comment]
@jaquesdias Uh! oh. I'm so sorry, I didn't want to make your information public, I missed posting the link to the form. Please feel free to delete the above comment and share your info here https://chatwoot.typeform.com/to/ihG9Gz

**Comment by jaquesdias** [comment]
@pranavrajs no worries. It's done.

**Pull request merged**
