### PR TITLE
feat: Audio Notifications for "Mine and Unassinged Conversations"

### LINKED ISSUE #8675: Audio Notifications for "Assigned and Unassinged Conversations"
### Is your feature or enhancement related to a problem? Please describe.

We dont use "auto assign"

Without an option to enable sound in "Assigned" conversations, the only option is to activate it for "All Conversations"

But agents get very confused if every conversation assigned to other agents sends audio notifications

### Describe the solution you'd like

At /profile/settings adds a new option in "Audio Notifications" for "Assigned and Unassinged Conversations"
image

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Cauen**
closes #8675

image

# Pull Request Template

## Description

This is a very small change, basically i've:
1. Added a new Audio Notification option "mine_and_unassigned".
2. Renamed (UI ONLY) old "Assigned Conversations" to "My Conversations". (In db its already "mine", so dont updated, so this PR dont haves breaking changes)
3. Creted/updated related translations

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update
- Needs small update here: https://www.chatwoot.com/docs/user-guide/features/notifications/

## How Has This Been Tested?

Select the new option, reload screen, and create a new conversation as "Unassigned" or create a message in a "Unassigned" conversation. Audio notification must be triggered.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- Small changes, comments wouldn't fit here
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- Small changes, t wouldestsn't fit here
- [ ] New and existing unit tests pass locally with my changes
- Small changes, t wouldestsn't fit here
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Cauen** [comment]
I did the setup locally, did numerous tests
Everything working as expected

**Comment by Double-Click-ERP** [comment]
+1

**Comment by Cauen** [comment]
Hi @pranavrajs 
Is there anything I can do to help this MR get merged?

**Comment by Double-Click-ERP** [comment]
+1

**Comment by Cauen** [comment]
Created new PR https://github.com/chatwoot/chatwoot/pull/9703 with resolved conflicts

**Comment by Cauen** [comment]
Created new PR https://github.com/chatwoot/chatwoot/pull/9703 with resolved conflicts

**Pull request closed without merging**
