### PR TITLE
fix: Email messages in dark mode

### PR DESCRIPTION
**Pull request by iamsivin**
# Pull Request Template

## Description

This PR will fix email messages in dark mode. Now, we will force `bg-white` and `text-slate-900` color to stay in dark and light mode.

Fixes https://linear.app/chatwoot/issue/CW-2698/design-adjust-colors-in-email-messages-in-dark-mode

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

**Screenshot**

**Before**
image

**After**
image

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by scmmishra** [comment]
@iamsivin let me know when this is ready to review. Also, update the PR desc with a screenshot

**Comment by iamsivin** [comment]
> @iamsivin let me know when this is ready to review. Also, update the PR desc with a screenshot

@scmmishra I will let you know. This change is not reflecting in the email messages. I need to find the best way.

**Comment by scmmishra** [comment]
> > @iamsivin let me know when this is ready to review. Also, update the PR desc with a screenshot
> 
> @scmmishra I will let you know. This change is not reflecting in the email messages. I need to find the best way.

Sure, let me know if you need any help, we can pair on this

**Comment by iamsivin** [comment]
> > > @iamsivin let me know when this is ready to review. Also, update the PR desc with a screenshot
> > 
> > 
> > @scmmishra I will let you know. This change is not reflecting in the email messages. I need to find the best way.
> 
> Sure, let me know if you need any help, we can pair on this

Sure

**Review by scmmishra — COMMENTED** [review]
Works well, but needs work from a design PoV. Right now there is no padding for the text and the border radius is 0, which looks off. 

CC: @absurdiya can you help here

**Review by scmmishra — APPROVED** [review]

**Pull request merged**
