### PR TITLE
feat: New automation actions

### LINKED ISSUE #3951: Automation enhancements
**New events:**

- [ ] Contact Created
- [ ] Contact Updated
- [ ] Label Added
- [ ] Label Removed

**Conditions:**

- [x] #4458
- [x] #4459

**Actions**

- [x] #4015
- [x] #4179

### LINKED ISSUE #4051: Automation Enhancement Actions
Reference - https://github.com/chatwoot/chatwoot/issues/3951

New Actions to add 
 Send the email notification to the team (team_ids as an input)
 Assign to an agent (agent_id as an input in the action)
 Send an email transcript to specified email (email as an input in the action)
 Mute conversation (no input)
 Change status to snooze/resolved (no input)
 Send a webhook event to specified URL (webhook URL as an input in the action)

### PR DESCRIPTION
**Pull request by fayazara**
## Description

Adds new automation events

1. Send the email notification to the team (team_ids as an input)
2. Assign to an agent (agent_id as an input in the action)
3. Send an email transcript to specified email (email as an input in the action)
4. Mute conversation (no input)
5. Change status to snooze/resolved (no input)
6. Send a webhook event to specified URL (webhook URL as an input in the action)

Fixes #4051 

## Type of change

Please delete options that are not relevant.
- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by iamsivin** [comment]
@fayazara  Found a small issue, adding an action eg: Assign a team and select a team, if we change that action with another action the multi-select value is not changing or resetting, you can see in bellow screencast.


https://user-images.githubusercontent.com/64252451/155254105-8fac0e1f-9680-4c8b-932a-b7609909451b.mov

**Comment by fayazara** [comment]
> @fayazara Found a small issue, adding an action eg: Assign a team and select a team, if we change that action with another action the multi-select value is not changing or resetting, you can see in bellow screencast.

@iamsivin fixed this.

**Review by iamsivin — DISMISSED** [review]
LGTM 👍🏻  @nithindavid can you take a look

**Comment by pranavrajs** [comment]
Folks, I guess this is blocked on the backend, please make sure the relevant backend changes are merged to master before merging this PR.

**Review by tejaswinichile — APPROVED** [review]
LGTM 💯

**Review by tejaswinichile — APPROVED** [review]
LGTM

**Pull request merged**
