### PR TITLE
chore: Support for special characters in password

### LINKED ISSUE #2919: chore: Ability to use special characters in password
Problem: When I am signing up for a new chatwoot account, Sometimes the password generated by my password manager isn't accepted by chatwoot which is frustrating. 

Cause: Chatwoot uses https://github.com/ValiMail/devise-secure_password for ensuring the password restrictions. The gem has a specific whitelist of allowed special characters.  This needs to be updated to support: https://owasp.org/www-community/password-special-characters

# Required Changes 
- [x] Propose the change on the original gem repo
- [x] Create a fork and update the safe list of characters. ref: one of the forks contains example changes:  https://github.com/ValiMail/devise-secure_password/compare/master...UnitooTeam:master
- [x] Commit the changes to the original repo if maintainers approve the change 
- [x] Use the fork / updated gem in Chatwoot so that the issue is resolved 

# Acceptance and Testing
- [x] Ability to use passwords generated by various password managers which included special characters ( Dashlane, Lastpass, built-in managers  for chrome, safari, etc )
- [x] Ensure the special characters are compliant with the proposed list.

### PR DESCRIPTION
**Pull request by tejaswinichile**
# Pull Request Template

## Description

Strong password characters included with the new fork here https://github.com/chatwoot/devise-secure_password

Fixes #2919 

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Tested on local with the new password update with the new extra characters.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by muhsin-k** [comment]
I have tested using **1password** suggested password in my local machine and working as expected

https://user-images.githubusercontent.com/12408980/133031891-ba1670ae-79ff-40be-a2ac-74e410a20a23.mov


@sojan-official Could you please check the code changes?

**Comment by muhsin-k** [comment]
@tejaswinichile There are some **rubocop** issues. Could you please look into this?

**Review by sojan-official — APPROVED** [review]
LGTM

**Review by muhsin-k — APPROVED** [review]

**Comment by tejaswinichile** [comment]
@muhsin-k Circle CI has been fixed. @sojan-official This is ready to merge.

**Pull request merged**
