### PR TITLE
feat: Adds the ability to edit article

### PR DESCRIPTION
**Pull request by muhsin-k**
Fixes https://github.com/chatwoot/product/issues/486

### CODE REVIEW

**Comment by iamsivin** [comment]
@muhsin-k Tested it locally and found an issue.
https://www.loom.com/share/998ece06d0fe46f5bdae2ec75aab49b3

**Review by iamsivin — COMMENTED** [review]
@muhsin-k Tested it locally and found an issue.
https://www.loom.com/share/998ece06d0fe46f5bdae2ec75aab49b3

**Comment by muhsin-k** [comment]
> @muhsin-k Tested it locally and found an issue. https://www.loom.com/share/998ece06d0fe46f5bdae2ec75aab49b3

@iamsivin Fixed. Please check now

**Review by iamsivin — APPROVED** [review]
Tested LGTM. Editing article API call works every 300ms. Working as expected.

**Pull request merged**
