### PR TITLE
feat: Add RTL Support for widget and portal.

### LINKED ISSUE #7407: [CW-2179] RTL Widget
### Is your feature or enhancement related to a problem? Please describe.

I need to use chatwoot Widget in RTL, My website have multilingual english and arabic
en.mywebsite.com  ( LTR )
ar.mywebsite.com  ( RTL )
The current chat widget does not provide proper support for RTL languages. When using the chat widget in an RTL language ( ar.mywebsite.com ) , the text alignment and direction are incorrect, leading to a poor user experience.  I need a tip or trick to customize it if is it possible.

### Describe the solution you'd like

In Widget Builder be an option to define text alignment and direction of Widget contents.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

<sub>[CW-2179](https://linear.app/chatwoot/issue/CW-2179/rtl-widget)</sub>

### PR DESCRIPTION
**Pull request by nawafinity**
# Pull Request Template

## Description

This pull request introduces RTL (Right-To-Left) support to widgets and portals, ensuring compatibility with languages that utilize RTL layouts. It features the introduction of a new `rtlMixin` specifically designed for widgets, alongside updates to the existing `rtlMixin` for the dashboard. This update leverages Tailwind CSS's utility classes for dynamic layout direction based on the `dir` attribute.

e.g.:
```html
<div class="flex rtl:flex-row-reverse">
```

```scss
.example {
    text-align: left;
    [dir='rtl'] & {
        text-align: right;
    }
}
```

 A new Ruby initializer (`~/config/initializers/i18n_extensions.rb`) has been added to automatically set the document language and direction.

Supported languages include:
- `ar` (Arabic)
- `arc` (Aramaic)
- `dv` (Divehi)
- `fa` (Persian)
- `ha` (Hausa)
- `he` (Hebrew)
- `khw` (Khowar)
- `ks` (Kashmiri)
- `ku` (Kurdish)
- `ps` (Pashto)
- `ur` (Urdu)
- `yi` (Yiddish)

Fixes #7407 #7141

## Examples:
| RTL | LTR |
|-----|-----|
| localhost_3000_widget_tests_position=right locale=ar | localhost_3000_widget_tests_position=left locale=en (1) |
| localhost_3000_widget_tests_position=right locale=ar (1) | localhost_3000_widget_tests_position=left locale=en (2) |

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

This feature was tested in a local development environment using unit tests to verify that changes correctly apply RTL styles based on the `dir` attribute. Manual testing was also performed to ensure that widgets and portals render appropriately in supported RTL languages.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by scmmishra — CHANGES_REQUESTED** [review]
Hey @nawafinity I can see that you have made changes to the translation files as well in this PR. It would be great if you could make those changes in a separate PR. Also in case you want to update translations, you can do them here: https://translate.chatwoot.com/

**Comment by hadifarnoud** [comment]
@nawafinity is this ready for test? I could help.


@scmmishra it would've been great to have text direction settings in widget and kb portal. This way I can keep my chatwoot UI in English and have the chat widget correctly set to RTL.

**Comment by nawafinity** [comment]
Hey @scmmishra,

I will make these changes this week and finalize this PR.

@hadifarnoud, it’s almost ready. I’m currently running some tests and preparing to update the branch.

This PR will be finalized as soon as possible.

Thank you,
Nawaf

**Comment by TheMikeyRoss** [comment]
Wonferful, any updates?

**Comment by abehnamfard** [comment]
any news about this issue?

**Comment by pranavrajs** [comment]
@nawafinity I appreciate your effort, but several things, including the build tools and the version of Vue, have been updated since the PR was raised. If you’re still interested, please raise a new PR. I’ll close this for now.

**Pull request closed without merging**
