### PR TITLE
feat: Introduce templated canned responses

### PR DESCRIPTION
**Pull request by heroic**
This will allow us to use dynamic variables in canned responses

Currently supported variables are:
1. requester_name
2. requester_email
3. requester_phone
4. requester_#{any external attribute name}

In the future I plan to make these a bit more namespaced with:
1. conversation.contact.#{name of variables}
2. conversation.assignee.#{name of variables}

fixes: https://github.com/chatwoot/chatwoot/issues/2084

# Pull Request Template

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

## Instructions:

Here's an example that uses normal variables and also custom attributes.

`Hi {{requester_name}}​, You can pay your bill by clicking on the "Pay Now" or "Request Extension" button on the screen when you login. You can also visit the "Profile" section and click on "Pay Now" to pay your bill. You can also visit https://example.com/user/{{requester_external_id}} ​to pay your bill`

In the example, {{requester_name}} is coming from the standard variables and {{requester_external_id}} is automatically created from custom attributes on the contact object.

### CODE REVIEW

**Comment by heroic** [comment]
@nithindavid @tejaswinichile please review

**Comment by nithindavid** [comment]
@heroic Thanks for this PR, Can you include more details on how to add these variables to templates ? WIth a screencast or more documentation?

**Comment by heroic** [comment]
It's quite simple. I've used the same liquid templating engine that was already being used. Here's an example that uses normal variables and also custom attributes.

```
Hi {{requester_name}}​, You can pay your bill by clicking on the "Pay Now" or "Request Extension" button on the screen when you login. You can also visit the "Profile" section and click on "Pay Now" to pay your bill. You can also visit https://example.com/user/{{requester_external_id}} ​to pay your bill
```

In the example, `{{requester_name}}` is coming from the standard variables and `{{requester_external_id}}` is automatically created from custom attributes on the contact object.

**Comment by nithindavid** [comment]
@heroic Makes sense. Can you add the instruction you commented to PR description. Also can you add test cases ?

**Comment by heroic** [comment]
> @heroic Makes sense. Can you add the instruction you commented to PR description. Also can you add test cases ?

Updated the PR. Test cases are something I am not great with, unfortunately.

**Comment by pranavrajs** [comment]
@heroic It is quite hard to test the conditions you had in mind without the test cases. Would it be possible to have basic test cases for `app/controllers/api/v1/accounts/canned_responses_controller.rb`? 

We are happy to help you with this. Let us know if you need any assistance.

**Comment by heroic** [comment]
I'll try somehting, but it will be sometime before I can get back at this.

**Comment by nithindavid** [comment]
@heroic Any luck with this? Let us know if you need help :)

**Comment by heroic** [comment]
@nithindavid Been stuck with a few other things. This is already deployed as a patch on our instance, so haven't had the urgency to get the test cases in. I'm gonna have to spend a few hours to get a primer on how to write tests.

**Comment by ravillagunasekhar** [comment]
@pranavrajs  is this feature rolled out?

**Comment by glauberssoutodossantos** [comment]
@pranavrajs this feature is very interest. Does it out of next chatwoot version?

**Comment by pranavrajs** [comment]
@glauberssoutodossantos @ravillagunasekhar We will prioritize this for the December 15 release.

**Comment by glauberssoutodossantos** [comment]
Thanks @pranavrajs. This will be a very good feature.

**Comment by sojan-official** [comment]
@heroic Thanks again for raising this PR. We have been ideating on this feature for a while and finally have some progress to share. We have taken a slightly different approach, resolving the template variable in the message model itself. This will let us have this functionality across Chatwoot, even in automation, macros etc.  

So we can continue the work over https://github.com/chatwoot/chatwoot/pull/6077 and close this PR.

**Pull request closed without merging**
