### PR TITLE
feat: Hide secondary sidebar in conversations

### PR DESCRIPTION
**Pull request by jacsonsantospht**
## Description

When accessing Conversations, it should display button to hide secondary sidebar

Fixes https://github.com/chatwoot/chatwoot/issues/5360

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

1 - Access Panel Chatwoot
2 - Click Menu Conversations
3 - Click button toggle Secondary Sidebar

Peek 21-11-2022 16-03

## Checklist:

- [x] My code follows the style guidelines of this project

### CODE REVIEW

**Comment by ammaraslam** [comment]
Don't we already have a toggle on top left of the sidebar for this which appears when the browser zoom is set on 125%+?

Another toggle would make UI a bit cluttered.

**Comment by pranavrajs** [comment]
@jacsonsantospht The suggestion from @ammaraslam seems good as the behavior would be consistent across the pages irrespective of whether you are in the conversations screen or the help center module. Let me know what you think.

**Comment by jacsonsantospht** [comment]
Hi @pranavrajs , I'm going to close this PR and open a new one with the current toggle. Thanks @ammaraslam 
Captura de tela de 2022-11-22 16-56-31

**Comment by pranavrajs** [comment]
@jacsonsantospht Works, thanks 👍

**Pull request closed without merging**
