### PR TITLE
fix: [CW-44] don't count private message as first reply

### PR DESCRIPTION
**Pull request by scmmishra**
## Description

Private message would be treated as a valid first reply, this PR fixes that.

Fixes https://github.com/chatwoot/chatwoot/issues/6354

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by tejaswinichile** [comment]
LGTM, just one minor comment.

**Review by tejaswinichile — APPROVED** [review]
LGTM 💯

**Comment by scmmishra** [comment]
copilot:summary

**Comment by scmmishra** [comment]
Merging this PR, ignored a code climate, complexity warning, The function is pretty straightforward to read and for debugging too, breaking into smaller chunks didn't make sense

**Pull request merged**
