### PR TITLE
fix: #7427 - Options/Buttons Interactive messages don't format in web widget

### LINKED ISSUE #7427: Options/Buttons Interactive messages don't format in web widget
### Describe the bug

**Options/Buttons** Interactive messages are not formatting properly in web widget.
I have tried 

### On Web widget:
image
### On CW dashboard:
image

### To Reproduce

1. Create a conversation using web widget
2. Send an interactive message with bold or italics using api
3. It will not format on web widget but it will format on the dashboard

### Expected behavior

Formatted text

### Environment

app.chatwoot.com

### Cloud Provider

None

### Platform

None

### Operating system

_No response_

### Browser and version

_No response_

### Docker (if applicable)

_No response_

### Additional context

v2.18.0
app.chatwoot.com

### PR DESCRIPTION
**Pull request by Jatin-MYST**
## Description

The buttons/options interactive message was not formatting properly on the web widget.
I applied a fix by seeing how formatting was done in regular messages (app/javascript/widget/components/AgentMessageBubble.vue)

Fixes #7427

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

I tested it by deploying an instance of CW on a brand new ubuntu 20.04 VM.
Making my changes. Recompiling all the assets and restarting CW using:
`RAILS_ENV=production rake assets:clean assets:clobber assets:precompile && sudo systemctl restart chatwoot.target`
Then tested the change using the inbuilt 'Open in CodePen' button.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Jatin-MYST** [comment]
@sojan-official Is there anything else I need to do with this PR?

**Comment by pranavrajs** [comment]
@Jatin-MYST Sorry for missing this out. Thanks for the PR. The changes looks good. I will test it out and merge.

**Comment by pranavrajs** [comment]
Working as expected.

Screenshot 2023-08-04 at 4 49 58 PM

**Review by pranavrajs — APPROVED** [review]

**Comment by pranavrajs** [comment]
@Jatin-MYST This looks good, I made some minor changes to cleanup the component for dark mode.

**Pull request merged**
