### PR TITLE
Update .env.example

### PR DESCRIPTION
**Pull request by nikhilmuz**
Added default database name config in example env file

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## How Has This Been Tested?

Fixed non-breaking documentation file so it won't affect the working of the codebase.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by pranavrajs** [comment]
Screenshot 2022-08-03 at 2 19 13 PM

@nikhilmuz Any context on why this was added would be helpful. There is already a default in the database.yml file.

**Comment by nikhilmuz** [comment]
It would be helpful incase someone doesn’t walk through the codebase and
deploy multiple different instances of Chatwoot on a DB using production
docker image just having env file. One can just change sample env with
different DB name and extend production docker image

**Comment by nikhilmuz** [comment]
Yes, the change works. I had a hard time changing the DB parameters for the name yesterday and had to dig deeper into ruby code to figure out the same so at least having params in sample .env makes sense. And for my case, the DB name which I got was as committed but now I realised that's different on different builds. Anyway, I have updated the same.

**Comment by pranavrajs** [comment]
@nikhilmuz Sure, makes sense. Thanks for the contribution. ❤️

**Pull request merged**
