### PR TITLE
refactor: minor code refactoring in accordance with Vue.js best practices

### PR DESCRIPTION
**Pull request by jamesgeorge007**
## Description

Adopt `Vue.js` best practices.

- Made components self-closing.
- Use `Array.includes()` instead of `indexOf()`
- Use directive shorthands to be consistent with the rest of the codebase.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?
N/A

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by pranavrajs** [comment]
@jamesgeorge007 Thanks for the PR. 

> Made components self-closing.

This is good if you are writing react components. I didn't like it to be self-closing in the case of Vue components or raw HTML file. 

I'd like to borrow the below thought process even thought self-closing tags work right now.

https://github.com/vuejs/vue/issues/1036#issuecomment-120634281

> Use Array.includes() instead of indexOf()

Thanks for this.

> Use directive shorthands to be consistent with the rest of the codebase.

Thanks for this as well.

**Comment by jamesgeorge007** [comment]
@pranavrajs self-closing components are strongly recommended in SFC's as from the official style guide [here](https://vuejs.org/v2/style-guide/#Self-closing-components-strongly-recommended)

**Comment by pranavrajs** [comment]
> @pranavrajs self-closing components are strongly recommended in SFC's as from the official style guide here

Yes, I'm aware of this. When we start building this in 2016-17, self-closing was not a popular option. Our codebase has very few self-closed markups. I'm sure about why we should adopt this now and go back and change all the references. If it is about readability, I don't find it in more readable than the existing usage. I'm putting this to the team @nithindavid @sojan-official @sony-mathew whether we should adopt this or not.

**Comment by sojan-official** [comment]
Guys, I think we can mandate the official guideline for the newer PRs and try to refactor the existing code to that style as well. It will be much easier for newer contributors.  

@jamesgeorge007  thanks for bringing up this discussion.

**Pull request merged**
