### PR TITLE
fix: Selected agent profile picture in agent multi select 

### PR DESCRIPTION
**Pull request by wilso199**
# Pull Request Template

## Description

When assigning an agent to a conversation the response from the assignments controller did not contain the appropriate fields to set the user's profile picture. We are now returning the agent partial if an agent is found and nil otherwise.

I also made a slight change to the `onSelfAssign()` method. This method was trying to grab the `thumbnail` property from `this.currentUser` which doesn't exist. This value is stored in `avatar_url`.

Fixes: #2895 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

1. Assigned a profile picture to my agent account.
2. Selected a conversation
3. Assigned an agent to the conversation
4. Verified the user profile picture exists after being selected

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by pranavrajs** [comment]
@sojan-official @tejaswinichile Can you please review this?

**Review by sojan-official — APPROVED** [review]

**Comment by muhsin-k** [comment]
@wilso199 Thanks for the PR ❤️

**Comment by wilso199** [comment]
@muhsin-k Yup, I will look into that!

**Comment by wilso199** [comment]
@muhsin-k I believe the flicker should be fixed now.

When working on this I noticed users'/agents' profile images are listed under two different properties across the project: `thumbnail` and `avatar_url`. The different properties is what caused this bug.

Is it worth trying to use one property value for all profile images? I didn't want to make large changes in this PR since it is a fix, but may be beneficial to standardize a property.

What are your thoughts?

**Comment by muhsin-k** [comment]
> @muhsin-k I believe the flicker should be fixed now.

Tested the changes and it is working as expected
> 
> When working on this I noticed users'/agents' profile images are listed under two different properties across the project: `thumbnail` and `avatar_url`. The different properties are what caused this bug.
> 
> Is it worth trying to use one property value for all profile images? I didn't want to make large changes in this PR since it is a fix, but may be beneficial to standardize a property.
> 
> What are your thoughts?

It was not intentional 😄. We can standardize the property in a separate PR

**Review by muhsin-k — APPROVED** [review]

**Pull request merged**
