### PR TITLE
feat: scroll to replied message

### PR DESCRIPTION
**Pull request by clairton**
Scroll to replied message on click

### CODE REVIEW

**Comment by clairton** [comment]
https://github.com/chatwoot/chatwoot/assets/471685/e12e1b48-27a0-48b5-9d3f-39ddd5df7bd9

**Comment by scmmishra** [comment]
@clairton can you test if this works for a longer conversation where the message is probably not loaded and needs to be fetched?

**Comment by clairton** [comment]
@scmmishra its true, what code would be use to load this messages?

**Comment by pranavrajs** [comment]
@scmmishra Let us merge this and consider the case where the message is unavailable as a separate one.

**Review by pranavrajs — APPROVED** [review]

**Comment by pranavrajs** [comment]
@clairton Thanks for the PR. This is helpful.

**Pull request merged**
