### PR TITLE
Improve I18n for French language

### PR DESCRIPTION
**Pull request by Vadorequest**
# Pull Request Template

## Description

Improved translations for French language.

Discussion at https://discord.com/channels/647412545203994635/722075616169689098/968796083683749938

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Not tested, nothing to be tested. (I suppose?)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by pranavrajs** [comment]
@Vadorequest Can you please follow this guide (https://www.chatwoot.com/docs/contributing-guide/translation-guidelines#translate-strings)? It would be better if these changes are available in Crowdin instead of a PR here.

**Comment by Vadorequest** [comment]
I did since then but honestly if feels pointless to use crowdin, I felt like good proposals weren't applied, and my proposals never got applied either so I'm not participating anymore.

**Comment by Vadorequest** [comment]
I'll try to explain a bit more in-depth then.

Long story short, I felt like my efforts translating things using Crowdin didn't change anything and weren't taken into account. I'm not familiar on how it works and who should review/validate things, but the "efforts ROI" are too low for me to spend any more time into this at this time.

**Comment by pranavrajs** [comment]
There is a workflow for approving the language translations as there are multiple people contributing to it. @sojan-official Can you please share the process here?

**Pull request closed without merging**
