### PR TITLE
feat: SSO Integration

### PR DESCRIPTION
**Pull request by tejaswinichile**
# Pull Request Template

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by matbgn** [comment]
Code looks promising! Although I have a question, why to start with SAML when 2/3 of the protocols asked where OIDC/OAuth related ?

Even more important to me is what does mean:
> However, custom auth providers would not be supported.
From @pranavrajs 

The OIDC would just completely solve that problem as it is an Open Standard noop ?

**Comment by matbgn** [comment]
I can only double the Turtley @github-actions for the relative slow steps taken here. But as every time, we are in open source and it has to go like this. Maybe come back in two or three months 😄 

Maybe a more specific and technical question: What do we have to do here to have at the very basics a workable and mergeable branch? Or at least, what are the macro steps to follow to solve this PR?

**Comment by matbgn** [comment]
@pranavrajs (@tejaswinichile), would a small sponsorship help with this merge request? We are seriously considering replacing Chatwoot with another SSO compatible solution like Zammad for security management concerns. As it would be a huge investment, I'm considering all possible solutions in between.

**Comment by pranavrajs** [comment]
> @pranavrajs (@tejaswinichile), would a small sponsorship help with this merge request? We are seriously considering replacing Chatwoot with another SSO-compatible solution like Zammad for security management concerns. As it would be a huge investment, I'm considering all possible solutions in between.

Which is the SSO provider you are using?

We are working on the SSO in different parts. Gmail Oauth will be released soon. SAML SSO and LDAP will be picked up once that is complete. Just a note, this is an enterprise feature and would not be available in open-source version.

**Comment by matbgn** [comment]
Thanks for the quick answer! We use Keycloak as our SSO provider, so it's clear to me that we need to move away from Chatwoot now. 

SSO is not a "feature" as a systems engineer, it's a security requirement. As a result, we and many others, as you can see here https://github.com/mattermost/focalboard/issues/103, will not give future solutions a chance without it. 

We have been actively "trying out" Chatwoot with our team, and have experienced some understandable problems so far, but without SSO we will not go any further with testing, contributions or financial support. 

Another CEO asked me last week about my confidence in Chatwoot (no cheat) and I told him to wait another 2 months before giving him any feedback due to the issues. But again, I have a quicker answer now.

Thanks again and all the best for the future.

**Comment by alexanderadam** [comment]
> Which is the SSO provider you are using?

Usually an implementation shouldn't be provider dependent, right?
Because people might use just any OIDC Provider like [a selfhosted Authelia](https://www.authelia.com/), [Keycloak](https://www.keycloak.org/), [Authentik](https://goauthentik.io/) or [GitLab](https://docs.gitlab.com/ee/integration/openid_connect_provider.html) or [Nextcloud](https://apps.nextcloud.com/apps/oidc).
OAuth/OpenID Connect is standardized anyway, 

> Just a note, this is an enterprise feature and would not be available in open-source version.

I see. Please consider advertising Chatwoot [on this website](https://sso.tax/) after you released this as an enterprise feature. You can create a Pull Request [over here](https://github.com/robchahin/sso-wall-of-shame).

**Comment by matbgn** [comment]
Even sadder, after 10 days, absolutely no response to our commercial proposal (sent per email to @pranavrajs on 14.02.23) to sponsor the development for the benefit of the community... Even a "no" will be less rude. Feel that #1318 will see no end unfortunately.

The Zammad open source solution (https://github.com/zammad/zammad) is now in our official internal backlog to opperate replacement.

**Comment by pranavrajs** [comment]
@matbgn Just sharing the response I shared with you over the email.


> There are several factors that we take into consideration when we decide whether the feature is enterprise or open-source.
> 
> I appreciate your thought on supporting the development and the efforts to publicize it in FOSDEM. However, the reason is not just about the cost of development. Supporting each SSO implementation requires manual effort from the team as the setup differs, and different configuration options are available. Even slightest misconfiguration would take a couple of hours to debug. Consider this happening to the larger community, and then it becomes our burden to support these. As a small team, these would hinder the progress we make and would take up a lot in terms of the team's bandwidth. 
> 
> As an example, you can see the Facebook/Instagram integration in Chatwoot is relatively straightforward. However, we end up with tons of support requests and Github issues every month. Ultimately it leads to a poor experience for something which we don't have control over.
> 
> This is a tradeoff, and it might not be the best solution out there. However, considering the size of the team and the stage we are in, this seems like the best path forward. Also, I believe that if making SSO paid would churn you from using our open-source version, then it might mean that you don't see enough value in the open-source product. I would definitely go back to the drawing board to see if I can fix that.

**Comment by matbgn** [comment]
Thanks for your reply @pranavrajs, although I don't understand the point of vue. 

OIDC is now an industry standard and therefore it's maintenance will surely cost much less than any Google, Meta, Custom-whatever integration.

Also, you will not be impacting end users, but integrators and sysadmins in case of lack of implementation. In such a case, documentation, which we could also create as a community, will surely cover most of the potential issues.

Also, as a small company, if we have to choose between implementing Apple's custom solution or an industry-wide standard, our choice is now pretty quick. Hopefully this will encourage a new way of thinking.

> it might mean that you don't see enough value in the open-source product

In fact not, but thanks to this response we are holding things up a bit to see what comes out of the drawing board.

**Comment by matbgn** [comment]
As you say say 🐢 it's done we are out since last week (for the moment back to a shared mailbox, still a better experience overall than on Chatwoot sadly)

**Comment by xxXWarMachineRoXxx** [comment]
How about Simplesaml php integration too!

**Comment by TobiasGrether** [comment]
Is this PR being worked on or did this completely go stale?

**Comment by tejaswinichile** [comment]
> Is this PR being worked on or did this completely go stale?

We have changed the priority for this.

**Comment by clairton** [comment]
+1

**Comment by jordan26** [comment]
I also would like to +1 for this, incredibly useful to have SSO and improves security too.

**Comment by umm0n** [comment]
> SSO is not a "feature" as a systems engineer, it's a security requirement.

Just want to reiterate the importance of this. It's very unfortunate that you've locked SSO behind the enterprise plan and hugely detrimental to the security of the product overall. Please, we urge you to reconsider.

**Comment by JackW6809** [comment]
> > SSO is not a "feature" as a systems engineer, it's a security requirement.
> 
> Just want to reiterate the importance of this. It's very unfortunate that you've locked SSO behind the enterprise plan and hugely detrimental to the security of the product overall. Please, we urge you to reconsider.

Wow, that is a huge price. $99/agent/month...

> How about Simplesaml php integration too!

This is definitely possible. If you have somewhere to host it, this could work. I make use of On Prem & Azure AD (1 Azure AD tenant is free if you have an Office 365 subscription or licence for your organization). I can make a custom attribute with the user's ID in it. So the process would be like this.

Let's say my chatwoot is @ https://chatwoot.contoso.com...
I can have https://auth.chatwoot.contoso.com which is just a SimpleSAML service provider. This then redirects to Azure AD and authenticates me. I have a custom attribute of 'chatwootUid' => '5'. Well now back on SimpleSAML since I am now an authenticated user the webserver can make an API call to https://chatwoot.contoso.com/platform/api/v1/users/chatwoodUid/login to create a SSO URL (if that is still possible) which returns a string and make use of it in a header('Location: https://chatwoot.contoso.com/sso/URL').

Not an ideal method but definitely a way to do it for "free" if you already have the resources available. Obviously, AD is not required, you can use your own identity provider. SimpleSAMLPHP is quite a good piece of kit once you get your head around it.

**Comment by pranavrajs** [comment]
Closing this here as this PR has been stale for a while and we don't intend to merge this to open-source edition.

**Pull request closed without merging**
