### PR TITLE
Annotations

### PR DESCRIPTION
**Pull request by mukesh4139**
# Pull Request Template

## Description
This PR adds annotate gem to the project. It will help automatically document all the models and its corresponding factories, fixtures and specs.

This covers #326 #328 

## How Has This Been Tested?
No test required for this.

### CODE REVIEW

**Comment by mukesh4139** [comment]
Can we exclude this file from rubocop? 
Rubocop suggests `Align the elements of a hash literal if they span more than one line.`

I think the readability of the current version is better than the aligned one.

Eg. 

Suggested by Rubocop
```ruby
my_hash = {
    'abc' => 10,
    'def' => 20,
    'ghijklmno' => 30,
    'p' => 40,
    'qrstuvwyxzw' => 50
  }
```

vs
Current Version
```ruby
my_hash = {
    'abc'         => 10,
    'def'         => 20,
    'ghijklmno'   => 30,
    'p'           => 40,
    'qrstuvwyxzw' => 50
  }
```

**Comment by mukesh4139** [comment]
Hey @sojan-official,

Thank you for your comments.
I have a file auto-generated by the gem lib/tasks/auto_annotate_models.rake which contains the configuration for the annotations.

Rubocop raised `Block has too many lines. [45/30]`. 
Could you please suggest a proper way to refactor this?

**Comment by pranavrajs** [comment]
@mukesh4139 I guess if the file is autogenerated, it can be added to the ignore list on rubocop. @sojan-official to make a decision on this.

**Comment by sojan-official** [comment]
@mukesh4139  @pranavrajs  I am cool with adding the file to ignore list. otherwise looks good to me.

**Comment by mukesh4139** [comment]
Thank you @sojan-official, @pranavrajs for helping me to out to complete my first Open Source Contribution. :)

**Comment by sojan-official** [comment]
@mukesh4139 The start for a thousand more 😀 🎉

**Pull request merged**
