### PR TITLE
fix: Custom attr filter on conversations

### PR DESCRIPTION
**Pull request by tejaswinichile**
# Pull Request Template

## Description

Custom attribute filter on conversations.

Fixes https://github.com/chatwoot/product/issues/680

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Equal to filter works fine
- Not equal to filter works only if custom attributes are present.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by tejaswinichile** [comment]
https://www.loom.com/share/b900a9b3ec0d48c8a409fd441370020d

**Review by sojan-official — APPROVED** [review]

**Review by pranavrajs — CHANGES_REQUESTED** [review]
The problem still exists. It returns only the conversations with the attribute present. 

To reproduce:

Add a new attribute in custom attributes and apply the Not Equal To filter. The expectation is that it should return all the conversations because none of the conversations have this attribute added to them. The actual result is that it returns empty results.

**Comment by pranavrajs** [comment]
@tejaswinichile Looked at the loom video. I don't get the logic. Whether the custom attributes key is present or not, it should return all the objects which doesn't match the filter.

Here `Not Equal` implies `Not Equal or not present.` If the key is not present, it should match.

**Comment by tejaswinichile** [comment]
@pranavrajs Please check the changes with the updated query

https://www.loom.com/share/17d2672a5c0c491b99c41352b6e43416

**Comment by pranavrajs** [comment]
@tejaswinichile Tested this and it works locally now. Nice work. @sojan-official Can you please check the query builder changes and merge this?

**Pull request merged**
