### PR TITLE
hotfix: downgrade to alpine 3.13 as a temporary fix

### PR DESCRIPTION
**Pull request by vishnu-narayanan**
ref: https://github.com/chatwoot/chatwoot/issues/2845

# Pull Request Template

## Description

Downgrade to alpine-3.13 as a temporary fix

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by vishnu-narayanan** [comment]
Do not merge. Keeping this open till the next release.

**Comment by vishnu-narayanan** [comment]
Used to push the `hotfix-v1.19.0` chatwoot image based on `alpine-3.13`.

**Comment by pranavrajs** [comment]
@vishnu-narayanan Do we need to push this to master?

**Comment by vishnu-narayanan** [comment]
@pranavrajs No. The only long-term solution for users having this issue is to update their docker engine and associated components. 

And thus it does not make sense to downgrade our base image to `alpine-3.13` nor support both `3.13` and `3.14`.

Ref: https://github.com/chatwoot/chatwoot/issues/2845#issuecomment-904512984

**Pull request closed without merging**
