### PR TITLE
fix: clean cache to process message again when fail

### PR DESCRIPTION
**Pull request by clairton**
# clean cache to process message again when fail

When message fail delete key process cache

### CODE REVIEW

**Comment by clairton** [comment]
@pranavrajs @sojan-official sorry by mentionate, but this PR is very important!

**Comment by clairton** [comment]
without this fix, some messages is not processed @pranavrajs @sojan-official

**Comment by pranavrajs** [comment]
@clairton Can you please share the case where this breaks? How do I reproduce it?

**Comment by clairton** [comment]
when an error occurs in processing, and the job runs again, it finds the cache and discards the message

**Comment by pranavrajs** [comment]
> when an error occurs in processing, and the job runs again, it finds the cache and discards the message

@clairton I understand this, but where is the error occurring? There are only DB calls in between. Can you share a case where this breaks?

**Pull request closed without merging**
