### PR TITLE
chore: revert arm64 docker build in gh action

### PR DESCRIPTION
**Pull request by vishnu-narayanan**
# Pull Request Template

## Description

`arm64` build is failing at the asset:pre-compile stage. This usually happens due to instance mem/CPU requirements not being met. Reverting this change for now.

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?
- gh action

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by vishnu-narayanan** [comment]
ref: https://github.com/chatwoot/chatwoot/pull/5575

https://github.com/chatwoot/chatwoot/pull/5575#issuecomment-1277208625

**Comment by vishnu-narayanan** [comment]
related: https://github.com/chatwoot/chatwoot/issues/5568

**Comment by marcelstoer** [comment]
I'm the one who provided the initial PR #5545 that enabled it.

When I learned that you reverted it I was first surprised. Looking at https://github.com/chatwoot/chatwoot/actions/runs/3194644842/jobs/5214429525#step:10:3588 and seeing `yarn install` resulting in "There appears to be trouble with your network connection." I expected this to be a glitch, a temporary issue. So, I went back to my PR and checked the build status - it was inconclusive. Some passed, some didn't. Yet, since you still merged it I thought I didn't have to worry about it.

-> I'll make a few more tests with GH Actions in my fork

#2575 should be re-opened I guess.

**Comment by marcelstoer** [comment]
> I'll make a few more tests with GH Actions in my fork

So, there's this issue with Docker Node on emulated hardware: https://github.com/nodejs/docker-node/issues/1335. I verified that the proposed work-around - increasing the Yarn network timeout through `--network-timeout 600000` - does indeed work.

```
#38 [linux/arm64 pre-builder 12/13] RUN if [ "production" = "production" ]; then   SECRET_KEY_BASE=precompile_placeholder RAILS_LOG_TO_STDOUT=enabled bundle exec rake assets:precompile   && rm -rf spec node_modules tmp/cache;   fi
#38 54.76 yarn install v1.22.19
#38 56.50 [1/5] Validating package.json...
#38 56.56 [2/5] Resolving packages...
#38 68.56 [3/5] Fetching packages...
#38 77.66 [4/5] Linking dependencies...
...
#38 119.6 [5/5] Building fresh packages...
#38 120.2 Done in 65.58s.
```
source: https://github.com/marcelstoer/chatwoot/actions/runs/3329510296/jobs/5506819109#step:10:3707

However, the subsequent `rake` task (`rake assets:precompile`) failed with a seg fault: https://github.com/marcelstoer/chatwoot/actions/runs/3329510296/jobs/5506819109#step:10:3752

```
ERROR: failed to solve: process "/bin/sh -c if [ \"$RAILS_ENV\" = \"production\" ]; then   SECRET_KEY_BASE=precompile_placeholder RAILS_LOG_TO_STDOUT=enabled bundle exec rake assets:precompile   && rm -rf spec node_modules tmp/cache;   fi" did not complete successfully: exit code: 134
```

-> not being familiar with this project or Ruby in general means a dead end for me, at least for now

**Comment by vishnu-narayanan** [comment]
> I'm the one who provided the initial PR #5545 that enabled it.
> 
> When I learned that you reverted it I was first surprised. Looking at https://github.com/chatwoot/chatwoot/actions/runs/3194644842/jobs/5214429525#step:10:3588 and seeing `yarn install` resulting in "There appears to be trouble with your network connection." I expected this to be a glitch, a temporary issue. So, I went back to my PR and checked the build status - it was inconclusive. Some passed, some didn't. Yet, since you still merged it I thought I didn't have to worry about it.
> 
> -> I'll make a few more tests with GH Actions in my fork
> 
> #2575 should be re-opened I guess.


@marcelstoer Missed replying to this. It was a minor addition to what we had already in place and I thought it should work this time and went ahead with merging your PR. 

The action started failing completely due to the arm64 stage around `yarn install`. Debugged the issue and found out increasing network timeout could work. As you already saw, after resolving that issue it was failing around the assets compilation stage. This was blocking the docker builds for so long and as such had to revert the PR.

**Comment by vishnu-narayanan** [comment]
> > I'll make a few more tests with GH Actions in my fork
> 
> So, there's this issue with Docker Node on emulated hardware: [nodejs/docker-node#1335](https://github.com/nodejs/docker-node/issues/1335). I verified that the proposed work-around - increasing the Yarn network timeout through `--network-timeout 600000` - does indeed work.
> 
> ```
> #38 [linux/arm64 pre-builder 12/13] RUN if [ "production" = "production" ]; then   SECRET_KEY_BASE=precompile_placeholder RAILS_LOG_TO_STDOUT=enabled bundle exec rake assets:precompile   && rm -rf spec node_modules tmp/cache;   fi
> #38 54.76 yarn install v1.22.19
> #38 56.50 [1/5] Validating package.json...
> #38 56.56 [2/5] Resolving packages...
> #38 68.56 [3/5] Fetching packages...
> #38 77.66 [4/5] Linking dependencies...
> ...
> #38 119.6 [5/5] Building fresh packages...
> #38 120.2 Done in 65.58s.
> ```
> 
> source: https://github.com/marcelstoer/chatwoot/actions/runs/3329510296/jobs/5506819109#step:10:3707
> 
> However, the subsequent `rake` task (`rake assets:precompile`) failed with a seg fault: https://github.com/marcelstoer/chatwoot/actions/runs/3329510296/jobs/5506819109#step:10:3752
> 
> ```
> ERROR: failed to solve: process "/bin/sh -c if [ \"$RAILS_ENV\" = \"production\" ]; then   SECRET_KEY_BASE=precompile_placeholder RAILS_LOG_TO_STDOUT=enabled bundle exec rake assets:precompile   && rm -rf spec node_modules tmp/cache;   fi" did not complete successfully: exit code: 134
> ```
> 
> -> not being familiar with this project or Ruby in general means a dead end for me, at least for now


The asset compilation stage fails with a segmentation fault when the instance runs out of memory. 
Related comment https://github.com/chatwoot/chatwoot/pull/5575#issuecomment-1277208625

I was not able to prioritize debugging why this runs out of memory only for the arm64 stage in the GitHub action runners. It must be the overhead introduced due to virtualization.

**Comment by marcelstoer** [comment]
I continue to investigate here. Maybe this is related to https://github.com/docker/build-push-action/issues/621. 

I will try https://github.com/tgrosinger/hledger-multiarch/commit/83e401677f73d32d872f069d89972bbe7699c009. Also, while certainly convenient, running the asset compilation _inside_ the Docker container(s) somehow does sound like trouble. It'd be faster to do it outside the container and then copy the results into the container. Similar to what was done here https://github.com/eclipse-zenoh/zenoh/pull/294.

**Pull request merged**
