### PR TITLE
fix: AudioContext warning when loading widget on Chrome

### LINKED ISSUE #3930: AudioContext warning when loading Chatwoot widget on Chrome
**Describe the bug**

Any use of chatwoot widget causes a warning in the console on Chrome about AudioContext.

**To Reproduce**

1. Go to https://www.chatwoot.com/
2. Open the console
4. See error: The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu

**Expected behavior**

Chatwoot should not cause a warning.

**Browser logs**

The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu

**Server logs**

N/A

**Environment**

Any installation of the Chatwoot widget.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome
 - Version 98.0.4758.80

**Additional context**

This looks like how Chrome prevents sites from auto-playing with out user interaction. Some relevant threads:

- Auto play policy in Chrome: https://developer.chrome.com/blog/autoplay/#webaudio
- Simple solution: https://www.mattmontag.com/web/unlock-web-audio-in-safari-for-ios-and-macos
- https://github.com/katspaugh/wavesurfer.js/issues/1531

My guess is you need to grab the audio context on click instead on window.onload here https://github.com/chatwoot/chatwoot/blob/9c31d7c672d4f9743ce3a18910d905fe841be7cf/app/javascript/packs/widget.js#L36

### PR DESCRIPTION
**Pull request by iamsivin**
# Pull Request Template

Fixes #3930

## Type of change

- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by pranavrajs** [comment]
@nithindavid Please pair with @iamsivin to get this merged.

**Comment by pranavrajs** [comment]
@nithindavid Please share your findings here.

**Comment by iamsivin** [comment]
Tested it in local work as expected, audio will get activated only when initiating events like `'click', 'touchstart', 'keypress'`.

**Review by fayazara — APPROVED** [review]
Tested locally, working as expected, audio plays after user interaction happens and also chrome does not warn regarding the same.

**Comment by pranavrajs** [comment]
@chatwoot/engineering Let us wait for interim release 2.2.1 before we merge this PR.

**Pull request merged**
