### PR TITLE
DE Widget - 100% Translation

### LINKED ISSUE #307: [Feature] Ability to use chatwoot in local languages
**Is your feature request related to a problem? Please describe.**
- I would like to let my agents use chatwoot in the local language 
- I would like to translate chatwoot completely into my local language

**Describe the solution you'd like**
- language option in agent/account settings so each individual can choose language of choosing
- the organization set to have a particular language as a fallback 

**Describe alternatives you've considered**
N/A

**Additional context**
Ability to onboard users to the software is easier with local language support.

**Road Map**

- Stage 1:  Accounts can have a default language which will be used to translate every aspect related to that account & also the widget

- Stage 2: Accounts can have multiple allowed languages apart from the primary language 
  - if users browser settings give any of the values in the allowed languages, we will show the widget in that language
  - if the language setting doesn't match allowed languages we will fall back to the default language
  - we can also explore doing the same behavior for agent dashboard as well.

- Stage 3:  Agent Setting to Select language from the allowed languages for that account 
  -  If Agent has a language set, the dashboard will be shown in that language else in the default language

### PR DESCRIPTION
**Pull request by DavidSteinbauer**
# Pull Request Template

## Description

The widget is now fully translated into German. Crowdin is already updated. But seems not to be in the latest version.

Fixes #307

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

n/a

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by pranavrajs — APPROVED** [review]

**Comment by DavidSteinbauer** [comment]
@pranavrajs I made an update to the latest chatwoot docker version with [caprover ](https://www.chatwoot.com/docs/deployment/deploy-chatwoot-with-caprover#upgrading-chatwoot-installation) but the de.json is still the old one... 
2021-01-18 at 17 39
 
Whats wrong with docker containers? I dont have a persistent volumen for those to containers!

**Comment by pranavrajs** [comment]
@DavidSteinbauer Did you use the tag latest? or did you specify a version number?

**Comment by DavidSteinbauer** [comment]
@pranavrajs I used `latest`! thats the point!

**Comment by pranavrajs** [comment]
@DavidSteinbauer yeah, `latest` tag would probably be cached so it is advised to use the version number.

**Pull request merged**
