### PR TITLE
feat: Changes theme of labels to smooth

### PR DESCRIPTION
**Pull request by nithindavid**
**After**

image

### CODE REVIEW

**Comment by iamsivin** [comment]
@nithindavid Please fix the codeclimate issue.

**Review by iamsivin — APPROVED** [review]
LGTM

**Comment by pranavrajs** [comment]
@nithindavid Some of the colors are readable, the contrast is too low. Can you update the logic accordingly, please see the screenshot?

|Previous|Current|
|--|--|
| Screenshot 2022-03-30 at 6 07 08 PM | Screenshot 2022-03-30 at 6 06 40 PM |

**Comment by nithindavid** [comment]
image
@pranavrajs Thanks added it.

**Comment by iamsivin** [comment]
@nithindavid Please fix the specs.

**Comment by pranavrajs** [comment]
@nithindavid What are the next steps here?

**Comment by nithindavid** [comment]
Loom video and demo - https://www.loom.com/share/0dde2b67e3cb477c9c36e79781208a02

@pranavrajs @iamsivin @fayazara Can you share your thoughts?

**Comment by fayazara** [comment]
> Loom video and demo - https://www.loom.com/share/0dde2b67e3cb477c9c36e79781208a02
> 
> @pranavrajs @iamsivin @fayazara Can you share your thoughts?

Looks good!

**Review by iamsivin — APPROVED** [review]

**Pull request merged**
