### PR TITLE
Possible change URL for WhatsApp Cloud API

### PR DESCRIPTION
**Pull request by clairton**
##  Whatsapp Cloud API unnoficial option

Add field in form Inbox type Whatsapp Cloud Api with default url to https://graph.facebook.com and a method whatsapp_cloud_api_unofficial? to compare this url to verify if message cloud be send

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

This feature is possible use whatsapp with https://github.com/adiwajshing/Baileys ou any project implementing a whatsapp cloud api layer without error on Whatspp Cloud API Official

### CODE REVIEW

**Comment by smashah** [comment]
I think this is an ample compromise for now thanks @clairton

**Comment by clairton** [comment]
@smashah the implemetation this layer, is not part of chatwoot, but this small changes is chatwoot could help much =)

**Comment by smashah** [comment]
I think the implementation detail should be left to aiddle API layer. Otherwise this PR will only work with Baileys.

**Comment by clairton** [comment]
I use Baileys, but anywhere could implement with another lib, the condition is the rest api format is the same format of request of whatsapp cloud api. And in the chatwoot the only change necessary is a field do put a url, with default value is the graph.face....

**Comment by clairton** [comment]
Hi guys, is everything ok with this PR?

**Comment by viapratica** [comment]
> Hi guys, is everything ok with this PR?

Good Morning!

Do you have the format of responses that Baileys for chatwoot? Because the reverse can the webhook.site. If you can share I would be grateful. camalau@gmail.com

Thanks

**Comment by viapratica** [comment]
> Hi guys, is everything ok with this PR?

It's no use, I tried making the changes in the code and nothing changed and I tried using your repository and it gave an error.

Thanks

**Comment by clairton** [comment]
Hi
The comunication between baileys and chatwoot with WhatsApp cloud api needs a layer implementation witch translate the baileys format to WhatsApp cloud api format. This PR just change the url to use the unnoficial implemation layer

**Comment by clairton** [comment]
@sojan-official this PR no implement a new feature and not breaking the current funcionality

The unique change is possible change https://graph.facebook.com/ do https://mydomain.com

Captura de Tela 2023-01-18 às 17 12 58

**Comment by smashah** [comment]
This may cause confusion to everyday users. Maybe hide the extra config behind an advanced toggle?

**Comment by clairton** [comment]
> This may cause confusion to everyday users. Maybe hide the extra config behind an advanced toggle?

Captura de Tela 2023-02-10 às 09 49 31
Captura de Tela 2023-02-10 às 09 49 36

**Comment by clairton** [comment]
> > Hi guys, is everything ok with this PR?
> 
> Good Morning!
> 
> Do you have the format of responses that Baileys for chatwoot? Because the reverse can the webhook.site. If you can share I would be grateful. [camalau@gmail.com](mailto:camalau@gmail.com)
> 
> Thanks

This is a WIP yet

https://github.com/clairton/baileys-cloud-api

**Comment by clairton** [comment]
WIP project to integrate https://github.com/clairton/baileys-cloud-api

**Comment by scmmishra** [comment]
Hey @clairton, thanks for the contribution. At the moment, this change does not exactly fit our product vision, but there's certainly some interest in the community about this, as evident by the PR, so it makes sense to allow Chatwoot users to change this. 

However, having this available within the UI as a configuration does burden the project's maintainers and also impacts the UX of the product by exposing a configuration in the UI that is not relevant to most of the users; I suggest allowing this to be an installation-level configuration injected via environment variables. We have already done something similar here: https://github.com/chatwoot/chatwoot/blob/9c9183a35214f0ddbb7aa425178672335c049a3b/app/services/whatsapp/providers/whatsapp_360_dialog_service.rb#L52

Let us know what you think of it!

**Comment by clairton** [comment]
Awesome! I open new PR #6622

**Comment by sojan-official** [comment]
@clairton Thanks for the update. Closing this in favour of #6622

**Pull request closed without merging**
