### PR TITLE
chore: Customises emails to add context about inbox and origin

### LINKED ISSUE #3732: [CW-362] Email customization
> Is it possible to customize the email notification our users receive? We had one customer who didn't know who the notification was for, as there is no indication.

**Todo:** 

- [ ] Add Inbox name in the email content.
- [ ] Update the email copy.

 

<sub>[CW-362](https://linear.app/chatwoot/issue/CW-362/email-customization)</sub>

### PR DESCRIPTION
**Pull request by nithindavid**
fixes #3732

### CODE REVIEW

**Comment by pranavrajs** [comment]
@tejaswinichile Can you please assist @nithindavid to get this PR merged?

**Comment by tejaswinichile** [comment]
Let me fix and add the test cases for the same.

**Comment by nithindavid** [comment]
@tejaswinichile I got this error in console. Can you help me add them

`ActionView::Template::Error: undefined local variable or method `account' `

**Comment by sojan-official** [comment]
Moving to on hold cause of following: 

- [ ] further product discussions
- [ ] content changes
- [ ] font changes

**Comment by pranavrajs** [comment]
Closing this in favour of the work done with @Hricha-Shandily to update the email templates.

**Pull request closed without merging**
