### PR TITLE
feat: Placeholder for image attachments in conversations view [CW-3087]

### PR DESCRIPTION
**Pull request by nithindavid**
## Description
On conversation page, the scroll jumps on load as image attachments get loaded. This causes an unpleasant experience.

With the metadata of attachments we could show a placeholder of same size while the image is loading. This prevents the 
UI jump

<details><summary>Loom</summary>
<p>

https://www.loom.com/share/7cbb33251d75454aa3061f022b873270?sid=9c0c91ae-91a8-4345-8e69-11a68df8c150

</p>
</details> 

## Final Preview

https://github.com/chatwoot/chatwoot/assets/18097732/960c4f8d-2dc8-4ba5-8544-22a2fce145c4

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code

### CODE REVIEW

**Comment by pranavrajs** [comment]
@nithindavid This is a good improvements. Let us test this out properly before getting it to merge.

**Comment by nithindavid** [comment]
@pranavrajs I have added a loom video, There's small jump still happening on first load. The view scrolls to top of last message.

**Review by scmmishra — COMMENTED** [review]
Managed to drastically simplify the code. We didn't need a placeholder, just setting the `width` and `height` is enough for the browser to handle the dimensions correctly preventing any layout shift

Ref: [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#:~:text=Use%20both%20width%20and%20height%20to%20set%20the%20intrinsic%20size%20of%20the%20image%2C%20allowing%20it%20to%20take%20up%20space%20before%20it%20loads%2C%20to%20mitigate%20content%20layout%20shifts.)

**Comment by scmmishra** [comment]
@pranavrajs PTAL at the updated video from staging, it's good to go!

**Review by pranavrajs — APPROVED** [review]

**Pull request merged**
