### PR TITLE
fix: telegram send audio messages

### LINKED ISSUE #8499: Telegram - Unable to Send Audio Clips from Agent Side
### Describe the bug

Currently, within the Telegram channel integration, agents are experiencing difficulties sending audio messages. Despite successful attempts to send audio clips from the agent side, users are not receiving these messages in their Telegram inbox.

### To Reproduce

1. Access the Chatwoot platform with a Telegram channel integrated.
2. Navigate to the agent interface.
3. Attempt to send an audio message to a user through the Telegram channel.
4. Verify that the audio message is sent successfully from the agent side.
5. Check the user's Telegram inbox to confirm that the audio message is not received.

### Expected behavior

Audio messages sent by agents through the Telegram channel should be successfully delivered to users' Telegram inboxes, allowing for seamless communication.

### Environment

app.chatwoot.com

### Cloud Provider

None

### Platform

Browser

### Operating system

ubuntu 20.04

### Browser and version

Chrome 93

### Docker (if applicable)

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by mazenkhalil**
Fixes #8499

### CODE REVIEW

**Comment by amaljosea** [comment]
Can you please look into this? 

@nithindavid @pranavrajs

**Comment by pranavrajs** [comment]
Confirmed that the fix works. wav files are not accepted in the Telegram API. We will need to do more investigation on the file each channel accept and disable the ones that cannot be sent.

**Review by pranavrajs — APPROVED** [review]

**Comment by pranavrajs** [comment]
@mazenkhalil Thanks for the PR. @amaljosea Thanks for the followup here. ❤️

**Comment by amaljosea** [comment]
Thanks @pranavrajs for the quick support.

Any idea on when this will be released?

**Comment by amaljosea** [comment]
It is available now in production, thanks.

**Pull request merged**
