### PR TITLE
fix: fetch only unread emails

### PR DESCRIPTION
**Pull request by sajangupta74**
# Pull Request Template

## Description

Please include a summary of the change and issue(s) fixed. Also, mention relevant motivation, context, and any dependencies that this change requires.
Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by tejaswinichile** [comment]
@sajangupta74 Hey I will have it tested today and get back to you with the next steps.

**Comment by tejaswinichile** [comment]
This works fine, but one copy should be in the chatwoot dashboard.

As inbox is shared between agents, and they are handling customer support queries from the dashboard, then anyone who doesn't have access to emails but access to inbox should be able to respond to the conversation.

cc @pranavrajs @sojan-official what do you guys think?

**Comment by sajangupta74** [comment]
> This works fine, but I think one copy should be in the chatwoot dashboard even if it's read email.
> 
> As inbox is shared between agents, and they are handling customer support queries from the dashboard, then anyone who doesn't have access to emails but access to inbox should be able to respond to the conversation.
> 
> cc @pranavrajs @sojan-official what do you guys think?

@tejaswinichile anyone having access to inbox can reply to the email. As this change only reads unread emails, read emails will be in the inbox so the user having access can reply from inbox as well

**Comment by tejaswinichile** [comment]
@sajangupta74 

I tested this scenario:

1. User sent an email to inbox-email
2. I(suppose super-admin) opened inbox email from the email dashboard, not the chatwoot dashboard
3. So that particular email doesn't reach to chatwoot inbox because it gets filtered out with the NOT SEEN key

We don't want this particular behavior.

**Comment by tejaswinichile** [comment]
https://www.loom.com/share/40781dfcd8d4423c9216f64f2bcba9d1

This is the behavior that is wrong and not expected from the customers as well as the agents.

**Comment by sajangupta74** [comment]
yep that's right, consider following scenario:
we had an issue in our environment where in tickets were not getting processed into chatwoot dashboard, if this issue continue for significant amount of time then what happens is there will be 1000s of unproccessed emails. After fixing the issue what happened is latest 10 emails was processed but remaining 1000s - 10 were not getting processed as the worker fetches latest 10 emails only. 

So its a tradeoff where in we supposed no one would open email from inbox(that's more likely) and whenever similar prod issue happens then all unprocessed emails will be processed automatically(no intervention of developer required).

**Comment by tejaswinichile** [comment]
@sajangupta74 This is a very specific issue with your specific instance; in this case, you can raise the count to 100 or 1000 to fetch the last 1000 emails may be in batches if you have that large amount of emails. The contribution PR should keep up with the existing functionality.

If you want our repo should have this change may add some installation config which would ask client if they are ready for this tradeoff, if the installation config is true then only add this key filter.

Otherwise, As of now, we can't merge this PR.

**Comment by pranavrajs** [comment]
>  we had an issue in our environment where in tickets were not getting processed into chatwoot dashboard, if this issue continue for significant amount of time then what happens is there will be 1000s of unproccessed emails. After fixing the issue what happened is latest 10 emails was processed but remaining 1000s - 10 were not getting processed as the worker fetches latest 10 emails only.

@tejaswinichile @sajangupta74 I believe this is a valid case and should have a fix. We can discuss this separately. The idea of the email channel with Chatwoot is that should work similarly to the regular email clients. So, the point @tejaswinichile made still exists. If someone accidentally opens the email, it will not be available in Chatwoot, which leads to an inconsistent state which is hard to debug.

**Comment by tejaswinichile** [comment]
@sajangupta74 Can you add this as a GitHub issue?

**Comment by tejaswinichile** [comment]
@sajangupta74 Please mention this PR there so we can come up with a solution by considering the comments on this PR and please close this PR.

**Pull request closed without merging**
