### PR TITLE
Fix: html mail fix with html_body content

### PR DESCRIPTION
**Pull request by tejaswinichile**
RCA:

Mail had content-type : text/Html
Mail.html_part and mail.parts was empty

In that case, we considered the raw text body but from this fix, if only HTML content is present then we are considering raw HTML mail body too.

This fix fixes all the HTML type email

The previous PR that we closed, I had introduced refactoring of code there which apparently didn't work for some mail types which I removed from here.

### CODE REVIEW

**Comment by tejaswinichile** [comment]
QA checklist

- [ ] 1. Only text email with email.parts not present
- [ ] 2. Only HTML email(fix is related to this issue) with mail.parts not present
- [ ] 3. Text email with email.parts present
- [ ] 4. Html email with mail.parts present
- [ ] 5. Multipart email with only attachments
- [ ] 6. Multipart email with text and attachments
- [ ] 7. Multipart email with HTML mail and attachments

**Review by sojan-official — DISMISSED** [review]

**Comment by tejaswinichile** [comment]
1. text/plain
2. text/HTML
3. multipart/alternative
4. text/plain and text/HTML [Here mail.parts is available]
5.

**Comment by tejaswinichile** [comment]
@pranavrajs @sojan-official Please have a look at the above notes and let me know your feedback so I will merge this today.

**Comment by pranavrajs** [comment]
@tejaswinichile The comment looks good ahead. Let us get this merged.

**Review by pranavrajs — APPROVED** [review]

**Comment by sojan-official** [comment]
ref: https://github.com/chatwoot/chatwoot/issues/1063

**Pull request merged**
