### PR TITLE
chore: upgrade ruby to 3.1.3

### PR DESCRIPTION
**Pull request by vishnu-narayanan**
# Pull Request Template

## Description

- Upgrade ruby version from 3.0.4 to 3.1.3
- This change would enable us to use the latest heroku-22 stack

Fixes https://github.com/chatwoot/product/issues/594

## Type of change

Please delete options that are not relevant.

- [x] Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [x] This change requires a documentation update

## How Has This Been Tested?

- PR checks
- Tested on a self hosted installation

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by vishnu-narayanan** [comment]
```
Run bundle exec rake db:create
You don't have net-smtp installed in your application. Please add it to your Gemfile and run bundle install
rake aborted!
LoadError: cannot load such file -- net/smtp
```

**Comment by sojan-official** [comment]
@vishnu-narayanan  The circle builds are a success for this now. Should we upgrade the version for cwctl as well on this PR / or take it as a separate issue ?

Also, in case of cwctl how do we handle the upgrade process?

**Comment by vishnu-narayanan** [comment]
@sojan-official 

> @vishnu-narayanan The circle builds are a success for this now. Should we upgrade the version for cwctl as well on this PR / or take it as a separate issue ?
`cwctl` will not need any changes.

Also, in the case of cwctl how do we handle the upgrade process?
`cwctl` will read the `.ruby-version` and upgrade the ruby if needed. No change is required here.

 >   might as well upgrade to 3.1.3 over this PR
+1

**Comment by sojan-official** [comment]
We can directly go for 3.2 :D  https://www.ruby-lang.org/en/news/2022/12/25/ruby-3-2-0-released/

**Comment by vishnu-narayanan** [comment]
Facing some issues with ruby 3.2.0. Upgrading to 3.1.3 for now.

**Comment by vishnu-narayanan** [comment]
Docker build fails with error log
```
2023-01-11T08:06:42Z #20 31.89 Error: error:0308010C:digital envelope routines::unsupported
2023-01-11T08:06:42Z #20 31.89 at new Hash (node:internal/crypto/hash:71:19)
2023-01-11T08:06:42Z #20 31.89 at Object.createHash (node:crypto:133:10)
2023-01-11T08:06:42Z #20 31.89 at module.exports (/app/node_modules/webpack/lib/util/createHash.js:135:53)
2023-01-11T08:06:42Z #20 31.89 at NormalModule._initBuildHash (/app/node_modules/webpack/lib/NormalModule.js:417:16)
2023-01-11T08:06:42Z #20 31.89 at /app/node_modules/webpack/lib/NormalModule.js:452:10
2023-01-11T08:06:42Z #20 31.89 at /app/node_modules/webpack/lib/NormalModule.js:323:13
2023-01-11T08:06:42Z #20 31.89 at /app/node_modules/loader-runner/lib/LoaderRunner.js:367:11
2023-01-11T08:06:42Z #20 31.89 at /app/node_modules/loader-runner/lib/LoaderRunner.js:233:18
2023-01-11T08:06:42Z #20 31.89 at context.callback (/app/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
2023-01-11T08:06:42Z #20 31.89 at /app/node_modules/babel-loader/lib/index.js:59:103 {
2023-01-11T08:06:42Z #20 31.89 opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
2023-01-11T08:06:42Z #20 31.89 library: 'digital envelope routines',
2023-01-11T08:06:42Z #20 31.89 reason: 'unsupported',
2023-01-11T08:06:42Z #20 31.89 code: 'ERR_OSSL_EVP_UNSUPPORTED'
2023-01-11T08:06:42Z #20 31.89 }
```

**Comment by vishnu-narayanan** [comment]
Starting with Node 17, nodejs switched to OpenSSL3. The docker builds are installing node18.xx with `alpine-3.1.3`.

From [Node.js 17's announcement post](https://medium.com/the-node-js-collection/node-js-17-is-here-8dba1e14e382#5f07):

>If you hit an ERR_OSSL_EVP_UNSUPPORTED error in your application with Node.js 17, it’s likely that your application or a module you’re using is attempting to use an algorithm or key size which is no longer allowed by default with OpenSSL 3.0. A new [command-line option](https://nodejs.org/api/cli.html#--openssl-legacy-provider), --openssl-legacy-provider, has been added to revert to the legacy provider as a temporary workaround for these tightened restrictions.

Looks like a `webpack` issue. This is fixed in `webpacl` `5+` and we are on `webpack4` at the moment.

Solutions
-----
1. Upgrade webpack.
2. Pin nodejs version to be 16.x.x
3. Use ` --openssl-legacy-provider` as a workaround. 


cc: @sojan-official @pranavrajs

**Comment by vishnu-narayanan** [comment]
https://github.com/webpack/webpack/issues/14532#issuecomment-947515866

**Comment by vishnu-narayanan** [comment]
https://github.com/vuejs/vue-cli/issues/6770

**Comment by vishnu-narayanan** [comment]
https://stackoverflow.com/questions/69665222/node-js-17-0-1-gatsby-error-digital-envelope-routinesunsupported-err-os

**Comment by pranavrajs** [comment]
@scmmishra Please take a look at this thread.

**Comment by scmmishra** [comment]
The effort in upgrading webpack might not be trivial, we should definitely do that. In the interim, the quickest solution is to pin the node version to 16. 

Using the flag should not be a problem either because node 16 still uses the old version of openSSL, which was released in v17 [here](https://medium.com/the-node-js-collection/node-js-17-is-here-8dba1e14e382#5f07). So either way we will be using the legacy version with or without pinning.

My suggestion is to pin the version, that will ensure predictability given we have been using the version so far, we can then take upgrading webpack after that. 

##### On upgrading webpack

Vue.js 2 is generally compatible with Webpack 5, as Vue's template compiler and runtime does not have a direct dependency on Webpack itself. The only concern will be all the webpack plugins what we use and the ones vue-cli brings in.

**Comment by sojan-official** [comment]
note: make sure to update the reference to the node version across the repo, like cwctl etc. also ensure that we have a pathway to upgrade node version in those installations

**Comment by vishnu-narayanan** [comment]
Pinning node version to `16.x` for now.

cc: @sojan-official @scmmishra

**Comment by vishnu-narayanan** [comment]
>note: make sure to update the reference to the node version across the repo, like cwctl etc. also ensure that we have a pathway to upgrade node version in those installations

@sojan-official Will take this up as a separate issue. Currently, the node version is different between docker(16.x.x) and linux(12.x.x) installations.

Also, is a `node` update mandatory for existing installations as part of the chatwoot upgrade?

**Comment by sojan-official** [comment]
@vishnu-narayanan  would help stay consistent everywhere. There might be differences in support for packages.

**Comment by vishnu-narayanan** [comment]
CE spec GitHub actions and docker image builds are passing. CircleCI is failing, though. Circle does not have a `3.1.3-browser` image with nodev16.x.


Tests are passing locally with `node v18.x`, which CircleCI is using. 
```
➜  chatwoot git:(feat/upgrade_ruby) node -v
v18.13.0
➜  chatwoot git:(feat/upgrade_ruby) rspec ./spec/controllers/super_admin/installation_configs_controller_spec.rb:34
Run options: include {:locations=>{"./spec/controllers/super_admin/installation_configs_controller_spec.rb"=>[34]}}
.

Finished in 0.83616 seconds (files took 3.48 seconds to load)
1 example, 0 failures

Coverage report generated for RSpec to /Users/vn/Documents/workspace/cw/chatwoot/coverage. 642 / 14130 LOC (4.54%) covered.
```


cc: @sojan-official

**Comment by sojan-official** [comment]
@nithindavid  could you take a look at this build ?

**Comment by vishnu-narayanan** [comment]
@sojan-official Could you please review again?

**Review by sojan-official — APPROVED** [review]

**Pull request merged**
