### PR TITLE
feat: Add additional attributes in `setUser` method

### LINKED ISSUE #3599: feat: company management in widget setUser
I quote from the documentation "Support for additional parameters is in progress."
So here some suggestions.

At the moment with setUser we can use: name, email, phone_number.
It would be nice if the fields company, city, country could be used as parameters of the setUser in the widget.
In particular for the company, there is already an icon displayed (briefcase) when we looked at a contact. So it seems to be an 'important' field but not managed by the setUser.

Todo:

- [ ] Support more parameters in the setUser method.

### PR DESCRIPTION
**Pull request by muhsin-k**
Fixes #3599 

#### How Has This Been Tested?

- Give values `company_name`, `location` and `description` in messenger script

Ex:
```
window.addEventListener('chatwoot:ready', function() {
  window.$chatwoot.setUser('<%= user_id %>', {
    email: 'jane@example.com',
    description:'', // description about the user
    country_code:'' // Two letter country code
    city: '' // City of the user
    social_profiles:{
     twitter:'', // Twitter user name 
     linkedin:'', // LinkedIn user name 
     facebook:'' , // Facebook user name 
   }
  });
})
```
- Load the widget

- Check attributes are showing in conversation side panel

### CODE REVIEW

**Comment by fayazara** [comment]
@muhsin-k 

I added the above data with the SDK, it worked, the data was showing in the contact details, but once I refreshed the page, `/conversations` endpoint throws a 500 error, and the dashboard wont load.

CleanShot 2022-02-17 at 18 52 06

CleanShot 2022-02-17 at 18 54 25

**Comment by fayazara** [comment]
@tejaswinichile as discussed on the call. Adding a `avatar_url` is breaking the `/conversations` and `/contacts` endpoints throw the below error, and this does not open the dashboard home and contacts page.

image

**Comment by sojan-official** [comment]
@fayazara  I have reviewed the backend code and it looks good to me.  
lets sync up if you face the issue with avatar URL again.

**Comment by fayazara** [comment]
> @fayazara I have reviewed the backend code and it looks good to me. lets sync up if you face the issue with avatar URL again.

@sojan-official I am still seeing this issue. Adding avatar URL breaks breaks the dashboard, `/conversations` and `/contacts` throw a error 500.
CleanShot 2022-02-24 at 15 08 05@2x

PS, I will add a error message to display instead of just showing the spinner on the dashboard.

**Review by fayazara — APPROVED** [review]
Did a QA, works as expected.

CleanShot 2022-02-24 at 15 15 45@2x

CleanShot 2022-02-24 at 15 15 58@2x

**Comment by fayazara** [comment]
@pranavrajs 

Found some bugs

1. Works- Added social links, they show up on the contacts, conversations page.
2. Works - Added company name
3. Works - Added city and country code - show the correct flag beside City name.
4. Failed - Adding any random url to social links just appends it the respective social medias root url. 
CleanShot 2022-02-24 at 15 27 07@2x
5. Failed - Github profile is not gettign added. 
6. Failed - Adding description, but not sure where this is being shown the dashboard, cannot see it anywhere.
7. Failed - Adding a random Country code, breaks the contact details page, needs validation on frontend as well as backend.
CleanShot 2022-02-24 at 15 47 32@2x
8. Failed - Not related to this PR, but there's no validation to emails from SDK and it saves any random string and shows  the same in our contact/conversation panel.

Doing this - 
```javascript
window.$chatwoot.setUser('hmacstring', {
  email: 'hsabdfjhsbdfjdf'
});
```
will save the email in chatwoot
CleanShot 2022-02-24 at 15 40 52@2x

**Comment by muhsin-k** [comment]
@fayazara 
> 
> Found some bugs
> 
> 5. Failed - Github profile is not gettign added.

Currently, there is no option for view/edit GitHub URL, so removing from SDK too. Will create a separate issue for this.

> 6. Failed - Adding description, but not sure where this is being shown the dashboard, cannot see it anywhere.

I can see that description is adding properly in conversation side panel in your previous QA.

> 7. Failed - Adding a random Country code, breaks the contact details page, needs validation on frontend as well as backend.

Created a separate issue for this https://github.com/chatwoot/chatwoot/issues/4077

**Pull request merged**
