### PR TITLE
feat: Ability to send voice message to channel

### PR DESCRIPTION
**Pull request by giquieu**
# Feat/1973 ability to send voice message to channel

## Description

Created the possibility to send audio as an attachment via dashboard.
The channels that can send audio are the same channels that can send any type of attachment.
Used RecordRTC (https://github.com/muaz-khan/RecordRTC) to capture the audio and Wavesurfer (https://github.com/katspaugh/wavesurfer.js) to display the audio waves.
RecordRTC can be used to record videos if necessary.

Fixes # (issue)
Feat/1973

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Pressing the record button and send as an attachment message.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by sojan-official** [comment]
@fayazara  Could you also take a look at this PR?

**Comment by fayazara** [comment]
> @fayazara Could you also take a look at this PR?

Testing this.

**Comment by iamsivin** [comment]
Tested it locally, working as expected, found a small issue throwing a console error when we click the stop button, can see in the screencast.


https://user-images.githubusercontent.com/64252451/156183614-6cc8d8ff-4f33-41c9-844c-e44655f569c8.mov

**Comment by giquieu** [comment]
@iamsivin Ty, I can solve this.

**Comment by giquieu** [comment]
I sent the fix for the case that @iamsivin reported.

**Comment by iamsivin** [comment]
@sojan-official The issue that I have been mentioned is solved and the code LGTM. @fayazara can you also take a look.

**Comment by fayazara** [comment]
Tested this locally, works really well. Awesone job @giquieu 💯 

@sojan-official I do have one question, on the receivers end in the web widget, shouldn't this be played instead of showing the audio as a attachment they have to download?

CleanShot 2022-03-04 at 12 40 24

**Comment by giquieu** [comment]
Ty @fayazara,
About the audio player inside the Widget, there is the issue:
https://github.com/chatwoot/chatwoot/issues/3603
I can take it too.

**Comment by sojan-official** [comment]
@giquieu  thanks a lot. please feel free to pick it up. 
@fayazara  let's take it up as a separate issue.

**Pull request merged**
