### PR TITLE
feat: Revamps editor for message and article

### PR DESCRIPTION
**Pull request by nithindavid**
## Description

This PR introduces separate editors for the message reply box and article editor in the help center.  With support for keyboard rules to trigger formatting marks like bold, italics, code, lists etc. 

Will update list of new changes introduced as a doc, meanwhile please see the comment on test cases.

**Introduces new icons on the menu**
image

**Improves UI for canned response selector**
image

**Loom video for message editor**:  https://www.loom.com/share/10f36094f4b14bf0b48d8c6f9ca17a3d
**Loom video for article editor**:  https://www.loom.com/share/6dea1e175a384bc39e1e69b9e0a92645

**Notes while testing**
- Most of the changes are introduced to core editor schema here https://github.com/chatwoot/prosemirror-schema/pull/5, - Please do `yarn install --force` 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [x] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by nithindavid** [comment]
### Cases tested on Message Editor

**Menu**
[] All menu items toggles the correct marks [Bold, italics, Code, Link]
[] Menu shows active state correctly
[] Undo redo works correctly
[] Can Add ul, ol through menu
[] Ul, Ol icons gets hidden on first item of a menu
[] Can nest lists inside lists from second item
[] Can add a link on highlighted text

**Keyboard Shortcuts**
[] Wrapping inside \*\*stars\*\* transforms text into bold
[] Wrapping inside \*stars\* transforms text into italics
[] Wrapping inside \`stars\` transforms text into code
[] **\* and space** to start unordered list
[] **1. and space** to start ordered list

**Existing behavior**
[] Enter to send and Cmd+enter works correctly to send message
[] Shift+enter does soft break from current line
[] Can paste content into editor
[] Can insert Emoji
[] Typing **\\** shows canned response menu
[] Typing text after **\\** filters content in canned response menu
[] Typing **@** shows canned response menu
[] Can insert canned response through mouse click
[] Can insert canned response through keyboard navigation 
[] Can insert mention through mouse click
[] Can insert mention through keyboard navigation 
[] Can attach files

**Comment by nithindavid** [comment]
I was able to build the storybook locally, Will fix the build issue here.

image

**Comment by pranavrajs** [comment]
@nithindavid Nice work here! This is a real improvement in the editor. The help center editor feels awesome. 

Some minor suggestions. 

1. Can we avoid the placeholder here?
Screenshot 2023-01-06 at 1 18 12 PM

2. Can we reduce the spacing? It seems a bit much.
Screenshot 2023-01-06 at 1 20 47 PM

**Comment by pranavrajs** [comment]
Also, there is an issue with the code editor. The start of each line is not aligned properly.
Screenshot 2023-01-06 at 1 21 29 PM

**Comment by nithindavid** [comment]
> @nithindavid Nice work here! This is a real improvement in the editor. The help center editor feels awesome.
> 
> Some minor suggestions.
> 
> 1. Can we avoid the placeholder here?
> 
> Screenshot 2023-01-06 at 1 18 12 PM
> 
> 2. Can we reduce the spacing? It seems a bit much.
> 
> Screenshot 2023-01-06 at 1 20 47 PM

@pranavrajs Is spacing issue between the menu and title or the typography?

**Comment by nithindavid** [comment]
@pranavrajs Thanks for the feedback :) I have fixed the comments.

**Review by iamsivin — COMMENTED** [review]
@nithindavid Tested this PR locally and its working as expected. Found an issue,

1. If enter to send is enabled we cannot break the line to new one.
https://www.loom.com/share/30eb69e31992438998586bc011b0b5d9

2. Feels not aligned properly if the first item is not active.
image

**Review by scmmishra — COMMENTED** [review]
Screenshot 2023-01-11 at 5 03 01 PM

The changes mostly look good to me, found this small UI bug. There's no bottom padding in the canned responses list, is it intentional?

**Review by scmmishra — COMMENTED** [review]
Some nitpicks

<details>
<summary>
In the article view for my screensize, the text looks way too big
</summary>
Screenshot 2023-01-11 at 5 14 16 PM
</details>

<details>
<summary>
The title area seems to be resizable, can we disable that?
</summary>


https://user-images.githubusercontent.com/18097732/211799585-81aae7b6-2b07-4243-82d2-53ba28a7e7d6.mov


</details>

<details>
<summary>
In the editor, you can see two scrollbars for some reason, can we fix that?
</summary>


https://user-images.githubusercontent.com/18097732/211799378-9cf5fb8c-78d0-4806-a6c8-759407d518b5.mov

</details>

**Comment by nithindavid** [comment]
@scmmishra @iamsivin Thanks for the review. I'll fix them soon.

> There's no bottom padding in the canned responses list; is it intentional?
I removed the bottom padding so when the list overflows, it'll look like there are items to scroll. I'll add padding for the last item to fix this.

**Comment by nithindavid** [comment]
> Some nitpicks
> 
> In the article view for my screensize, the text looks way too big
> The title area seems to be resizable, can we disable that?
> In the editor, you can see two scrollbars for some reason, can we fix that?

@scmmishra This was done with initial feedback on the old editor to match the typography on the article view page. eg: https://chatwoot.help/hc/handbook/en/engineering/15. The font size is 18px here. Please let me know what you think.

cc:  @pranavrajs

**Comment by pranavrajs** [comment]
> This was done with initial feedback on the old editor to match the typography on the article view page. eg: https://chatwoot.help/hc/handbook/en/engineering/15. The font size is 18px here. Please let me know what you think.

@scmmishra @nithindavid Let us try to match the experience end user is getting so that it doesn't like an entirely different content when the user publishes it.

**Comment by nithindavid** [comment]
@iamsivin @scmmishra I have made the fixes. Can you let me know if this is good to merge?

**Review by iamsivin — APPROVED** [review]
I tested this PR locally and it's working as expected 🔥

**Review by scmmishra — APPROVED** [review]
LGTM!!!

**Review by muhsin-k — APPROVED** [review]

**Pull request merged**
