### PR TITLE
Prefer reply-to over from

### LINKED ISSUE #3834: Support reply-to header in emails? Can make PR
**Is your enhancement request related to a problem? Please describe.**
I recently tried to integrate chatwoot into our systems. We don't actually want real time chat (we don't have capacity to deliver on realtime support, we're a tiny team in an uncommon timezone). But I really love chatwoot as a issue tracking system. It beats all the other open-source products out there.

Our main communication channel is email. I tried integrating the live chat widget, but realized that we can't respond via email later on if the conversation is started in a chat channel, also the customers get disappointed when we can't respond in real time. Then i tried integrating your API, it required a lot of logic and network requests to create or search a contact, conversation, add message etc, and has the same problems as the chat channel.

By far the simplest way to integrate chatwoot, for us, is to have a web-form which sends an email. The FROM header is fixed (we can't spoof a from header from our server), but I can put the customer name and email into the REPLY-TO header. I have made a 2 line change to chatwoot to prefer the reply-to header when parsing an email in the IMAP processor. This way, our systems can send emails in from web-forms, and we can reply via email from within chatwoot. It works really well!

**Describe the solution you'd like**
2 changes are on my mind. Firstly, if you would like, I can make a pull request with my changes to prefer a REPLY-TO header before the FROM header in your email processor.

The other idea, is the ability to reply via email when a conversation is started in a chat or api channel, and I'm wondering what you think about that.

Thanks so much for this great product!

### PR DESCRIPTION
**Pull request by robguthrie**
# Pull Request Template

## Description

This change tells chatwoot to obtain the email contact information from the reply-to header before the from header. Fixes #3834 

In practice, for us, this means we can have a web-form which sends emails on behalf of users, by putting their contact info into the reply-to header.

This is our main sales and support inquiry pattern, and all our support is then continued over email.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

We're running this change on our chatwoot install, for 3 or 4 days now, and have had about 30 tickets come through successfully so far.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by pranavrajs** [comment]
@sojan-official @tejaswinichile Can you please take this up from here and get this ready for a merge for the current release?

**Comment by tejaswinichile** [comment]
@pranavrajs I will add some test cases for the same, once I finish the other I'm progress task.

**Comment by miguelurtado** [comment]
👏 like this change.

**Review by tejaswinichile — APPROVED** [review]
LGTM 💯 

Thanks, @robguthrie For these changes.

Will merge this PR once the bundle audit is fixed.

**Pull request merged**
