### PR TITLE
feat: Add ability to paste file/image from clipboard

### LINKED ISSUE #5594: Take Screenshot from Widget or Paste Image
Sometimes client need to show what problem they are facing by sending screenshot.
Currently, to do this they should save it first to disk then select the image using attachment.

**Solution**
It will be better if Chatwoot has internal screenshot tool that the client can use it directly from the widget.

**Alternative**
If the solution above can't be delivered, another alternative is allowing client to paste the image after taking screnshot from external tool, without saving it first to disk and attach it using attachment button.

### PR DESCRIPTION
**Pull request by KubesDavid**
# Pull Request Template

## Description

Fixes #5594

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by nithindavid — APPROVED** [review]
🔥

**Comment by muhsin-k** [comment]
@KubesDavid Thanks for the PR. I found two issues while testing
1. While pasting the files, the file's name is also filled.
2. Attachment size check is not handled. Please take care of that case well. [Reference](https://github.com/chatwoot/chatwoot/blob/develop/app/javascript/widget/components/ChatAttachment.vue#L110)

**Comment by KubesDavid** [comment]
Hey @muhsin-k,
1. I fixed a bug with inserting the filename
2. Checking the file size works fine, but I found a problem with mixing data types

**Comment by muhsin-k** [comment]
@KubesDavid Thanks for the changes. We will test it out again, and merge the PR.

**Review by muhsin-k — APPROVED** [review]
Tested in staging and working fine 💯 .

**Review by iamsivin — APPROVED** [review]

**Comment by punyaikhwan** [comment]
Hello, any update for the blocked merging above?

**Pull request merged**
