### PR TITLE
feat: add audit for web channel

### PR DESCRIPTION
**Pull request by vishnu-narayanan**
# Pull Request Template

## Description

Fixes https://linear.app/chatwoot/issue/CW-2027/subsequent-update-events-to-inbox-object-are-not-logged

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by vishnu-narayanan** [comment]
@pranavrajs Does this approach work?

**Comment by pranavrajs** [comment]
@vishnu-narayanan This is an approach, but it is not feasible. The channel id is not shared to the customer in the UI. There is no way they can relate to it. It needs to be under the inbox update itself.

**Comment by pranavrajs** [comment]
On further investigation, I believe you can use associated_audits. Please see the docs [here](https://github.com/collectiveidea/audited#associated-audits).

**Comment by vishnu-narayanan** [comment]
Closing in favor of https://github.com/chatwoot/chatwoot/pull/7396

**Pull request closed without merging**
