### PR TITLE
chore: Update spinner component to use SVG instead of css

### PR DESCRIPTION
**Pull request by nithindavid**
## Description
Refactors Spinner component use a simple SVG instead of the CSS spinners in use. 

1. We were using a css class in some components and component in other files. I have refactored this so that there will be only one spinner
2. Removes the `Spinner` vue file import as `woot-loader` will work
3. Added size and color scheme options for the spinner component
4. The buttons using this pass the color scheme down
5. Support for dark mode
6. Added a `<LoadingState />`  component to use across the app for spinner + loading text

Color and size options can be found here - https://www.figma.com/file/UGuR6jAQUnTm5IJxdENnGp/Design-system?type=design&node-id=20614%3A10353&mode=design&t=JSmS9DPY8tPwAcjy-1
Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by scmmishra — APPROVED** [review]

**Review by iamsivin — COMMENTED** [review]
@nithindavid I tested this PR locally and could find any issue in the dashboard, and for the widget, the start conversation button with the loader has some alignment and color issues. And can you check the components in the attached image, which is using `<spinner/>` instead of `<woot-spinner/>`.

**Screenshot**
Screenshot 2023-11-07 at 1 40 51 PM

**Files**
image

**Comment by scmmishra** [comment]
Looks good overall, just found a few places the colors can be improved, like the green button here

CleanShot 2023-11-08 at 11 10 19@2x

Perhaps we can set the the spinner colors to have some opacity like `text-gray-900/30` and `fill-gray-300/30`, that way it will appear tinted for any background.

**Review by muhsin-k — APPROVED** [review]

**Review by iamsivin — APPROVED** [review]

**Comment by nithindavid** [comment]
@scmmishra I have made the colors transparent.

**Comment by nithindavid** [comment]
Will reopen once we create the new spinner component

**Pull request closed without merging**
