### PR TITLE
refactor: handling keyboard shortcuts 

### PR DESCRIPTION
**Pull request by scmmishra**
# Pull Request Template

## Description

Fixes https://linear.app/chatwoot/issue/CW-3183/keyboard-shortcuts-doesnt-work

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by scmmishra** [comment]
@pranavrajs @iamsivin and I worked on refactoring the keyboard handling. It's a much more declarative way to handle shortcuts and does require the usage of `KeyboardHelper.js` a typical config for shortcuts will look like this

```js
const events = {
  'Alt+KeyM': {
    action: () => this.$refs.arrowDownButton?.$el.click(),
    allowOnFocusedInput: true,
  },
  'Alt+KeyE': this.resolveOrToast,
  '$mod+Alt+KeyE': async event => {
    // handle event as you need it to
    event.preventDefault();
  },
};
```

It supports passing the handler function directly, or passing an object with config like `allowOnFocusedInput`

**Comment by iamsivin** [comment]
## Keyboard Shortcuts

### Tiny keys
**Mac**: $mod = Meta (⌘)
**Windows/Linux**: $mod = Control

### Keyboard shortcuts allowed on the input focus

`$mod+KeyK` -> Open CMD bar 

`Enter` -> **Send message** (Based on UI settings)
`$mod+Enter` -> **Send message** (Based on UI settings)

`Alt+KeyJ` -> Navigate with the chat list (previous)
`Alt+KeyK` -> Navigate with the chat list (next)

`Alt+KeyM` -> Open resolve action dropdown

`Escape` -> Close label dropdown/ Close emoji picker/ Close mentions 

`ArrowUp/ArrowDown` -> Move up/down in the phone input dropdown (edit contact)
`Enter` -> Select the country in the phone input (edit contact)

`Alt+KeyP` -> Move to private note editor and focus
`Alt+KeyL` -> Move back to the reply editor and focus
`Alt+KeyA` -> Open file upload

`$mod+Enter` -> Add contact notes  
`ArrowUp/ArrowDown` -> Navigate through the dropdown list  

**Mention Box(Canned response, Variables etc) / Tag Agent / Search in public help center / Phone input (Widget pre-chat form)**
`ArrowUp/Control+KeyP` -> Move to previous
`ArrowDown/Control+KeyN` -> Move to next 

### Keyboard shortcuts Not allowed on the input focus

`Alt+KeyC` -> Go to the dashboard
`Alt+KeyV` -> Go to the contacts dashboard
`Alt+KeyR` -> Go to the reports overview
`Alt+KeyS` -> Go to the settings agent list

`Alt+KeyN` -> Change the chat list tabs (Mine, all, unassigned)

`Alt+KeyE` -> Resolve conversation
`$mod+Alt+KeyE` -> Resolve conversation and open next $mod+Slash -> Open keyboard shortcuts modal

`$mod+Escape` -> Close keyboard shortcuts modal

`$mod+KeyZ` -> Undo the AI message and set it to the initial message 

`KeyL` -> Open the label dropdown (Conversation and contact)
`Escape` -> Close the label dropdown (Conversation and contact) (Enabled on input focus)

`Alt+KeyO` -> Open conversation sidebar

`Escape` -> Close pop-out editor

`ArrowLeft/ArrowRight` -> Move attachments left/right in the gallery view
`Escape` -> Close the gallery view

`Slash` -> Focus the search in the insert article modal 
`Escape` -> Close insert article modal (Enabled on input focus)
  
  
  CC @pranavrajs @scmmishra

**Review by scmmishra — COMMENTED** [review]
When inside the input box we should stop propagating the events further

https://github.com/chatwoot/chatwoot/assets/18097732/96445ad6-8efb-4b2a-bd7b-fa58cc4b43fd

@iamsivin

**Comment by scmmishra** [comment]
@iamsivin there is a `Switch to the next conversation status` shortcut in the Keyboard shortcuts modal, but it doesn't do anything, PTAL at that, we can remove it if not required

**Review by scmmishra — COMMENTED** [review]
There is a usage of `buildHotKeys` in `app/javascript/superadmin_pages/views/playground/Index.vue` see if we can update that too. We'll be able to completely remove `buildHotKeys` then

**Comment by iamsivin** [comment]
> @iamsivin there is a `Switch to the next conversation status` shortcut in the Keyboard shortcuts modal, but it doesn't do anything, PTAL at that, we can remove it if not required

@scmmishra It was there before, but I think it's been removed. [Commit]( https://github.com/chatwoot/chatwoot/pull/2672/files#diff-2ee8159ddc3e6d65d7996953d1728b38f21a6da595c045a36eefa9a0c109aacaR24). I removed it from the keyboard shortcut modal.

**Comment by iamsivin** [comment]
> There is a usage of `buildHotKeys` in `app/javascript/superadmin_pages/views/playground/Index.vue` see if we can update that too. We'll be able to completely remove `buildHotKeys` then

@scmmishra I removed `buildHotKeys` from this file. Can you test it out on the super admin page? https://github.com/chatwoot/chatwoot/pull/9242/commits/cbdb33aadc40902832fb1ec9d0213edd1e260bc6

**Comment by scmmishra** [comment]
> When inside the input box we should stop propagating the events further
> 
>  CleanShot.2024-04-25.at.12.58.07.mp4 
> @iamsivin

Seems like there is not straightforward way to do this right now, need to discuss further, and can be dealt with in a separate PR

**Review by iamsivin — APPROVED** [review]

**Review by muhsin-k — APPROVED** [review]

**Pull request merged**
