### PR TITLE
fix: "wa_source_id" function return value

### PR DESCRIPTION
**Pull request by civilcoder55**
# Pull Request Template

## Description

fix wa_source_id return value at ContactInboxBuilder class

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

fixing an issue, no need to add new tests

## Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by sojan-official** [comment]
@civilcoder55  Could you provide more context on the changes?
ref: https://www.chatwoot.com/docs/handbook/engineering/pr-guidelines#avoid-cosmetic-changes

**Comment by civilcoder55** [comment]
@sojan-official 
there was an issue with "wa_source_id" return value
`"#{@contact.phone_number}.delete('+')" `
resulting in appending ".delete('+')" literally at the end of value

**Comment by civilcoder55** [comment]
@sojan-official

**Comment by sojan-official** [comment]
@civilcoder55 sorry for the delay in getting to this. I got what you meant. let me check if we need to add any migrations to mix any existing source_ids generated with this and have this PR merged.

**Review by sojan-official — APPROVED** [review]

**Pull request merged**
