### PR TITLE
Fix 1145 by allowing DATABASE_URL env to take presedence over individ…

### PR DESCRIPTION
**Pull request by quacktacular**
Please see here: https://github.com/chatwoot/chatwoot/issues/1145

Allows the docker entrypoint to use the full connection string (DATABASE_URL) to check if Postgres is ready. Necessary for environments with non standard Postgres ports.

### CODE REVIEW

**Comment by julianwachholz** [comment]
I recently wanted to try out chatwoot and this was blocking me. Can I help to get this merged?

**Comment by pranavrajs** [comment]
@julianwachholz Sure, we will get this one tested and merged today/tomorrow.

**Comment by sojan-official** [comment]
note for future: if the rails_env is not production when running rake db tasks, it tries to modify the test databases and throws error. ( as the values are picked from database.yml ) . 

https://stackoverflow.com/questions/44069951/docker-compose-rails-wont-respect-the-database-url-to-connect-to-postgres

**Review by sojan-official — APPROVED** [review]
LGTM

**Pull request merged**
