### PR TITLE
Slightly increase sidebar width

### PR DESCRIPTION
**Pull request by jtraulle**
## Description

This PR, propose to slightly increase the width of the sidebar to allow translated strings in French to be in one line only.

See https://github.com/chatwoot/chatwoot/issues/688#issuecomment-616211237 for more info and visual screenshots of change.

### CODE REVIEW

**Comment by pranavrajs** [comment]
@jtraulle Sorry that we missed the comment earlier. I would like to approach this problem differently. I don't think it is a scalable solution to the problem we have, let us say there is a long inbox name which does not fit to the width. Increasing width would not solve that problem. 

I would prefer to have the text truncated like the one given below and show the full text as a popup when we hover on the item.

Screenshot 2020-04-27 13 21 20

Let me know what you think.

**Comment by jtraulle** [comment]
@pranavrajs Thanks for your reply :slightly_smiling_face:  While I understand that this should be scalable for as many languages as possible, I tend to find that it is more readable when we can read the complete string.

So maybe a combination of both solution (increasing size of the sidebar : this would fit 80% of languages I suppose and a CSS ellipsis for the rare translations that would not fit).

**Comment by pranavrajs** [comment]
@jtraulle Sounds good, could you make that change to truncate the text as well?

Please test this in tablet view as well.

**Comment by jtraulle** [comment]
OK, I'll do that. Was stuck yesterday trying to install Yarn dependencies but with the ongoing lock-down situation worldwide, network congestion is more frequent. Finally got it installed and successfully build the docker image.  I'll update the PR ASAP :slightly_smiling_face:

**Comment by pranavrajs** [comment]
> @pranavrajs OK, I'll do that. Was stuck yesterday trying to install Yarn dependencies but with the ongoing lock-down situation worldwide, network congestion is more frequent. Finally got it installed and successfully build the docker image. I'll update the PR ASAP 🙂

Sounds good. Yeah, the network congestion is real.  Hope you are staying safe.

**Comment by jtraulle** [comment]
@pranavrajs I have added the ellipsis. I search for the tooltips definition and found them in /app/javascript/dashboard/i18n/default-sidebar.js but noticed that the **toolTip** keys does not get translated. For example, tooltip _Conversation from all subscribed inboxes_ (for the **Conversations** menu item) does not get translated. Is it possible to change that and allow the **toolTip** to be translated as well ? I search what to modify but without luck ... Thanks for your help :slightly\_smiling\_face:

**Comment by pranavrajs** [comment]
@jtraulle I'll test this out tomorrow. 

> I search for the tooltips definition and found them in /app/javascript/dashboard/i18n/default-sidebar.js but noticed that the toolTip keys does not get translated. For example, tooltip Conversation from all subscribed inboxes (for the Conversations menu item) does not get translated. 

This tooltip is only used in Conversations. I think we can get rid of that attribute all together, it doesn't add much value now.

**Comment by pranavrajs** [comment]
@jtraulle Nice work!

I found a couple of minor issues.

Screenshot 2020-06-09 12 19 05

1. Letters appear to be cut due to some reason, please see `g` in Agentes
2. I would like to have a tooltip on the last one. Right now, the user cannot see the entire text

**Comment by caseyjhol** [comment]
Setting

```css
.wrap {
    padding: $space-small 0;
    margin: -#{$space-small} 0;
}
```
should fix the issue with the bottoms of letters being clipped.

**Comment by sojan-official** [comment]
In our current design iteration, we are trying to expand the conversation workspace area and to that, we are evaluating shrinking the sidebar even further 😅 . I guess the changes here will become irrelevant then.

**Pull request closed without merging**
