### PR TITLE
feat: Revamp conversation permissions based on teams

### PR DESCRIPTION
**Pull request by sojan-official**
This PR will enable members of a team to access team-assigned conversations irrespective of whether they are added as inbox members. This will be helpful in cases where you need more restricted access to conversations than the default all-access model. 

Fixes https://github.com/chatwoot/chatwoot/issues/6422

### CODE REVIEW

**Comment by sojan-official** [comment]
- [ ] ensure the agent has permission to conversation by URL if they are part of the team
- [ ] specs for the changes

**Comment by pedromagalhaesgm** [comment]
Hello, is there a prediction of data to release this feat? We in Brazil are looking forward to it!

**Comment by sojan-official** [comment]
Note: We will need to revert the assignable agents change and switch to conversations/id/assiganable_agents

cc: @pranavrajs

**Comment by pranavrajs** [comment]
@thiagoinovmi We expect it to get it out by next week.

**Comment by Shiba1805** [comment]
This is live now?

**Comment by thiagoinovmi** [comment]
> @thiagoinovmi We expect it to get it out by next week.

I didn't see an update for this feature in 3.1.1. It still continues the same way. I noticed something even more serious, when an agent is not in the list of agents in the inbox, if a filter is made to find all conversations, the conversation appears, even if it is not included in the list of agents in the inbox. (I tested it with the chat channel on the website.

**Comment by pranavrajs** [comment]
> I didn't see an update for this feature in 3.1.1. It still continues the same way. I noticed something even more serious, when an agent is not in the list of agents in the inbox, if a filter is made to find all conversations, the conversation appears, even if it is not included in the list of agents in the inbox. (I tested it with the chat channel on the website.

@thiagoinovmi Can you please raise a separate issue with a screencast?

**Comment by pranavrajs** [comment]
Closing this for now as we will pick it up along with the permissions revamp.

**Pull request closed without merging**
