### PR TITLE
feat: Add inbox details endpoint

### LINKED ISSUE #5514: Enable CSAT, Greetings Messages, Out of office message via API Channel
Please help us by enabling messages through the API.
Currently not receiving messages from:

*Welcome message
*CSAT
*Out of business hours

### PR DESCRIPTION
**Pull request by CristianDuta**
## Description

This change targets the public API and is related to the Inbox with channel type API.
Exposes public inbox details under `/public/api/v1/inboxes/{inbox_identifier}`. This allows access to feature flags and business hours configured for the inbox.

Solves part of #5514 

## Why is this important?

Currently there is no way to tell, before sending a message, if we are within business hours or if a specific feature is enabled for the Inbox with channel type API.

The widget currently has this feature by fetching the working hours and calculating the "online status" based on the inbox timezone. 

Once the feature flags are available, you can then expect communication over the websocket for some specific messages (CSAT, greeting messages)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Manual test:
 - Set up a local environment
 - Create Inbox with API Channel
 - do GET request to `/public/api/v1/inboxes/{inbox_identifier}`

Automated test:
 - `spec/controllers/public/api/v1/inbox/inboxes_controller_spec.rb`

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by intelnexoec** [comment]
@sojan-official

**Comment by sojan-official** [comment]
@CristianDuta Thanks a lot for working on this. The changes look good to me. This won't close https://github.com/chatwoot/chatwoot/issues/5514 , Since the expectation, there is to have the automated message pushed through the webhooks.  

But this PR adds value since the clients build over public API to be able to read business hours and other configurations if required.  We will have it tested one more time and have it merged

**Comment by CristianDuta** [comment]
> This won't close #5514 , Since the expectation, there is to have the automated message pushed through the webhooks.
I can create a follow-up PR to get this done. I will update the ticket so that it states it only solves half of the problem.

> We will have it tested one more time and have it merged
Thank you so much for investing time to do this. I really appreciate it. Please let me know if I need to do any changes.

**Comment by CristianDuta** [comment]
Hi @sojan-official, any progress with this? Cheers! 😁

**Comment by sojan-official** [comment]
@CristianDuta, apologies for the delay on this. Thanks again for the changes.

**Comment by CristianDuta** [comment]
> @CristianDuta, apologies for the delay on this. Thanks again for the changes.

@sojan-official 
No apology needed. Thank you so much for investing time and checking this out, much appreciated. Cheers!

**Pull request merged**
