### PR TITLE
Made some grammatical changes

### PR DESCRIPTION
**Pull request by bharat-patodi**
The changes are minor.
Hope they are helpful.

### CODE REVIEW

**Comment by sojan-official** [comment]
@bharat-patodi  thanks a lot for looking into this :D

**Comment by bharat-patodi** [comment]
Thanks Sojan.

Would you guys be interested in creating a full-fledged docs structure for Chatwoot? 
I am starting out as a technical writer and would love to take this on.

**Comment by sojan-official** [comment]
@bharat-patodi currently we are keeping the docs here https://github.com/chatwoot/chatwoot/tree/develop/docs . We do want to document all the available features in chatwoot. So would love to get any help around this. 

We will switch over to more of a UI oriented approach for editing these docs once we have knowledge base feature built-in on chatwoot .

**Comment by bharat-patodi** [comment]
I'll be looking into the docs.
Should take me some time to come up with a major change while I pick up the basics of docker and postgres.
Till that time, I'll keep making grammatical updates.

Thanks for the opportunity @sojan-official 🌞

**Comment by sojan-official** [comment]
@bharat-patodi  No problem. Do let us know if you end up need help in setting up anything.  
and thanks again for looking into this. 

we are also available on https://discord.gg/cJXdrwS

**Pull request merged**
