### PR TITLE
Fix lowercase label and team name in sidebar

### PR DESCRIPTION
**Pull request by virajbahulkar**
# Pull Request Template

## Description

This PR fixes issue of the labels and team names from the sidebar shown in lowercase even if entered in capitalized at the time of the creation.

Fixes # (issue)
#3147 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by nithindavid** [comment]
@virajbahulkar Any update on this?

**Comment by sojan-official** [comment]
@virajbahulkar, this is more of a backend issue, where we downcase all the team names before it is saved.

https://github.com/chatwoot/chatwoot/blob/0c9b682329489c4a1a2fe5258db98b68153470f6/app/models/team.rb#L33

It was a product decision taken at that time. So if we have to preserve the casing, we will have to remove this extra validation.

**Comment by sojan-official** [comment]
@virajbahulkar `titelize` would be a cosmetic fix. but the original issue states 

>Currently, team names, and labels are getting lowercased on the dashboard and in the conversation settings. I believe it should be displayed in the same way the names are typed. 

So if someone types in `CoolLabel` or `CoolTeam` they would still want the case to be preserved, which would be the predictable behavior.   

cc: @pranavrajs

**Comment by pranavrajs** [comment]
Closing this as there was no activity for a long time.

**Pull request closed without merging**
