### PR TITLE
Reduce long peer dependencies warning

### PR DESCRIPTION
**Pull request by ghosteathuman**
## Description

A long unmet peer dependencies warning list appears when running `yarn`.

Current:
```
warning " > @babel/preset-env@7.8.4" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/helper-compilation-targets@7.8.4" has unmet peer dependency "@babel/core@^7.0.0".
warning "@babel/preset-env > @babel/plugin-proposal-async-generator-functions@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-proposal-dynamic-import@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-proposal-json-strings@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-proposal-nullish-coalescing-operator@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-proposal-object-rest-spread@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-proposal-optional-catch-binding@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-proposal-optional-chaining@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-proposal-unicode-property-regex@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-syntax-async-generators@7.8.4" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-syntax-dynamic-import@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-syntax-json-strings@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-syntax-nullish-coalescing-operator@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-syntax-object-rest-spread@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-syntax-optional-catch-binding@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-syntax-optional-chaining@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-syntax-top-level-await@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-transform-arrow-functions@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-transform-async-to-generator@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-transform-block-scoped-functions@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-transform-block-scoping@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-transform-classes@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-transform-computed-properties@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-transform-destructuring@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-transform-dotall-regex@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-transform-duplicate-keys@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-transform-exponentiation-operator@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-transform-for-of@7.8.4" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-transform-function-name@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-transform-literals@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-transform-member-expression-literals@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-transform-modules-amd@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-transform-modules-commonjs@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-transform-modules-systemjs@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-transform-modules-umd@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-transform-named-capturing-groups-regex@7.8.3" has unmet peer dependency "@babel/core@^7.0.0".
warning "@babel/preset-env > @babel/plugin-transform-new-target@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-transform-object-super@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-transform-parameters@7.8.4" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-transform-property-literals@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-transform-regenerator@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-transform-reserved-words@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-transform-shorthand-properties@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-transform-spread@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-transform-sticky-regex@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-transform-template-literals@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-transform-typeof-symbol@7.8.4" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-transform-unicode-regex@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-proposal-unicode-property-regex > @babel/helper-create-regexp-features-plugin@7.8.3" has unmet peer dependency "@babel/core@^7.0.0".
warning " > foundation-sites@6.5.3" has unmet peer dependency "jquery@>=2.2.0".
warning " > foundation-sites@6.5.3" has unmet peer dependency "what-input@>=4.1.0".
warning " > url-loader@2.3.0" has unmet peer dependency "webpack@^4.0.0".
warning " > vue-loader@15.9.0" has unmet peer dependency "css-loader@*".
warning " > vue-loader@15.9.0" has unmet peer dependency "webpack@^3.0.0 || ^4.1.0 || ^5.0.0-0".
warning "@vue/babel-preset-app > @babel/plugin-proposal-decorators@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@vue/babel-preset-app > @babel/plugin-syntax-jsx@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@vue/babel-preset-app > @babel/preset-env@7.3.4" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@vue/babel-preset-app > @vue/babel-preset-jsx@1.1.2" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@vue/babel-preset-app > @babel/plugin-proposal-decorators > @babel/plugin-syntax-decorators@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@vue/babel-preset-app > @vue/babel-preset-jsx > @vue/babel-plugin-transform-vue-jsx@1.1.2" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@vue/babel-preset-app > @vue/babel-preset-jsx > @vue/babel-sugar-functional-vue@1.1.2" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@vue/babel-preset-app > @vue/babel-preset-jsx > @vue/babel-sugar-inject-h@1.1.2" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@vue/babel-preset-app > @vue/babel-preset-jsx > @vue/babel-sugar-v-model@1.1.2" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@vue/babel-preset-app > @vue/babel-preset-jsx > @vue/babel-sugar-v-on@1.1.2" has unmet peer dependency "@babel/core@^7.0.0-0".
warning " > babel-core@7.0.0-bridge.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning " > babel-jest@25.1.0" has unmet peer dependency "@babel/core@^7.0.0".
warning "babel-jest > babel-preset-jest@25.1.0" has unmet peer dependency "@babel/core@^7.0.0".
warning "babel-jest > babel-preset-jest > @babel/plugin-syntax-bigint@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning " > eslint-config-airbnb@17.1.1" has unmet peer dependency "eslint-plugin-react@^7.14.2".
warning " > eslint-import-resolver-webpack@0.11.1" has unmet peer dependency "webpack@>=1.11.0".
warning " > webpack-dev-server@3.10.3" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
warning "webpack-dev-server > webpack-dev-middleware@3.7.2" has unmet peer dependency "webpack@^4.0.0".
```

After:
```
warning " > foundation-sites@6.5.3" has unmet peer dependency "jquery@>=2.2.0".
warning " > foundation-sites@6.5.3" has unmet peer dependency "what-input@>=4.1.0".
warning " > url-loader@2.3.0" has unmet peer dependency "webpack@^4.0.0".
warning " > vue-loader@15.9.0" has unmet peer dependency "css-loader@*".
warning " > vue-loader@15.9.0" has unmet peer dependency "webpack@^3.0.0 || ^4.1.0 || ^5.0.0-0".
warning " > eslint-config-airbnb@17.1.1" has unmet peer dependency "eslint-plugin-react@^7.14.2".
warning " > eslint-import-resolver-webpack@0.11.1" has unmet peer dependency "webpack@>=1.11.0".
warning " > webpack-dev-server@3.10.3" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
warning "webpack-dev-server > webpack-dev-middleware@3.7.2" has unmet peer dependency "webpack@^4.0.0"
```

## Type of change

Changes done in this PR:

1. Move almost all `babel` packages to `devDependencies`.
2. Rearrange packages alphabetically.

### CODE REVIEW

**Comment by pranavrajs** [comment]
@ghosteathuman  Thanks for the PR. Changes seems to be okay. I will test it out tomorrow and merge.

**Comment by ghosteathuman** [comment]
New commits are to fix failing tests.

**Comment by pranavrajs** [comment]
Screenshot 2020-03-06 at 3 01 30 PM


@ghosteathuman Could you please run `RAILS_ENV=production bundle exec rake assets:precompile` and see the errors?

**Comment by ghosteathuman** [comment]
> @ghosteathuman Could you please run `RAILS_ENV=production bundle exec rake assets:precompile` and see the errors?

@pranavrajs I fixed the issues related with that. I had to revert some changes.

**Comment by ghosteathuman** [comment]
> @ghosteathuman Could you please run `RAILS_ENV=production bundle exec rake assets:precompile` and see the errors?

@pranavrajs I fixed the issues related with that. I had to revert some changes.

**Pull request merged**
